### ISSUE TITLE
Add secure secret management 

### ISSUE THREAD

**Issue by timfpark** [Microsoft/bedrock#10]
Ala Azure Key Vault or Hashicorp Vault

**Comment by jmspring** [comment]
Design should address supporting multiple approaches.  Specifically:
- Azure KeyVault
- Hashicorp Vault

Docs should contain information on how secrets are accessed within the vault.

**Comment by dtzar** [comment]
@jmspring 
This can be useful documentation for the key vault flex volume implementation, 
https://github.com/shwetams/containers-rest-cosmos-aks-java/blob/master/infrastructure/AKSconfiguration.md
with complimentary helm chart to enable the ENV vars from the volume mount
https://github.com/shwetams/containers-rest-cosmos-aks-java/blob/b3925f27415346b470cce064ae49613d1ecb3f60/gitops/charts/chakraview/templates/deployment.yaml#L31
https://github.com/shwetams/containers-rest-cosmos-aks-java/blob/b3925f27415346b470cce064ae49613d1ecb3f60/gitops/charts/chakraview/templates/deployment.yaml#L42-L53
