### ISSUE TITLE
`spk service create` should allow for arguments to be passed into the `az acr build` process

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#1006]
**As a:** developer

**I want:** to be able to pass arguments into the container build process.

**Describe the solution you'd like:**

Building of the Dockerfile assumes there are no inputs into the build process.  One possible example would be to add a variable group and script the inputs to generate  the build are string.  

An example of doing such is as follows:

```
          - script: |-
              set -e
              export BUILD_REPO_NAME=$(echo $(Build.Repository.Name)-jmsgumbo-svc | tr '[:upper:]' '[:lower:]')
              echo "Image Name: $BUILD_REPO_NAME"
              cd ./
              echo "az acr build -r $(ACR_NAME) --image $BUILD_REPO_NAME:$(echo $(Build.SourceBranchName) | tr / - | tr . -)-$(Build.BuildNumber) ."
              az acr build -r $(ACR_NAME) --image $BUILD_REPO_NAME:$(echo $(Build.SourceBranchName) | tr / - | tr . -)-$(Build.BuildNumber) .
            displayName: ACR Build and Publish
```

To:

```
          - script: |-
              set -e
              export BUILD_REPO_NAME=$(echo $(Build.Repository.Name)- | tr '[:upper:]' '[:lower:]')
              echo "Image Name: $BUILD_REPO_NAME"
              cd ./
              export DOCKER_BUILD_FILE=$(if [ -z "$SERVICE_DOCKERFILE_PATH" ]; then echo "DockerFile"; else echo "$SERVICE_DOCKERFILE_PATH"; fi)
              if [ ! -z "$SERVICE_NAME_BASE" ]; then
                arg_str=""
                for v in project_path version_suffix test_logger skip_tests docker_entrypoint framework_release framework_build; do
                arg_str=""
                for v in project_path version_suffix test_logger skip_tests docker_entrypoint framework_release framework_build; do
                  valueKey=$(echo "service_""$v" | tr '[:lower:]' '[:upper:]')
                  arg_str="$arg_str --build-arg $v=\"${!valueKey}\""
                done
              fi
              echo "az acr build -r $(ACR_NAME) --file $DOCKER_BUILD_FILE $arg_str --image $BUILD_REPO_NAME:$(Build.SourceBranchName)-$(Build.BuildNumber) ."
              az acr build -r $(ACR_NAME) --file $DOCKER_BUILD_FILE $arg_str --image $BUILD_REPO_NAME:$(Build.SourceBranchName)-$(Build.BuildNumber) .
            displayName: ACR Build and Publish
```

**Acceptance Criteria:**
- [x] Design documentation on implementation
- [x] A flag to add a variable-group and a list of variables to be used as build args during `spk service create`
- [x] Enforcing variable name cases: 
    - https://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html:
    - >uppercase letters, digits, and the '_' (underscore)
    - Create a warning for variable format
- [ ] Command to create a new variable-group in azure devops with given variables and values (some of which will be secrets).
  - [ ] does `spk variable-group create` do what we need already?
    - We may be deprecating that command. For now we'll link documentation and guidance on how to manually create variable groups though the az cli or UI.
- [ ] reference documentation on bedrock repository during walkthrough components
- [x] updated smoke tests with build arguments

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@jmspring This seems pretty seems like a legitimate concern for a user. I'm thinking that we can utilize [Azure DevOps Yaml templates](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops) to abstract out the docker registry pushing behavior.

The idea would be that the template is essentially a function that takes arguments such as 

- ACR_NAME
- BUILD_REPO_NAME
- DOCKER_ARGS
- $(Build.SourceBranchName)
- $(Build.BuildNumber)
- _etc..._

And would allow a user to provider their own implementation. The contract would be that the user's own implementation would need to use the args above and push the image to the ACR. Just a thought.

cc @mtarng @evanlouie @bnookala

**Comment by evanlouie** [comment]
@jmspring the example you shows most of the docker build args being stored in env variables. Are these dynamic in any way? or can they be reliably stored in a variable group?

**Comment by jmspring** [comment]
If you look in the above snippet, the args are read from a variable group ... this was one solution to the problem.  In general, we should allow for some mechanism where we can specify specific args that are passed into the docker file.

**Comment by andrebriggs** [comment]
I suggest @jmspring to meet with @evanlouie @mtarng and get a conclusion. In the mean time I've added this task to an epic #1111

**Comment by evanlouie** [comment]
@jmspring and @yradsmikham to sync on AC after design doc synced on

**Comment by mtarng** [comment]
Ongoing design doc: https://github.com/CatalystCode/spk/blob/yvonne.designDoc/technical-docs/designs/services/acrBuildArguments.md

**Comment by mtarng** [comment]
Per pipeline behavior and https://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html:

enforce variable names in a variable group to only consist of:
>uppercase letters, digits, and the '_' (underscore)

@yradsmikham

**Comment by yradsmikham** [comment]
In addition to https://github.com/microsoft/bedrock-cli/pull/16, I will open a new PR on the Bedrock repo to update documentation.
