### ISSUE TITLE
SPK needs to better handle existing service repository

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#1009]
**Describe the bug:** SPK has a certain set of entries in .gitignore.  If the project for a service already exists `spk service create .`, any relevant additions to existing files should be appended (gitignore for instance).  Additionally, if something like a Dockerfile already exists (but in a different location), a default one should not be created.

**Comment by andrebriggs** [comment]
@jmspring I'm hearing two requests here. Is the below correct?
* If a `.gitignore` file exists `spk project init` should not create/overwrite but instead append to it (and deduce) 
* if a Dockerfile already exists then `spk service create` should not create/overwrite

**Comment by mtarng** [comment]
> - If a .gitignore file exists spk project init should not create/overwrite but instead append to it (and deduce)

This is valid and seems like we could easily handle this.

> - if a Dockerfile already exists then spk service create should not create/overwrite

This is already the case. Let me know if anyone has an example showing otherwise.

@jmspring @andrebriggs

**Comment by andrebriggs** [comment]
@jmspring the actionable task out of this seems to be 
> If a .gitignore file exists spk project init should not create/overwrite but instead append to it (and deduce)

I created https://github.com/microsoft/bedrock/issues/1081. 

Please re-open this bug if that doesn't suffice
