### ISSUE TITLE
Spk build pipelines should set image repository in the build

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#1015]
**As a:**
spk user
**I want:**
The spk service build and update pipeline to also pin a container repository
**So that:**
The generated manifest points to the ACR repository and image that is being built.
**Describe the solution you'd like:**
When i create a service, the build and update pipeline also runs fab set for both the image.tag *and* the image.repository `mycontainerregistry.azurecr.io/image name`

**Acceptance Criteria:**
- [x] in the second stage of the the service build and update pipeline, when setting image.tag via fabrikate, also sets image.repository. The name of the acr is already in the variable group. 

**Describe alternatives you've considered:**
Currently the user is expected to overwrite the `image.repository` value manually in a config file in the hld repository

**Additional context:**
By default, when creating a helm chart though helm, there are 3 default variables for image:
```
image:
  repository: mycontainerregistry.azurecr.io/mycontainername
  tag: latest
  pullPolicy: Always
```
the build pipeline sets `image.tag`, but we need to set `image.repository` at least once.

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
If this is marked `good first issue` why the rush to get this in without a corresponding update to the integration tests.
