### ISSUE TITLE
[Spike] Explore modify Voting App to more robust production app

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#1021]
**As a:**
User 

**I want:**
To work with a sample application

**So that:**
I can understand the challenges of running workflows in production

**Describe the solution you'd like:**

**Acceptance Criteria:**
- [ ]  Check the feedback from the OneWeek hack
Evaluate the effectiveness of teaching production workflows with the voting app.

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by NathanielRose** [comment]
@andrebriggs Can this be closed?
