### ISSUE TITLE
Inconsistent private repo authorization behavior in SPK generated pipelines 

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1025]
**Describe the bug:**
When a helm chart repo is manually created in an AzDO project and is associated with a SPK service via `spk service create $app_name -d $services_dir -p "$app_name/chart" -g $helm_repo_url -b master` the SPK generated HLD to Manifest pipeline may fail due to not having the helm repo url and PAT env var defined in the `access.yaml` of the HLD repo. 

**To Reproduce:**
This issue was resolved when adding the red circled line below to the access.yaml

<img width="968" alt="image" src="https://user-images.githubusercontent.com/3119513/75121591-501f0400-564a-11ea-9d82-9eff80145b64.png">

For instance this [post](https://github.com/CatalystCode/spk/pull/329#issuecomment-590035240) describes the `fab install` error that occurs when the helm chart repo is not defined in the HLD access.yaml.

This issue appears inconsistent. Below is `access.yaml` that doesn't specify the helm chart repo.
<img width="924" alt="image" src="https://user-images.githubusercontent.com/3119513/75121618-8a88a100-564a-11ea-8d3c-e7525c4711b7.png">

There are no HLD to Manifest pipeline issues with this instance:
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/3119513/75121627-a3915200-564a-11ea-8f0d-e4eeab7d527f.png">
**Expected behavior:**
The issue could simply be a misunderstanding of the SPK documentation or some sort of environmental differences. 

- What is the correct method  to add helm chart repos that are located in the same AzDO project as the application repo? 
- Do these helm chart repos need explicit permission in `access.yaml`? 
- Is it possible for us to automate the additional of the helm chart repo url and PAT to the access.yaml in the `spk reconcile` process from the `spk service create` input?

**Does this require updates to documentation?:**
Probably

**Comment by mtarng** [comment]
So I’m not sure why your pipeline is able to pull the helmcharts correctly @andrebriggs. Currently adding a private helm git repo to an access.yaml is a required manual step. 

This issue was created to explore how we would automate the process through spk.
https://github.com/microsoft/bedrock/issues/914

**Comment by andrebriggs** [comment]
@mtarng The lifecycle pipeline generates a pull request that creates the `access.yaml` file and the entire HLD structure for the Application repo it is associated with. Consequently there doesn't seem to be a way to manually inject the the url/env var key-value pairing in `access.yaml` without the lifecycle pipeline failing first. Correct?

If so this is why I suggest we provide the necessary metadata when calling `spk service create`. Since the helm info is required when we call `spk service create` I can't think of a way to to inject this in without a failure in the lifecycle pipeline initially

**Comment by bnookala** [comment]
@andrebriggs 

> Consequently there doesn't seem to be a way to manually inject the the url/env var key-value pairing in access.yaml without the lifecycle pipeline failing first. Correct?

As @mtarng noted, this issue captures how one might be able to handle access tokens for other/external private repositories in the HLD, though it's not presently implemented: https://github.com/microsoft/bedrock/issues/914

The lifecycle pipeline should be allowed to fail - it does operate on pull requests to the HLD, so even if it _does_ fail, it's not catastrophic. If the access.yaml information does not exist at the time of service creation - one can simply add it it by modifying the access.yaml in the HLD with the proper location of the helm chart.

**Comment by andrebriggs** [comment]
What I'm hearing that in lieu of automation from #914 the lifecycle pipeline will fail with our current workflow if someone wants to add private repo. 

I will keep this bug open to track the fact that manual intervention is needed until #914 solves this

**Comment by andrebriggs** [comment]
@bnookala @mtarng is this unblocked now?

**Comment by bnookala** [comment]
@andrebriggs yep - closing this out
