### ISSUE TITLE
SPK service create helm chart needs better documentation

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1026]
**As a:**
Developer
**I want:**
To understand the `spk service create` helm chart flags
**So that:**
I can stop thinking about how to configure `spk` and get on with my business problem 
**Describe the solution you'd like:**
Currently the help text says
```
-c, --helm-chart-chart <helm-chart>
bedrock helm chart name. --helm-chart-* and --helm-config-* are exclusive; you may only use one.
-r, --helm-chart-repository <helm-repository>
bedrock helm chart repository. --helm-chart-* and --helm-config-* are exclusive; you may only use one.
-b, --helm-config-branch <helm-branch>
bedrock custom helm chart configuration branch. --helm-chart-* and --helm-config-* are exclusive; you may only use one.
-p, --helm-config-path <helm-path>
bedrock custom helm chart configuration path. --helm-chart-* and --helm-config-* are exclusive; you may only use one.
-g, --helm-config-git <helm-git>
bedrock helm chart configuration git repository. --helm-chart-* and --helm-config-* are exclusive; you may only use one.
```

This is confusing. The [spk project guide](https://github.com/CatalystCode/spk/blob/master/guides/project-service-management-guide.md#adding-a-service-to-a-application-repository) doesn't mention how to use these flags  It would be great to see sample scenarios for how to use these __mutually exclusive__ flags. 

_**Consider**_
The following to indicate mutually exclusivity:
```{--helm-chart-chart chart-name --helm-chart-repository repo-url | --helm-config-branch branch --helm-config-path path --helm-config-git helm-git}```

Above there are two options:
Left side of pipe: Explain why and when you would use `--helm-chart-chart` and `--helm-chart-repository`
Right side of pipe: Explain why and when you would use `--helm-config-branch`, `--helm-config-path path` and `--helm-config-git`

**Acceptance Criteria:**

- Sample usage for external helm charts and internal (local to the application repo) helm chart scenarios in the [docs](https://catalystcode.github.io/spk/commands/index.html#service_create).
- Guidance in the [spk project guide](https://github.com/CatalystCode/spk/blob/master/guides/project-service-management-guide.md#adding-a-service-to-a-application-repository)  on how to use these flags
- Consider not having mutually exclusive flags. I still don't understand why `spk service create` has this complication. If absolutely necessary we should explain.

**Does this require updates to documentation?:**

yes

**Comment by bnookala** [comment]
@andrebriggs

> Consider not having mutually exclusive flags. I still don't understand why spk service create has this complication. If absolutely necessary we should explain.

Commander does not offer a way for us to provide mutually exclusive flags hence this complication.

**Comment by andrebriggs** [comment]
@bnookala adding back the enhancement tag due to requests in acceptance criteria that we don't currently have

> * Sample usage for external helm charts and internal (local to the application repo) helm chart scenarios in the docs.
> * Guidance in the spk project guide on how to use these flags

cc @mtarng
