### ISSUE TITLE
As an SRE: I would like to have a mechanism to rotate SSH keys in SPK infra

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#1027]
**As a:** SRE

**I want:** A mechanism to rotate SSH keys for flux.

**So that:** Keys can be versioned off.

**Describe the solution you'd like:** The basic implementation would be to create a new key, update flux, and update AZDO.

**Acceptance Criteria:** Showing that the key is rotated and flux can continue to update the cluster from the repository.

**Comment by andrebriggs** [comment]
Off the top of my head the pieces involved would be
- SPK has access to cluster to RBAC enabled cluster (maybe via kubeconfig)
- If there are multiple clusters then SPK would need to be scripted to access each cluster
- SPK needs PAT for AzDO (or some other Git repo host) 

My fear is that SPK messes with Flux and then Flux has some issue, then what? Does Flux wait until Flux logs indicates it can pull from the repo with the new credentials.

This is a valid concern and good idea but perhaps outside of the scope of SPK. I envision an SRE having a script to do the steps above and have some sort of validation before moving to additional clusters.

Are you tied to the idea of this being in SPK @jmspring?

I could imagine a would where `spk infra` functionality is in a separate application or is an `az cli` extension. In that case I could see out this in.

cc @yradsmikham @NathanielRose

**Comment by andrebriggs** [comment]
This might involve providing a script cc @jmspring
