### ISSUE TITLE
Azure Single Keyvault should support the creation of an additional subnet in an existing vent

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#1029]
**As a:** Operator

**I want:** To be able to provision a second cluster into an existing vnet by creating a new subnet (as opposed to a whole new vnet).

**So that:** I don't have to constantly create new VNets.

**Describe the solution you'd like:** If an existing subnet is specified, it should be used, if not a new one should be created.  This may also be an external step, which would require documentation.

**Comment by andrebriggs** [comment]
@jmspring how would this work with the `spk infra` model?

**Comment by jmspring** [comment]
`spk infra` would end up with a new argument in single keyvault (subnet address prefix).  It had actually been there previously due to a lack of clean up.  So common-infra deploys the vnet, single key vault (and related) create a subnet for the cluster.

**Comment by andrebriggs** [comment]
@jmspring do you have a size for this?

**Comment by jmspring** [comment]
Duplicate of #1110
