### ISSUE TITLE
SPK docs should strings as unquoted in docs, strings should be quoted

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#1031]
**Describe the bug:** In the docs for introducing spk infra, the example definition.yaml shows strings as unquoted.  This will cause errors.  The example should be updated.

https://github.com/microsoft/bedrock/blob/docs_spk/docs/infrastructure.md

**Comment by andrebriggs** [comment]
@yradsmikham @NathanielRose

**Comment by yradsmikham** [comment]
This should be a quick fix in the documentation.

**Comment by andrebriggs** [comment]
Is this work worth doing giving the upskilling documentations tasks. @yradsmikham @NathanielRose is there a task in this [milestone](https://github.com/microsoft/bedrock/milestone/31) that covers https://github.com/microsoft/bedrock/blob/docs_spk/docs/infrastructure.md ?

https://github.com/microsoft/bedrock/issues/1038 Look like it covers infra. Can we make sure that the same issue doesn't exist? 

cc @jred55

**Comment by yradsmikham** [comment]
@andrebriggs @NathanielRose @jmspring @jred55 

We can tack this onto #1038. I think it makes sense to close this issue, and add a comment to #1038 to ensure that the documentation resolves quotations for consistency.

**Comment by andrebriggs** [comment]
Closing,. Added a comment to #1038
