### ISSUE TITLE
terraform commands in spk_docs branch need updating

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#1032]
**Describe the bug:** The command lines given for terraform in infrastructure.md are incorrect.  `terraform init` should take `-backend-config=<path>`, etc.  Also single dash versus double dashes.

**Comment by andrebriggs** [comment]
@jmspring The spk_docs branch has been merged to master. Do you still see these issues? If so we should update the bug to reflect master branch now

**Comment by NathanielRose** [comment]
Detailed here: https://github.com/microsoft/bedrock/blob/master/docs/multicluster.md#deploying-cluster

**Comment by andrebriggs** [comment]
@NathanielRose @jmspring ok looks like this is still an issue

**Comment by jred55** [comment]
Assigned to myself. Will look into this

**Comment by yradsmikham** [comment]
What's the status of this issue? @jred55 @andrebriggs

**Comment by jred55** [comment]
Thanks for the ping @yradsmikham . Looking into it

**Comment by jred55** [comment]
PR - https://github.com/microsoft/bedrock/pull/1268
