### ISSUE TITLE
Guidance on rolling back with SPK Infra

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#1036]
**As a:**
SPK user

**I want:**
guidance on rolling back my AKS cluster operated by SPK Infra and GitOps

**So that:**
I can ensure that my cluster can revert back to a healthy state in the situation of a failed terraform deployment.

**Describe the solution you'd like:**
Documentation that includes examples of using Azure DevOps pipelines, or a script to perform spk infrastructure roll backs.

**Does this require updates to documentation?:**
Yes

**Comment by NathanielRose** [comment]
Initial Draft Proposal is located here: https://github.com/NathanielRose/design-Docs
