### ISSUE TITLE
I want a walkthrough of: Deploying Cluster Infrastructure (1 cluster) with Keyvault

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#1038]
**As a:**
Developer
**I want:**
Walkthrough showing how to deploy a single cluster with Keyvault using Infra automation
**So that:**
I can use this cluster for subsequent walkthroughs
**Describe the solution you'd like:**
The solution will build on the first Deploying your first workload using Bedrock and change the cluster to use AKS Cluster with Keyvault and Vnet. The instructions will use Common and Single Keyvault Bedrock templates.
**Acceptance Criteria:**

- [ ] Instructions on how to deploy common infra 

- [ ] Instructions on how to deploy Single Keyvault 

- [ ] Reuse the manifest repo from first walkthrough 

- [ ] Able to hit the App endpoint 

- [ ] Make sure any example yaml is quoted properly #1031 

**Describe alternatives you've considered:**
None
**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by edaena** [comment]
When I went through the workflow a few weeks ago, I wrote down the list of [required resources](https://github.com/edaena/ohbedrock/blob/master/challenges/1-0.md#get-required-resources), needed to onboard.
We could provide an optional script where we create the following resources for them:
- Service principal
- Storage Account
- Two resource groups
- Two ssh keys

**Comment by andrebriggs** [comment]
@jred55 it appears this is done. Please re-open if not
