### ISSUE TITLE
I want a walkthrough on setting up HLD to Manifest pipeline 

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#1041]
**As a:**
Bedrock user
**I want:**
a walkthrough on how to setup HLD to Manifest pipeline using Bedrock Cli
**So that:**
I can understand how to automatically generate manifests from an HLD using an Azure DevOps pipeline.
**Describe the solution you'd like:**

**Acceptance Criteria:**
- [x] Walkthrough explaining the HLD -> Manifest setup 

- [x] Walkthrough deploys Traefik2 (via spk hld init)

- [x] Changes to HLD trigger the pipeline and the changes are picked up in the cluster 

- [x] Verify that Traefik2 pods are running in cluster via kubectl

**Describe alternatives you've considered:**
None

**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by edaena** [comment]
At @jred55 this step "Changes to HLD trigger the pipeline and the changes are picked up in the cluster" refers to adding the azure-vote-app right?
