### ISSUE TITLE
I want a deep dive on Deployment Pipelines and Repos

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#1044]
**As a:**
Bedrock user
**I want:**
a Deep Dive on the structure of various Repos (Three repos) and the need to automate the setup for the pipelines 
**So that:**
I understand the Services Automation in Bedrock
**Describe the solution you'd like:**
Document explaining the repo structure and pipelines 
**Acceptance Criteria:**

- [ ] Deep dive document is uploaded to Bedrock main repo 
- [ ] Document should explain the concept of three repos - App Repo, HLD repo and Manifest repo
- [ ] Document should have a diagram explaining the names of repos and names of pipelines and links to corresponding walkthroughs

**Describe alternatives you've considered:**
None
**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by timfpark** [comment]
@jred55 I'm going to mark this "in review" pending your review of https://github.com/microsoft/bedrock/blob/docs_spk/docs/gitops-pipeline.md.   Let me know if you think we have more work to do on this issue.
