### ISSUE TITLE
spk should allow a project to use an existing variable group

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#1046]
**As a:**
spk user
**I want:**
to be able to reference an existing variable group
**So that:**
multiple application repositories can share a single variable group in an AzDo project
**Describe the solution you'd like:**
`spk project add-variable-group <variable-group-name>` command that is similar to `spk project create-variable-group <variable-group-name>`, but instead of creating a variable group, it may check for the existence of the variable group in azdo, then it adds the reference to the project's `bedrock.yaml` _AND_ it adds the variable group for all linked service build pipelines.

**Acceptance Criteria:**

**Describe alternatives you've considered:**
We could overload `spk project add-variable-group <variable-group-name>` and check the variable group exists already. If it does, log a warning then skip creating the VG in azdo, but continue to add it to `bedrock.yaml` and the related pipelines.

**Additional context:**

**Does this require updates to documentation?:**
yes

**Comment by andrebriggs** [comment]
@mtarng I assume we would have additional flags on `spk project add-variable-group <variable-group-name>` to accept the AzDO org, project, and PAT, right?

**Comment by mtarng** [comment]
Correct. It should be nearly the identical as `spk project create-variable-group <variable-group-name>`. So same flags or it can use config. There is an alternative to just use `spk project create-variable-group <variable-group-name>` and skip adding the variable group if it already exists in azdo.

**Comment by andrebriggs** [comment]
@mtarng  Also the result should be an additional variable group in the `bedrock.yaml` file, right? See `MY_FIRST_VG` and ` MY_SECOND_VG`

```
    ...
    k8sBackendPort: 80
    middlewares: []
    pathPrefix: cart-service
    pathPrefixMajorVersion: v1
variableGroups:
  - MY_FIRST_VG
  - MY_SECOND_VG
# trigger bedrock flow from here
```

Any resulting services (even if mono-repo) will have these two variable groups in their `build-update-hld.yaml`, right?

**Comment by mtarng** [comment]
Yes, that looks correct @andrebriggs

**Comment by edaena** [comment]
Sounds similar to `spk hld append-variable-group: Appends the name of an existing variable group to the current manifest-generation.yaml file.`

**Comment by mtarng** [comment]
Yup. I think the big decision is mostly UX. Do we think we should create a new command that does nearly the same thing as `spk project create-variable-group`? My hunch is to say yes, while it's similar, the `create-variable-group` will explicitly try to create a new variable-group in azdo, if it fails to do so or if one already exists, it will throw and error.

With a new command `spk project append-variable-group` or however we name it, it will assume that variable group exists and verify the existence on azdo, and simply add references to that variable group in bedrock.yaml and any associated service build pipelines. Optionally, but suggested, we should also verify that the required variables exist inside the variable group.
