### ISSUE TITLE
Public IP is not verified in the traffic manager during Bedrock integration test

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#1051]
**Describe the bug:**
Receiving an error validating the traffic manager

**To Reproduce:**
Run the Integration test for Bedrock multi-cluster

**Expected behavior:**
Success on getting 400 for the voting app behind allocated IP 

**Screenshots:**
```
TestIT_Bedrock_AzureMC_Test 2020-02-24T21:08:35Z http_helper.go:30: Making an HTTP GET call to URL http://iorppgtmdns.trafficmanager.net
TestIT_Bedrock_AzureMC_Test 2020-02-24T21:08:35Z retry.go:84: HTTP GET to URL http://iorppgtmdns.trafficmanager.net returned an error: Get 
Error validating Traffic Manager - Removing cluster load balancer and Destroying resources
```

**Additional context:**
https://dev.azure.com/epicstuff/bedrock/_build/results?buildId=12558&view=logs&j=f3b2aaba-0964-5a71-b126-04f464bcedd6&t=ed3d359a-0c2b-5797-0784-0814e71568e6

**Does this require updates to documentation?:**
No

**Comment by andrebriggs** [comment]
@NathanielRose Is there a proposal to fix this?

**Comment by NathanielRose** [comment]
Proposed Fix: I can increase the retry amount for the traffic manager go script, I can add a full test retry for the entire job, I can re-evaluate the terratest for the multi-cluster environment, I can also look into the decoupling of terraform commands from terratest in order to skip terraform destroy failures since that may be more of an Azure issue. 

Currently Exploring alternatives way to verify Traffic Manager or remove the verification temporarily

**Comment by NathanielRose** [comment]
Update: In progress, having difficulties reproducing in my own AzDO pipeline and running locally. Experiencing different errors from the traffic manager. Can also disable the test until we have a fix for Multicluster @andrebriggs
