### ISSUE TITLE
Bedrock scheduled integration tests are running against PRs

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#1052]
**Describe the bug:**
Microsoft.Bedrock.scheduled are executing against PRs

**To Reproduce:**
Re-enable Microsoft.Bedrock.scheduled pipeline and open a PR

**Expected behavior:**
The pipeline runs on CRON job schedule (Friday at Noon)

**Screenshots:**
https://dev.azure.com/epicstuff/bedrock/_build?definitionId=1046&_a=summary

**Additional context:**
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers

**Does this require updates to documentation?:**
No

**Comment by andrebriggs** [comment]
@NathanielRose do you have a proposed fix? I believe we talked about having a separate pipeline for scheduled tests

**Comment by NathanielRose** [comment]
> @NathanielRose do you have a proposed fix? I believe we talked about having a separate pipeline for scheduled tests

There is a separate pipeline for the scheduled test located [here](https://github.com/microsoft/bedrock/blob/master/pipelines/bedrock-scheduled.yml). Though its including running against PRs in master

We have an identical issue with smoke tests running against PRs when it should only be scheduled daily - see slack thread [here](https://epicstuff.slack.com/archives/CMZLC09MF/p1582128686369200)
