### ISSUE TITLE
Error on install-manifest-pipeline, HLD repo or manifest url not defined

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#1055]
**Describe the bug:**
`spk hld install-manifest-pipeline` throws error even when the HLD repo url and manifest url are defined in `spk-config.yaml`

**To Reproduce:**
- Populate the `azure_devops` section of the `spk-config.yaml`.
- Run `spk init -f spk-config.yaml`
- Run `spk hld install-manifest-pipeline`

**Expected behavior:**
It installs the pipeline.

Seen:
```
error:   Error occurred installing pipeline for HLD to Manifest pipeline
error:   HLD repo url or manifest url not defined.
```

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by bnookala** [comment]
From the PR we merged yesterday: https://github.com/CatalystCode/spk/pull/309/files#diff-2c50a43e035c24c31dfa7cc9ce2abc40R47

Seems like the code does a check against passed in flags, failing if they don't exist and then ORs the passed in flags against the url embedded in config - I think the logic _should_ be the other way around - @yradsmikham - would you be able to pick this up?
