### ISSUE TITLE
We don't have an automated way to validate that "spk service build" command sets image repository and flows to manifest repository 

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1057]
**Describe the bug:**
The PR #1015 has no validation in our integration tests
 
**To Reproduce:**
Look in master branch

**Expected behavior:**
When feature is added we have not only a unit test layer of validation but an integration test layer of validation.

Specifically it sounds like the integration tests should be extended/modified to validate the E2E workflow can support passing through the image repository through SPK. Current we hardcode the image repository from the Helm chart values.yaml file.

**Comment by yradsmikham** [comment]
Pending https://github.com/CatalystCode/spk/pull/370 merge and new spk release.

**Comment by andrebriggs** [comment]
@yradsmikham a new release was pushed.
