### ISSUE TITLE
SPK hld_update shouldn't end up with confict on HLD repo

### ISSUE THREAD

**Issue by luongbac301092** [microsoft/bedrock#1060]
**Topic:**
SPK hld_update
**Question:**
I'm working on a repo which have two services.
if i trigger both service pipelines at the same time, there are two open pull request on HLD, both of them are updating the "common.yaml" file under "config" folder at hld root repository which end up with conflict.
Is this expected behavior?

**Comment by bnookala** [comment]
@luongbac301092 this is an issue as they're both attempting to update the same file - and there's no automated rebase _after_ one of the PRs is merged

Since there's multiple places where configuration can be set in the tree, it's possible that we can fix this - will investigate

**Comment by bnookala** [comment]
Created https://github.com/microsoft/bedrock/issues/1100 to track issue moving this question to blocked

**Comment by bnookala** [comment]
@luongbac301092 we fixed this issue via https://github.com/CatalystCode/spk/pull/378. this will remain an issue pending a new release of `spk`, for now.

**Comment by mtarng** [comment]
@luongbac301092 the latest release of spk should contain a fix for this now. Please do note, any config closer to the root of the repository _may_ overwrite any configs set higher up in the tree/nodes. To fix this, remove any `image.tag` and `image.repository` or other configurations set  in the hld's `/config/common.yaml` that may conflict.

tagging @bnookala @evanlouie for sanity check.

Please let us know if this addresses your issue @luongbac301092

**Comment by mtarng** [comment]
Closing this issue for now, feel free to reopen if needed @luongbac301092
