### ISSUE TITLE
spk should allow for replacement of the traefik deployment with something custom

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#1061]
**As a:** SRE, I might need to replace the traffic HLD deployed by SPK with a custom drop in.  

**I want:** Currently, if I want to replace the traefik2 deployment with something custom, I must manually edit the files in the repository for the HLD pipeline.

SPK should allow for specifying a custom component.

**Comment by mtarng** [comment]
This is already supported via `spk hld init`

Usage: hld init|i [options]

Initialize High Level Definition repository. Add manifest-generation.yaml file to working directory/repository if it does not already exist.
```
Options:
  --default-component-git <component-repository-url>  The default hld repository's component's git repository url. (default: "https://github.com/microsoft/fabrikate-definitions.git")
  --default-component-name <component-name>           The default hld repository's component's name. (default: "traefik2")
  --default-component-path <component-path>           The default hld repository's component's path. (default: "definitions/traefik2")```
