### ISSUE TITLE
Logs from infra-generation-pipeline.yml show up in SPK rings integration tests

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1064]
**Describe the bug:**

The text `Adding generated components for ` is showing up in the log of the rings validations test 3 times. This string comes from the `infra-generation-pipeline.yml` file [here](https://github.com/CatalystCode/spk/blob/2c496393ff94049894130127957e7a36c83357eb/azure-pipelines/templates/infra-generation-pipeline.yml#L109)

![image](https://user-images.githubusercontent.com/3119513/75472038-ca4fd100-5947-11ea-8603-e62ceb0d810c.png)

An example in the test log is [here](https://dev.azure.com/epicstuff/bedrock/_build/results?buildId=12854&view=logs&j=8fe65ec1-57b5-590c-8e73-b2e70046a92a&t=5273a394-895a-588d-3853-b9fce385fa20&l=199).

**To Reproduce:**

Run the rings integration tests.
**Expected behavior:**

We shouldn't have the `infra-generation-pipeline.yml` running and producing logs in a test that doesn't execute it

**Comment by yradsmikham** [comment]
I've gone ahead and tried to reproduce this in my own Azure DevOps environment, and was unable to reproduce the same behavior: https://dev.azure.com/yvradsmi/spk-services/_build/results?buildId=1541&view=results. 

I'm starting to think this is probably something not within our scripts, but rather something funky in Azure DevOps.

**Comment by yradsmikham** [comment]
Although, I am noticing the one specific infra log in the rings tests:
<img width="1677" alt="Screen Shot 2020-02-27 at 1 07 14 PM" src="https://user-images.githubusercontent.com/16811248/75486842-24f62680-5962-11ea-92bb-555b335f9010.png">
