### ISSUE TITLE
Propose new structure for Bedrock repo

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1073]
Propose a new structure for what the Bedrock repo will like like before and after if we move the SPK tool inside the repo.

**Comment by sarath-p** [comment]
@andrebriggs - with below doc, can we move this to done column?

https://microsoft.sharepoint.com/:w:/t/Bedrock223/EZrdNrfX9AtMk_MkAqonHfABhGl3gS3wf5J9aZinu290Zg?e=8E2UVe

**Comment by andrebriggs** [comment]
@sarath-p yep. Thanks
