### ISSUE TITLE
break createPullRequest function in lib/git/azure.ts into smaller and testable parts

### ISSUE THREAD

**Issue by dennisseah** [microsoft/bedrock#1078]
**As a:**
Developer

**I want:**
I have to have smaller and testable functions

**So that:**
code can be tested and reduce software defects

**Describe the solution you'd like:**
break big function https://github.com/CatalystCode/spk/blob/master/src/lib/git/azure.ts#L108 into small parts and add tests

**Acceptance Criteria:**
functions are less than 30 lines and code coverage is over 90%

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
no

**Comment by bnookala** [comment]
@dennisseah this belongs in sprint 12
