### ISSUE TITLE
Spk infra scaffold git retries failing for unknown reason

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#1079]
**Describe the bug:**
`spk infra scaffold` will fail and error out occasionally when attempting to `git clone` or `git pull` the source repo.

**To Reproduce:**
Execute `spk infra scaffold`.

**Expected behavior:**
To be able to clone or pull source repo, if not, throw a meaningful error message.

**Screenshots:**
<img width="420" alt="Screen Shot 2020-03-02 at 10 49 24 AM" src="https://user-images.githubusercontent.com/16811248/75707282-80325c80-5c73-11ea-9030-d4c0c5783991.png">

**Does this require updates to documentation?:**
No

**Comment by NathanielRose** [comment]
@yradsmikham  can you also share your .spk/templates directory? Try also deleting the templates and running the command again. This could be an issue with caching.

**Comment by yradsmikham** [comment]
@NathanielRose 
<img width="387" alt="Screen Shot 2020-03-02 at 12 35 25 PM" src="https://user-images.githubusercontent.com/16811248/75715475-4fa5ef00-5c82-11ea-9623-79eb5b798229.png">

Yes, I've gone ahead and deleted the template, and retried. But why is this happening?

**Comment by NathanielRose** [comment]
@yradsmikham Unsure, what steps are you taking so I can reproduce on my machine.

**Comment by yradsmikham** [comment]
@NathanielRose I am simply running `spk infra scaffold`. I believe after a certain point it will hit a wall. It's definitely a flaky approach, but from my experience, it happens every so often without a known root cause. And at this point, it has happened a handful of times already.

**Comment by NathanielRose** [comment]
@yradsmikham  Can you share a log file of the bug. I attempted to reproduce and having no luck on my machine.
[spk-infra.log](https://github.com/microsoft/bedrock/files/4282791/spk-infra.log)

**Comment by yradsmikham** [comment]
The only logs that I have are:

```
 ~/microsoft/spk   master  spk infra scaffold --name ydawgie-azure-simple-test --source https://github.com/microsoft/bedrock  --version master --template cluster/environments/azure-simple
error:   Env variable needs to be defined for test_name
warn:    Error loading SPK configuration file; run `spk init` to initialize your global configuration or ensure you have passed all required parameters to the called function.
warn:    The infrastructure repository containing the remote terraform template repo and access token was not specified. Checking passed arguments.
info:    All required options are configured via command line for scaffolding, expecting public remote repository for terraform templates or PAT embedded in source URL.
info:    Converted to: _microsoft_bedrock
info:    Checking if source: /Users/yvonneradsmikham/.spk/templates/_microsoft_bedrock is stored locally.
info:    Source template folder found. Validating existence of repository.
info:    Remote source repo: https://github.com/microsoft/bedrock exists.
info:    Checking if source repo: https://github.com/microsoft/bedrock has been already cloned to: /Users/yvonneradsmikham/.spk/templates/_microsoft_bedrock.
From https://github.com/microsoft/bedrock
 * branch            master     -> FETCH_HEAD

warn:    FAILURE DETECTED: Checking the error
error:   Error occurred while generating scaffold
error:   Failure error thrown during retry Error: Unable to determine error from supported retry cases From https://github.com/microsoft/bedrock
 * branch            master     -> FETCH_HEAD
```

This occurs intermittently. The problem is, the logs does not include meaningful error messages as to what is causing the issue.

**Comment by edaena** [comment]
No repro
