### ISSUE TITLE
SPK bedrock.yaml file should be versioned

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1082]
**As a:**
Developer
**I want:**
The `bedrock.yaml` file should container the version of `spk` that created/or modified it

**So that:**
the `spk` tool can use this metadata for features such as backwards compatibility and debugging 

**Describe the solution you'd like:**
The `bedrock.yaml` file containers a key value pair for spk version number or build number.

Example
<pre>
rings:
  master:
    isDefault: true
services:
  ./:
    displayName: quick-start-app
    helm:
      chart:
        accessTokenVariable: ACCESS_TOKEN_SECRET
        branch: master
        git: 'https://dev.azure.com/abrig/BedrockRocks/_git/quick-start-helm'
        path: quick-start-app/chart
    k8sBackend: quick-start-app-svc
    k8sBackendPort: 80
    middlewares: []
    pathPrefix: ''
    pathPrefixMajorVersion: ''
variableGroups:
  - quick-start-vg
<b>#THIS IS AN AUTOGENERATED VALUE.
version: 0.5.7 </b>
</pre>
 
**Acceptance Criteria:**
I can see what version of `spk` modified or created the `bedrock.yaml` file

**Does this require updates to documentation?:**
No

**Comment by sarath-p** [comment]
@andrebriggs - do we need `version` attribute in the file or comment that includes the version number? I think adding a `version` attribute in the schema touches many places.
