### ISSUE TITLE
Fallback/Default routing for rings

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#1084]
**As a:** operator

**I want:** requests made to a service made through the Traefik2 ingress to have a fallback/default ring to route to when my request does not have `Ring` header.

**So that:**

- The on-boarding for a _ring-less_ spk project is easier and the concept of rings can be adopted when needed.
- In the case of a mono-repository with multiple services and rings, it is possible for a a ringed-service to call another ringed-serviced. But in the scenario that this ring is a one-off bug fix ring, chances are the other service has not been deployed to that ring. In that scenario, the request should be routed to a sane default (e.g `master).

**Describe the solution you'd like:**

- Only allow one entry in `rings` in `bedrock.yaml` to be marked as `isDefault: true`.
- During IngressRoute creation time, use that `isDefault: true` property as a trigger to scaffold an additional IngressRoute -- one without the header requirement.

**Acceptance Criteria:**
- [ ] Documentation in SPK guides describing this behavior 
- [x] Add to the `spk hld reconcile` functionality to create an additional IngressRoute if the a ring is flagged as `isDefault: true` -- the Ingress route should be identical to the other one except without the `Ring` header match rule.
- [x] Add a validation in IngressRoute creation time that only one ring can be flagged as `isDefault: true`.

**Describe alternatives you've considered:**

**Additional context:**

This would impact the create-revision flow as it currently allow users to make PRs against the multiple rings defined with isDefault: true. However, this functionality has seen little real world use, so co-opting it might be best.

**Does this require updates to documentation?:** Potentially -- if the rings documentation is merged by the time this done.

**Comment by mtarng** [comment]
Once the ring management epic is completed: https://github.com/microsoft/bedrock/issues/955, this implementing logic may need to check which ring the default "ringless" IngressRoute points to after the default is changed.

**Comment by andrebriggs** [comment]
@mtarng @evanlouie size?

**Comment by mtarng** [comment]
I'm thinking S or M @evanlouie ?

**Comment by evanlouie** [comment]
M

**Comment by bnookala** [comment]
@evanlouie a detail that we need to consider is the "isDefault" attribute being used for both service revisions _and_ for routing 

consider a situation in which the `dev` or `master` branch is the `isDefault` ring - in this case you _may_ end up routing production traffic (ie traffic routed to your endpoint _without_ the ring header) to your `dev` or `master` branches…

**Comment by evanlouie** [comment]
Agreed. Might need to re-word the `isDefault` property then because it might get conflated with the tbd property name for default routing

**Comment by mtarng** [comment]
Could we change `isDefault` to select the ring for default routing, and change `spk service create-revision` to pass in a branch everytime?

@evanlouie @bnookala

**Comment by andrebriggs** [comment]
> Add a validation in IngressRoute creation time that only one ring can be flagged as isDefault: true.

@evanlouie Do we have runtime validation for this already?

**Comment by evanlouie** [comment]
@andrebriggs not currently. When a user runs `spk ring set-default <some-ring>`, it will set `isDefault` to false for all the others. But we do not have a run-time validation for when a user manually edits the bedrock.yaml
