### ISSUE TITLE
azure-multiple-clusters-waf-tm-apimgmt fails in terraform init

### ISSUE THREAD

**Issue by jasonhornatcrowe** [microsoft/bedrock#1087]
**Describe the bug:**
Unable to create terraform modules using the **azure-multiple-clusters-waf-tm-apimgmt** environment template.  Uncovers a defect with the main.tf configuration for waf found in:
- cluster/azure/waf/main.tf line 45 
`name = var.prefix}-beappool1" `

**To Reproduce:**
From bedrock repo home 
* master @ commit [9162c54](https://github.com/microsoft/bedrock/commit/9162c54236219c205f5634acada9eb4df44c7ca0)

1. cd cluster/environments/azure-multiple-clusters-waf-tm-apimgmt
2. cp ../azure-multiple-clusters/terraform.tfvars ./
3. vi terraform.tfvars (see attached variables file)
4. terraform init 2>&1 | tee tfinit (see attached tfinit)

**Expected behavior:**
terraform init creates modules without error

**Screenshots:**

**Additional context:**
- terraform.tfvars file attached ([terraform.tfvars.txt](https://github.com/microsoft/bedrock/files/4284048/terraform.tfvars.txt))
  - NOTE: updates required for 
    - service_principal_id 
    - service_principal_secret
    - ssh_public_key 
    - gitops_ssh_url 
    - gitops_ssh_key 
- tfinit output file attached ([tfinit_multiple_clusters.txt](https://github.com/microsoft/bedrock/files/4284069/tfinit_multiple_clusters.txt))

**Does this require updates to documentation?:**
No

**Attachments**
- [terraform.tfvars.txt](https://github.com/microsoft/bedrock/files/4284048/terraform.tfvars.txt)
- [tfinit_multiple_clusters.txt](https://github.com/microsoft/bedrock/files/4284069/tfinit_multiple_clusters.txt)

**Comment by NathanielRose** [comment]
@jasonhornatcrowe, I provided a quick fix based on your ticket but the `azure-multiple-clusters-waf-tm-apimgmt` has not been updated to our latest format for Bedrock templates. This includes resource groups managed through data resources and migrating the API Management module to a tf module instead of an ARM deploy module.
