### ISSUE TITLE
Bedrock Repairs to terraform Integration Tests

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#1089]
**Describe the bug:**
Failing tests are being experienced within the bedrock integration test harness
**To Reproduce:**
- [ ] Azure login in Bedrock.scheduled
- [ ] Scheduled tests being triggered upon PRs
- [ ] Whitelisting is no longer triggering the respective tests

**Expected behavior:**

Success on all integration tests

**Screenshots:**

```
FAIL	github.com/microsoft/bedrock/test	13.943s
```
```
Error: Error deleting Public IP "gtestk8s-pidcv0-ip" (Resource Group "gtestk8s-pidcv0-central-rg"): network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/***/resourceGroups/gtestk8s-pidcv0-central-rg/providers/Microsoft.Network/publicIPAddresses/gtestk8s-pidcv0-ip can not be deleted since it is still allocated to resource /subscriptions/***/resourceGroups/mc_gtestk8s-pidcv0-central-rg_gtestk8s-pidcv0_centralus_centralus/providers/Microsoft.Network/loadBalancers/kubernetes/frontendIPConfigurations/a571c287f40874760942b2576a1a4e55. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." Details=[]
```

**Additional context:**
https://dev.azure.com/epicstuff/bedrock/_build/results?buildId=13245&view=logs&j=f3b2aaba-0964-5a71-b126-04f464bcedd6&t=ed3d359a-0c2b-5797-0784-0814e71568e6

**Does this require updates to documentation?:**
No

**Comment by andrebriggs** [comment]
@NathanielRose closing since this is intermittent. Let's open a new bug when we have something concrete
