### ISSUE TITLE
spk hld reconcile not generates correct ingress-route for rings

### ISSUE THREAD

**Issue by luongbac301092** [microsoft/bedrock#1093]
**Describe the bug:**
Presently HLD reconcile generates service name in IngressRoute the same for every ring
**To Reproduce:**
1. add two rings master and develop.
2. generate an HLD with hld reconcile.

**Expected behavior:**
HLD reconcile should generate 2 ingress routes :
serviceName-master : this should forwarding the request to the service : serviceName-master
serviceName-develop : this should forwarding the request to the service : serviceName-develop

**Does this require updates to documentation?:**
No

**Comment by bnookala** [comment]
Hey @luongbac301092 thanks for the bug - this is currently blocked pending a new release of `spk` - it was fixed in this Pull Request: https://github.com/CatalystCode/spk/pull/289

**Comment by bnookala** [comment]
@luongbac301092 `spk` 0.5.5 was released yesterday https://github.com/CatalystCode/spk/releases/tag/v0.5.5 - this should resolve your issue.
