### ISSUE TITLE
Keyvault FlexVolume deploying version 0.0.9

### ISSUE THREAD

**Issue by ReisHEPi** [microsoft/bedrock#1094]
**Describe the bug:**
Bedrock is deploying a _much_ outdated version of the keyvault flexvolume by default:

https://github.com/microsoft/bedrock/blob/0d3a235b7f7d2f7ae0e87993ad9053e91a22728f/cluster/azure/keyvault_flexvol/variables.tf#L38

**Expected behavior:**
Keyvault flexvolume to be pointing to master branch:

https://github.com/Azure/kubernetes-keyvault-flexvol/blob/master/deployment/kv-flexvol-installer.yaml

Is there any reason why we are not following master branch?

**Additional context:**
Why this matters:
https://github.com/Azure/kubernetes-keyvault-flexvol#option-1-service-principal
Some specific functionality is only available in version 0.0.14 or above (e.g. not needing to specify the subID or resourcegroup)

**Comment by jmspring** [comment]
Fixed in PR 1097
