### ISSUE TITLE
Bedrock should support Helm3 

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#1102]
**As a:**
Developer
**I want:**
Bedrock to support Helm 3
**So that:**
I can use latest major release of Helm in my setup
**Describe the solution you'd like:**
Currently Bedrock supports Helm 2.16.1. 
**Acceptance Criteria:**
Bedrock templates will work with Helm 3
**Describe alternatives you've considered:**
None
**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by jmspring** [comment]
This should only go hand in hand with updating how Fabrikate deals with Helm or figure another way to decouple dependence on helm locally.

**Comment by jsturtevant** [comment]
Might need to re-open this issue.  Helm2 is still required otherwise you end up with error message: `Error: Error running command 'echo 'Need to use this var so terraform waits for kubeconfig` see #894

**Comment by jsturtevant** [comment]
It appears to have been other configuration that was generated was not correct and presented the same error message. It does not appear helm3 is needed and I was able to get the cluster created.
