### ISSUE TITLE
As an SRE - I would like to be able to deploy a second cluster instance to a shared vnet/keyvault

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#1110]
**As a:** SRE, I want to be able to deploy a second Azure single key vault instance into an existing VNET and share the existing Keyvault.

**Describe the solution you'd like:** Currently, the Vnet and Subnet are created within Azure Common Infra.  The subnet is cluster specific (not shared between clusters) so it should likely be moved down to the cluster creation level.

**Acceptance Criteria:**. I can deploy multiple clusters into the same Vnet.

**Describe alternatives you've considered:**. Manually create a subnet in the existing vnet.

**Does this require updates to documentation?:**. Yes.

**Comment by andrebriggs** [comment]
@jmspring do you have some steps in mind for this? Especially using `spk`. If so please list

**Comment by jmspring** [comment]
The templates are changing. It will primarily impact azure common infra. Subnet prefix and subnet name will move from common infra to single keyvault.  The impact on spk?  Where the values need to be updated in the definition.yaml

**Comment by jmspring** [comment]
Fixed in PR #1255
