### ISSUE TITLE
Update `service create` parameters and update bedrock.yaml schema

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#1117]
This is the first task for refactoring how we handle service references in
bedrock.yaml

**I want:** `spk service create` and `bedrock.yaml` to be reworked to index
based on a serviceName

**So that:**

There is less confusion about a service's name vs a service's path

**Describe the solution you'd like:**

- Rewrite `spk service create` to accept to positional arguments
  `spk service create <svc-name> <path-to-svc>`
- Change the schema for `bedrock.yaml` services to index on name and have a
  mandatory `path` parameter.
- Automatically migrate the old bedrock.yaml services schema to the new one
  whenever the an `spk service` command is run
  - Use the new required parameter `path` in the service definition as the
    differentiator to detect when the service is the old schema or the new
    schema.

**Acceptance Criteria:**

Refer to above section.

**Additional context:**

Parent epic: https://github.com/microsoft/bedrock/issues/943

**Does this require updates to documentation?:**

Yes -- update the docs to reflect the new `spk service create` command arguments

**Comment by andrebriggs** [comment]
@evanlouie @mtarng size?

**Comment by mtarng** [comment]
@evanlouie M or L?

**Comment by evanlouie** [comment]
M
