### ISSUE TITLE
Bedrock CLI configuration and onboarding should be in one place

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1127]
**Problem**: We ask people to copy and paste a config file.
- [x] `spk init` should have an interactive mode to help people _build_ their configuration file #987
  - If you already have a config file great. spk config will load that in. 
  - If you have a partial config file or no config file spk config will take care of that for you too.

**Problem**: It is confusing our to set up configuration for `spk deployment onboard`.

- [x] `spk init` should have an interactive mode to configure and create any `spk deployment` resources such as:
  - Resource Group
  - Service Principal Info
  - Storage Account
  - Table Name
  - Partition Key

Originally was part of #986

**Comment by dennisseah** [comment]
@andre, can you update this epic with more tasks? or we can done with this. thanks

**Comment by dennisseah** [comment]
Please open this epic if there are still more tasks thanks
