### ISSUE TITLE
Bedrock pre-req page needs updating

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#1131]
**As a:**
Developer
**I want:**
Updated pre-reqs page in the docs_spk branch (eventually be merged to master)
**So that:**
I have correct pre-reqs or scripts that exist at this location 
https://github.com/microsoft/bedrock/blob/docs_spk/tools/prereqs/README.md
**Describe the solution you'd like:**
Update the pre-req page
**Acceptance Criteria:**
Pre-req page can be used to install correct pre-reqs
**Describe alternatives you've considered:**
None
**Additional context:**
None
**Does this require updates to documentation?:**
Yes

**Comment by timfpark** [comment]
We believe these prereq scripts still work - please reopen if there is a specific issue we've discovered.
