### ISSUE TITLE
Migrate day 2 infra content to infrastructure deep dive documentation item

### ISSUE THREAD

**Issue by timfpark** [microsoft/bedrock#1133]
As an SRE I want documentation on day 2 scenarios around infrastructure like managing multiple clusters, version locking, and upgrading templates.

Tangibly, this task involves migrating the existing infrastructure "walkthrough" to be more of a deep dive into infrastructure.

**Comment by yradsmikham** [comment]
@timfpark, @NathanielRose and I are happy to sync with you on this to solidify the approaches we've discussed before.

**Comment by timfpark** [comment]
@yradsmikham would love your comments on the existing content and/or additions later in another PR.
