### ISSUE TITLE
lifecycle pipeline will "fail" (error) if commits happen on a single app repo where service is in root 

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#1134]
**Describe the bug:**

if i am in a single app repo with the service at the root of the repo and the bedrock.yaml file is _not_ updated on a commit, the lifecycle pipeline will successfully run to completion, but fail with an error from git:

```
Switched to a new branch 'RECONCILE/location-service-20200309.3'
spk hld reconcile location-service /home/vsts/high-level-definition ./..
<.. snip ..> 
time="09-03-2020 20:46:08" level=info msg="💾  Loading component.yaml"
time="09-03-2020 20:46:08" level=info msg="💾  Writing 'component.yaml'"
info:    Running: cd /home/vsts/high-level-definition/location-service/location-service/master && fab set --subcomponent "chart" serviceName="location-service-master"
time="09-03-2020 20:46:08" level=info msg="💾  Loading config/common.yaml"
info:    Skipping ingress route generation for service location-service
GIT STATUS
On branch RECONCILE/location-service-20200309.3
nothing to commit, working tree clean
GIT ADD (git add -A)
GIT COMMIT
On branch RECONCILE/location-service-20200309.3
nothing to commit, working tree clean
##[error]Bash exited with code '1'.
Finishing: Download Fabrikate and SPK, Update HLD, Push changes, Open PR
```

**To Reproduce:**

- in a newly instantiated project, create a service at the root of the repository (just one), and install all pipelines
- merge initial HLD changes
- commit to application repository as normal
- observe that lifecycle pipeline runs, but fails 

**Expected behavior:**

- lifecycle pipeline should run to completion, and _not_ error.

**Additional context:**

- we can add logic in the pipeline to only commit and PR if there are changes - if there are no changes, the pipeline should exit cleanly. 

**Does this require updates to documentation?:**

no

**Comment by mtarng** [comment]
Create a git function in `build.sh` for all pipelines to use?

Can take arguments for:
- path to add?
- commit message
- option to: exit with error if there's nothing to commit, otherwise just exit

**Comment by mtarng** [comment]
Development blocked by https://github.com/microsoft/bedrock/issues/1171
