### ISSUE TITLE
Spektate dashboard refreshing bug

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1156]
The Spektate dashboard is exhibiting a behavior where pressing the back button doesn't go back to the previous page because presumably  the way the page is refreshing is loaded a new resource

<img width="978" alt="image" src="https://user-images.githubusercontent.com/3119513/76464795-1583ce00-63a3-11ea-8fe5-0368aee16860.png">

**Comment by samiyaakhtar** [comment]
This may be caused due to the new backend model where we call `/api/deployments` endpoint every time to refresh the results.
