### ISSUE TITLE
Remove setup of custom helm chart repository 

### ISSUE THREAD

**Issue by andrebriggs** [Microsoft/bedrock#116]
Remove the `helm init` method in [build.sh](https://github.com/Microsoft/bedrock/blob/master/gitops/azure-devops/build.sh) file once https://github.com/Microsoft/fabrikate/issues/64 is implemented

**Comment by andrebriggs** [comment]
Marking this as impeded since we are waiting on the new release of Fabrikate that includes https://github.com/Microsoft/fabrikate/pull/67

**Comment by andrebriggs** [comment]
A new [release](https://github.com/Microsoft/fabrikate/releases/tag/0.2.3) of Fabrikate is available 

@yradsmikham @samiyaakhtar

**Comment by yradsmikham** [comment]
Blocked. The issue has appeared to be resolved when using Fabrikate 0.2.3. However, adding a helm repo will require that the command `helm init` is executed prior. The newest version of Fabrikate does not perform this check before attempting to run `helm add repo ...`. Workarounds would include to make changes to the Fabrikate source code to ensure that helm is installed properly before attempting to add repos, or include the helm_init function in the build.sh.

**Comment by yradsmikham** [comment]
https://github.com/Microsoft/fabrikate/issues/76

**Comment by yradsmikham** [comment]
Submitted a PR to @bnookala repo for [fabrikate-jaeger](https://github.com/bnookala/fabrikate-jaeger/pull/2).
