### ISSUE TITLE
Introspection dashboard should capture correct ring name

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#1164]
**As a:** developer

**I want:** to to view the ring name from bedrock.yaml

**So that:** I can introspect my services

**Describe the solution you'd like:**
Currently, it's a bit confusing when the branch name is `x` and environment name `deploy/something-x` because it does not clarify which one is ring and whether the branch name was a branch in source repo or HLD repo. Could do some thinking around this. 

<img width="751" alt="Screen Shot 2020-03-12 at 2 36 32 PM" src="https://user-images.githubusercontent.com/1795990/76556055-3580c380-646f-11ea-803d-7087d3f9c482.png">

~~-  Ring name should be derived from bedrock.yaml during the source build pipeline process~~
- [x] Ring name should come from source branch name

**Acceptance Criteria:**
Column data makes more sense

**Describe alternatives you've considered:**
So far we've considered branch name to belong to source repo and environment name to belong to HLD, but there's no correct ring name. 

**Additional context:**

**Does this require updates to documentation?:** No

**Comment by andrebriggs** [comment]
In the case below the ring is `develop`. That is what exists in the `bedrock.yaml`

> <img alt="Screen Shot 2020-03-12 at 2 36 32 PM" width="751" src="https://user-images.githubusercontent.com/1795990/76556055-3580c380-646f-11ea-803d-7087d3f9c482.png">

@samiyaakhtar What does the Environment column in the dashboard above map to in the command
`./spk/spk deployment create  -n $(INTROSPECTION_ACCOUNT_NAME) -k $(INTROSPECTION_ACCOUNT_KEY) -t $(INTROSPECTION_TABLE_NAME) -p $(INTROSPECTION_PARTITION_KEY) --p2 $(Build.BuildId) --hld-commit-id $latest_commit --env $BRANCH_NAME --image-tag $tag_name --pr $pr_id` ?

**Comment by samiyaakhtar** [comment]
@andrebriggs it maps to `--env $BRANCH_NAME`

**Comment by samiyaakhtar** [comment]
@andrebriggs in the case here the ring name is not develop, it's the branch in source repo that's develop. The ring name is `deploy/epmt/order-store-order-service-develop-20200312.5`

**Comment by samiyaakhtar** [comment]
Extracting ring name during ACR -> HLD step shouldn't need to read bedrock.yaml because ring names are stored as an array in yaml: 
```yaml
rings:
  master:
    isDefault: true
  deve: {}
  qa: {}
  prod: {}
services:
  ...
```
There’s actually no way to infer what ring maps to, during acr->hld pipeline since there's no metadata under each ring name. In fact, `$(Build.SourceBranchName)` should always map to a ring name in bedrock.yaml. This should heavily simplify this task to no longer involve reading bedrock.yaml.
