### ISSUE TITLE
spk deployment get should display PR column 

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#1167]
**As a:** developer

**I want:** to see a column PR IDs into my HLD

**So that:** I know which deployments are pending manifest generation and can approve/reject

**Describe the solution you'd like:**
- [x] Update spk get command to support this additional column, post completion of https://github.com/microsoft/bedrock/issues/1165 

**Acceptance Criteria:**
A new column is in `spk deployment get`

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by andrebriggs** [comment]
@samiyaakhtar have we thought about how this would look? Related to #743

**Comment by samiyaakhtar** [comment]
@andrebriggs this could look similar to all other columns, something along these lines: 
![Screen Shot 2020-03-24 at 3 36 14 PM](https://user-images.githubusercontent.com/1795990/77563808-fc891b80-6e7e-11ea-9e8a-18c58bb8304b.png)
