### ISSUE TITLE
Introspection dashboard should capture display name of services in mono repos

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1173]
<img width="501" alt="image" src="https://user-images.githubusercontent.com/3119513/76664783-c4124500-6542-11ea-9145-accde2c64251.png">

In the screenshot above there are two separate services in the "order-store" mono repo. It would be great is the display name in `bedrock.yaml` for these services was actually seen in the service column. 

- [x] prototype and implement a command `spk project get-display-name` which gets the display name of a service from its folder name, and repository name can stay as is 
- [x] Consume this command in spk generated pipelines after it's available in a release

**Comment by andrebriggs** [comment]
## A first pass idea on a way to accomplish this

1. The `SRC to ACR`/`ACR to HLD` pipeline is based in the application repo codebase. Regardless of mono-repo or not the `bedrock.yaml` file contains the metadata needed.
2. During the `SRC to ACR`/`ACR to HLD` pipeline we clone the application repo and can read the `bedrock.yaml` and map the directory that the Dockerfile is in to a `displayName` in the `bedrock.yaml` (we can build this logic into `spk`, e.g. `spk project get-display-name`?)
3. We can then extend `spk deployment create` to accept an optional parameter for displayName and pass through the `bedrock.yaml` value. 
4. The `HLD to Manifest` pipeline would link to the `SRC to ACR`/`ACR to HLD` via the existing "latest commit" method

At this point we would have additional metadata in the Azure Storage table and can give the user to the option to show displayName of a service or the repository name

@samiyaakhtar

**Comment by samiyaakhtar** [comment]
@andrebriggs i support the idea of building this logic into spk, to have a command that extracts the display name. However I'm thinking if we need a new field for this, perhaps we can reuse the ring/env column in storage for this? In that case we can pass in this ring name when `spk deployment create` is called for --env. Thoughts? Particularly, is there a reason to still keep the ring name we show in [this](https://user-images.githubusercontent.com/1795990/76556055-3580c380-646f-11ea-803d-7087d3f9c482.png)?

**Comment by andrebriggs** [comment]
@samiyaakhtar that could work if it is consistent for single ring (default) scenarios. For instance below is a screenshot from a version of the dashboard from early Feb. I'm assuming your HLD only has the `master` (default) ring. Where is DEV coming from? 

<img width="1680" alt="Screen Shot 2020-01-28 at 12 51 22 PM" src="https://user-images.githubusercontent.com/3119513/76829540-a8c46580-67e0-11ea-9024-9c862a724a0c.png">

**Comment by samiyaakhtar** [comment]
@andrebriggs yes this is a dashboard that's not really making the use of rings, so it has only one default environment (DEV). This was set up a long time ago before spk configured rings, so it's not a good reference for this.

**Comment by samiyaakhtar** [comment]
Depending on https://github.com/microsoft/bedrock/issues/1117 for changes to bedrock.yaml schema.

**Comment by andrebriggs** [comment]
@samiyaakhtar is this still a *small* task?

**Comment by samiyaakhtar** [comment]
@andrebriggs changed it to medium. The work for this is complete but will PR after 1117 is merged, since I worked off of that.
