### ISSUE TITLE
spk hld init fails when using --git-push

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1181]
## Issue from a customer

I noticed we don't have an integration test for `spk hld init --git-push` so we should verify if this is really a problem.

More context:
>using 'spk hld init fails when using --git-push'  will cause an error:
> 
> Initializing bedrock HLD repository.
> 
> info:    Generating hld manifest-generation in /home/mazilber/cluster-hld/ChangeFeedFork_HLD
> 
> warn:    Existing manifest-generation.yaml found at /home/mazilber/cluster-hld/ChangeFeedFork_HLD/manifest-generation.yaml, skipping generation.       info:    Generating component.yaml in /home/mazilber/cluster-hld/ChangeFeedFork_HLD
> 
> warn:    Existing component.yaml found at /home/mazilber/cluster-hld/ChangeFeedFork_HLD/component.yaml, skipping generation.
> 
> info:    Generating starter .gitignore in /home/mazilber/cluster-hld/ChangeFeedFork_HLD
> 
> warn:    Existing .gitignore found at /home/mazilber/cluster-hld/ChangeFeedFork_HLD/.gitignore, skipping generation.
> 
> error:   error: unknown option `show-current'
> 
> usage: git branch [<options>] [-r | -a] [--merged | --no-merged]
> 
>    or: git branch [<options>] [-l] [-f] <branch-name> [<start-point>]
> 
>    or: git branch [<options>] [-r] (-d | -D) <branch-name>...
> 
>    or: git branch [<options>] (-m | -M) [<old-branch>] <new-branch>
> 
>    or: git branch [<options>] (-c | -C) [<old-branch>] <new-branch>
> 
>    or: git branch [<options>] [-r | -a] [--points-at]
> 
>    or: git branch [<options>] [-r | -a] [--format]
> 
>  
> 
> Generic options
> 
>     -v, --verbose         show hash and subject, give twice for upstream branch
> 
>     -q, --quiet           suppress informational messages
> 
>     -t, --track           set up tracking mode (see git-pull(1))
> 
>     -u, --set-upstream-to <upstream>
> 
>                           change the upstream info
> 
>     --unset-upstream      Unset the upstream info
> 
>     --color[=<when>]      use colored output
> 
>     -r, --remotes         act on remote-tracking branches
> 
>     --contains <commit>   print only branches that contain the commit
> 
>     --no-contains <commit>
> 
>                           print only branches that don't contain the commit
> 
>     --abbrev[=<n>]        use <n> digits to display SHA-1s
> 
>  
> 
> Specific git-branch actions:
> 
>     -a, --all             list both remote-tracking and local branches
> 
>     -d, --delete          delete fully merged branch
> 
>     -D                    delete branch (even if not merged)
> 
>     -m, --move            move/rename a branch and its reflog
> 
>     -M                    move/rename a branch, even if target exists
> 
>     -c, --copy            copy a branch and its reflog
> 
>     -C                    copy a branch, even if target exists
> 
>     --list                list branch names
> 
>     -l, --create-reflog   create the branch's reflog
> 
>     --edit-description    edit the description for the branch
> 
>     -f, --force           force creation, move/rename, deletion
> 
>     --merged <commit>     print only branches that are merged
> 
>     --no-merged <commit>  print only branches that are not merged
> 
>     --column[=<style>]    list branches in columns
> 
>     --sort <key>          field name to sort on
> 
>     --points-at <object>  print only branches of the object
> 
>     -i, --ignore-case     sorting and filtering are case insensitive
> 
>     --format <format>     format to use for the output
> 
> 
> Per Andre to address this issue "--git-push" should be removed.
>

**Comment by bnookala** [comment]
@andrebriggs It's a bit buried in the docs, but we do require that the git version the user is running is at _least_ 2.22 - https://github.com/CatalystCode/spk/blob/master/guides/project-service-management-guide.md#requirements, since some features we use were added in that release: https://github.com/git/git/commit/0ecb1fc7269e15be890870937b8b639c987abd08

**Comment by bnookala** [comment]
Update: apparently git 2.22 on WSL does not appear to work - they're using 2.25

**Comment by mzilberman** [comment]
The issue is that by default all and updated WSL, today, has git version 2.17.  Switching to 2.25 requires pointing WSL to canary.

**Comment by bnookala** [comment]
@mzilberman while that's true - you can still use `apt` (presuming an ubuntu install on WSL) to update and upgrade the default packages by following the instructions https://askubuntu.com/questions/568591/how-do-i-install-the-latest-version-of-git-with-apt

```
sudo add-apt-repository ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git
```

**Comment by bnookala** [comment]
@mzilberman I was able to confirm that you are able to follow the instructions i posted in my previous comment to update git and use spk.

```
