### ISSUE TITLE
SPK lifecycle pipeline doesn't not specify helm2 support

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1182]
Related to https://github.com/microsoft/bedrock/issues/1171.

We should check to see if the build HLD update pipeline also has this issue.

```bash
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/c44db485-c526-442b-a5bb-f61a2ca5697d.sh
argument is --source-only
Sourcing build.sh ...
VERIFYING PERSONAL ACCESS TOKEN
RUN HELM INIT
Error: unknown flag: --client-only

##[error]Bash exited with code '1'.
Finishing: Download Fabrikate and SPK, Update HLD, Push changes, Open PR
```

**Comment by mtarng** [comment]
Looks like the [PR](https://github.com/CatalystCode/spk/pull/406) to close #1171 only modified a single pipeline. We need to add the changes to set helm version to the other 2. Should be a quick fix.
