### ISSUE TITLE
Expand helm documentation to describe service type options

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#1193]
**As a:**
spk user creating my helm chart
**I want:**
Guidance on service types. 
**So that:**
I can make an informed decision when choosing my Service type on helm chart configuration
**Describe the solution you'd like:**
Expanded documentation or link on k8s service types and explaining what bedrock suggests

*Author's comment*- I believe we should suggest ClusterIP as the default so that services aren't exposed directly though a provisioned external IP, rather all traffic should be routed through the IP provisioned for Traefik2

**Additional context:**
Our [reference documentation](https://github.com/microsoft/bedrock/blob/d6ad847d3372f2d2def0e6e8368d516d1ace68a6/docs/services.md#onboarding-a-service) points to a Service that, by default, is configured to a `LoadBalancer`. 
**Does this require updates to documentation?:**

**Comment by mtarng** [comment]
@mzilberman

**Comment by andrebriggs** [comment]
@mtarng @mzilberman is the suggestion that our helm chart guidance should push users to use Traefik? 

I agree that using a non external IP should be an option. In the Helm Chart we created for Spektate we have logic to flip between a LoadBalancer and aNodePort by using a [value](https://github.com/microsoft/spektate/blob/16196d3d005ba8c78b9cb0c88e03805a4fa0abfd/chart/values.yaml#L17). Would that approach be reasonable? cc @samiyaakhtar

**Comment by mzilberman** [comment]
@andrebriggs I don't know the answer to this, it seems that you have chosen Traefik for a reason yet the docs so far make no mention of why Traefik vs. LB vs. ClusterIp
