### ISSUE TITLE
As an SRE - I would like a way to rotate the AKS service principal

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#1199]
**As an:** SRE

**I want:** an ability to rotate a service principal in use by an AKS cluster

**So that:** secrets can be versioned in a reasonable manner.

**Acceptance Criteria:**. The cluster is provisioned with a new service principal and continues operation accordingly -- access to network, access to key vault, etc.

**Comment by yradsmikham** [comment]
This seems very general. What is the proposed solution? Is this something we wan `spk infra` to handle, or `spk` alone to handle? Or should this be manually done somehow?

@jmspring  @andrebriggs

**Comment by andrebriggs** [comment]
@yradsmikham We are expecting instructions on how to do this

**Comment by jmspring** [comment]
The process is documented here -- https://docs.microsoft.com/en-us/azure/aks/update-credentials

I need to see what happens when one uses Terraform.
