### ISSUE TITLE
Rings integration tests: update

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#1205]
**As a:**
spk tester
**I want:**
smoke tests for updating rings 
**So that:**
i have have tested work flows

**Acceptance Criteria:**
- [x] Create a branch for the ring, make a change, and verify the image tag. Related: [Azure Pipelines path triggers cannot begin with "."](https://github.com/microsoft/bedrock/issues/1168)

Related to #838 

**Additional context:**
Covering the flow in this epic: https://github.com/microsoft/bedrock/issues/955

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@edaena are we still blocked here?

**Comment by mtarng** [comment]
This task may still be blocked as we do not have the logic to remove rings from the hld:

https://github.com/microsoft/bedrock/issues/1118

parent epic: https://github.com/microsoft/bedrock/issues/858
