### ISSUE TITLE
Add SPK support for services with custom dockerfiles

### ISSUE THREAD

**Issue by erikschlegel** [microsoft/bedrock#1207]
User Story for #1111

**As a:**
Service Developer

**I want:**
to leverage spk add new a service to a bedrock project using my own dockerfile
 
**So that:**
I can deploy a spring boot application to kubernetes

**Describe the solution you'd like:**
I'd like SPK to support bringing my own dockerfile when setting up a new service.The customer is deploying a set of spring boot microservices to AKS. Their existing dockerfile is shown below.
```
FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
```
The JAR file referenced in the docker build argument will be pre-generated from an earlier pipeline. That JAR file will need to reside within the docker context. One approach is to allow the customer to own the docker image build and publish step? 

**Acceptance Criteria:**
- I can deploy one of the customer's spring boot microservice to AKS through SPK's service ADO pipeline.
- I can succesfully build and publish a docker image using the earlier mentioned `Dockerfile`.

**Does this require updates to documentation?:**
Not sure

**Comment by andrebriggs** [comment]
@bnookala you put this into last week's sprint without any proposal for `spk` interface changes. What are the expected changes to `spk` command or args that we can expect?

cc @mtarng @evanlouie

**Comment by mtarng** [comment]
@bnookala What changes do you think we need? `spk` does not create a Dockerfile if one exists in the service path, and the one generated is a placeholder that just echos out "hello world". So a user bringing their own Dockerfile is what is expected already.

**Comment by bnookala** [comment]
Closing this issue to track the up-to-date feature request here: https://github.com/microsoft/bedrock/issues/1362
