### ISSUE TITLE
spk infra definition.yaml is edited multiple times during the process

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1223]
Feedback on `spk infra`:
> it would be great to see a flow that does not have the user going back to edit the same file more than once.  This happens for deployment.yaml

**Comment by yradsmikham** [comment]
Can we have more information regarding this feedback? Which is the `deployment.yaml`?

**Comment by andrebriggs** [comment]
@yradsmikham I think this might be a misunderstanding of editing a `definition.yaml` for east and west in the multi cluster  instructions. Closing
