### ISSUE TITLE
Better guidance for the user to make appropriate choices for a directory structure

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1230]
Feedback on First Workload:

> Given that the reader is not familiar with the solution and is being guided to clone repos, create keys and store settings, it is important to provide guidance for a directory structure.  I found myself lost where things are and in 2 cases created assets where they were not intended or expected.
> 
> A recommended (as you build it) directory structure is highly recommended, all files, keys, settings created during install and config should reside in one directory so that it could be moved with simple tar/zip.
> All steps where any Create, Update and Delete operations are performed need a clear notation of the working directory.

**Comment by andrebriggs** [comment]
I think it is reasonable for us to show a directory structure of what each repo would look like and how to position the repos side by side in a local developer machine. This would help a read know they are "done"

For instance at the end we can say you should have `bedrock-workload` dir somewhere on your machine and it should have the following by the end of the walkthrough:
```
.
├── hld-repo
├── manifest-repo
├── voting-app
├── helm-chat-repo
├── bedrock-tf-generated-repo
└── yarn.lock
```

**Comment by evanlouie** [comment]
should live in "first workload" doc
