### ISSUE TITLE
Question: One ring is enabled without user asking for ring management after First Workload doc

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1235]
Feedback: 
> the end point is deploying using traefik and is automatically hidden behind a master ring.  At the end of service management to hit the deployed end point I have to use:
> 
> curl -Lv -H "Ring: master" 52.224.52.24/changefeed-app-service/weatherforecast -v
> 
> this is unexpected as I did not ask for a ring and documentation does not tell me that this is what is going to happen

**Comment by andrebriggs** [comment]
@bnookala @evanlouie

**Comment by bnookala** [comment]
Fixed by: https://github.com/CatalystCode/spk/pull/427

**Comment by bnookala** [comment]
Docs: https://github.com/CatalystCode/spk/blob/8724e4003edd2f5138748c1257c09a0284ea90b7/guides/rings-101.md#setting-the-default-ring--routing
