### ISSUE TITLE
Missing brew dependency for mac users

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#1248]
**Describe the bug:**
The [bedrock prereqs scripts](tools/prereqs/setup_terraform.sh) contain references to `brew` - if a user runs the script directly into their CLI, they may run into an error - that `brew` is not installed.

**To Reproduce:**
1. Ensure `brew` is not installed
2. Run the terraform setup script

**Expected behavior:**
We should let the user know how to install `brew` ie:

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
` (for macOS)

**Does this require updates to documentation?:**
Yes

**Comment by yradsmikham** [comment]
Would we just update the docs here: https://github.com/microsoft/bedrock/tree/master/tools/prereqs? or is there another place?

**Comment by NathanielRose** [comment]
This issue was created due to `unzip` command not being already installed natively in WSL. Added support to download unzip was added here for wsl: https://github.com/microsoft/bedrock/blob/master/tools/prereqs/setup_terraform.sh#L33

For darwin machines, `unzip` is natively installed and we dont need to use brew as a dependency specifically for `unzip`. Line https://github.com/microsoft/bedrock/blob/master/tools/prereqs/setup_terraform.sh#L36 could be removed or we can simply add a note to install brew as a prereq in the README.md for Mac machines.

**Comment by yradsmikham** [comment]
@NathanielRose, gotcha. I'll remove `brew install unzip` and update the README.md.
