### ISSUE TITLE
bash command to upload public SSH key to git repo settings

### ISSUE THREAD

**Issue by naveen10545** [microsoft/bedrock#1254]
need bash command to upload ssh public key to git repo settings deploy key section.

**Comment by andrebriggs** [comment]
@naveen10545 what Git repo provider are you using? 

GitHub: [Add a new deploy key](https://developer.github.com/v3/repos/keys/#add-a-new-deploy-key)

AzDO:  There [isn't any official API support](https://github.com/MicrosoftDocs/vsts-docs/issues/5616), however you can try [this](https://stackoverflow.com/a/52751232) unverified work around

**Comment by naveen10545** [comment]
hi @andrebriggs  the Key should go to the following location:
![image](https://user-images.githubusercontent.com/59998397/77617168-768dd300-6f59-11ea-8519-26eeb4ba6763.png)

**Comment by andrebriggs** [comment]
Hi @naveen10545, so you're using GitHub. We don't provide a script to do this automatically but you can use the API link I referenced to create a bash script to achieve this. 

One thing to know is that if your organization use multi-factor authentication on GitHub you might not be able to to seamlessly automate this.

**Comment by jred55** [comment]
Closing this @naveen10545, feel free to re-open if you need further guidance
