### ISSUE TITLE
Health and Version endpoints on the SPK dashboard

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1258]
**As a:**
developer or SRE

**I want:**
To know that the SPK dashboard is working

**So that:**
I can spend less time troubleshooting the dashboard

**Describe the solution you'd like:**
I would propose an endpoint the spk dashboard would what tell me what version the of teh docker image is running and what environment variables are present.

For instance `localhost:5000/version` and `localhost:5000/health`

### `localhost:5000/version`
This would tell me what version or build number the docker image is a json output

### `localhost:5000/health`
This would give me a json output of all the env vars that are present. This could help me troubleshoot when an environment variable is missing. **The SPK dashboard docker image will still run when env vars are missing**. This would help me troubleshoot what env vars are missing.

**Acceptance Criteria:**
I can make sure I have all teh necessary env vars to run and that I know what version of the dashboard I'm running

**Does this require updates to documentation?:**

**Comment by dennisseah** [comment]
`localhost:5000/health` - dumping env vars can be a security issue because some of these values are sensitive.

**Comment by andrebriggs** [comment]
@dennisseah good point. I'm imagining a page that simply lets me know that the env vars that Spektate dashboard requires are all present.

**Comment by samiyaakhtar** [comment]
Based on discussion today, there should be no need to build a UI for these endpoints. 
- **/version**: This endpoint should display the docker image version, but also this information should be available somewhere in the main spektate dashboard in small font
- **/health**: This endpoint should display in plain text/json the information a user needs to troubleshoot why the dashboard loads incorrectly, what env vars are provided and what was expected to be provided, and error messages (if any).
