### ISSUE TITLE
Implement caching solution on backend of dashboard

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1264]
Based on design [here](https://github.com/CatalystCode/spk/blob/master/technical-docs/designs/introspection/deploymentDashboardCaching.md)

Related to #1090

**Comment by dennisseah** [comment]
delivered in a branch `backendCaching`. Samiya will help to enhance it

**Comment by dennisseah** [comment]
I have delivered a solution to Samiya and she will continue
