### ISSUE TITLE
Spektate dashboard needs continuous deployment 

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1267]
**As a:**
developer

**I want:**
The [Spektate](https://github.com/microsoft/spektate/) dashboard to be continuously deployed.

Currently the Spektate codebase pushes a Docker image on every master build but none of the images are used for anything. There is no way see what changed or to be able do manual testing.

**So that:**
Everyone can see what the latest changes are. People who are contributing to Spektate can easily see the results of their changes and demo to others. People who are unfamiliar with Spektate can see the latest version. This 

**Describe the solution you'd like:**
A solution would be to have the Docker image deployed on every master merge build.

**Acceptance Criteria:**
I can see the Spektate UI hosted with the absolute latest changes. I can see data (even if it is dummy data) in the UI. This happens automatically after master merge.

**Describe alternatives you've considered:**
Having to pull the image and setting up numerous env vars manually.

**Does this require updates to documentation?:**
Yes

**Comment by samiyaakhtar** [comment]
This would be nice. It would also be nice to track spektate's CI and CD using Spektate itself (inception)

I'm thinking that once we have the tasks under https://github.com/microsoft/bedrock/issues/938 complete, we should use the HLD for spektate to host spektate itself, and have a full CI-CD pipeline all the way to a cluster. Thoughts?
