### ISSUE TITLE
Bedrock should automatically configure cloud storage of Terraform state

### ISSUE THREAD

**Issue by day-jeff** [Microsoft/bedrock#127]
The current process requires manual creation of a storage account and a resource group that contains the account. And the user needs to run commands to initialize cloud storage.

Suggesting a new feature: Create the RG and storage account using Terraform.

**Comment by jmspring** [comment]
This work was handled by having backend.tfvars in each as well as declaring the backend requirement and a tf script to create the storage account info in azure/backend-state.
