### ISSUE TITLE
Exclude bedrock.yaml from build pipeline triggers

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#1275]
**As a:**
spk user
**I want:**
my service build pipelines to exclude changes from `bedrock.yaml` from triggering a build pipeline.
**So that:**
I do not end up with unnecessary builds and PRs against the HLD repository for project management changes.

**Describe the solution you'd like:**
service build pipelines should have:
```
trigger:
    paths:
      exclude:
        - bedrock.yaml
```
in their definition
**Acceptance Criteria:**
- [ ] New service build pipelines have an exclude trigger on `bedrock.yaml`.
- [ ] Validate that changes to `bedrock.yaml` do not trigger service builds.
- [ ] Update documentation to reflect behavioral change

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@mtarng I would argue this requires updates to documentation. It's a behavioral change.
