### ISSUE TITLE
Dashboard shows empty cluster sync column when there's no data to show

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#1296]
**Describe the bug:**
https://spk-ci.azurewebsites.net/? is showing cluster sync column even though there's no data to show in it. 

**To Reproduce:**
Load the page and see cluster sync column show up, although there's no data

**Expected behavior:**
Column should not show if there's no data to show

**Screenshots:**
![Screen Shot 2020-04-01 at 1 07 14 PM](https://user-images.githubusercontent.com/1795990/78182075-5b6c0900-741a-11ea-8291-bcd936ed6ddd.png)

**Additional context:**

**Does this require updates to documentation?:**

**Comment by andrebriggs** [comment]
I'm wondering if this is still valid. I use the http://spektate-ci-env.eastus.azurecontainer.io:5000/ as the automated CI site and currently don't see that issue. Re-open if you see the issue.
