### ISSUE TITLE
Dashboard should support sorting on some columns

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#1298]
**As a:** developer

**I want:** to sort the dashboard on some columns, such as ring, service, last updated

**So that:** I can introspect my services

**Describe the solution you'd like:**
[azure-devops-ui](https://azdevinternal.azureedge.net/components/table#table-with-sorting) supports basic sorting by clicking on column headers. 
- [x] Add sorting support to columns in the dashboard: ring, service, author, merged by, last updated (default) 

**Acceptance Criteria:**
Dashboard is more user friendly

**Describe alternatives you've considered:**
No sorting

**Additional context:**
Bug in azure-devops-ui table https://github.com/microsoft/azure-devops-ui/issues/264 is blocking us from having a seamless experience since it doesn't support having default sorted column, so the sort state is getting lost every time the table is refreshed.

**Does this require updates to documentation?:**

**Comment by andrebriggs** [comment]
@samiyaakhtar can we be specific about which columns exact. Let's assume that folks who might take this on have no context

**Comment by samiyaakhtar** [comment]
@andrebriggs updated the description
