### ISSUE TITLE
deploying the simple service is not working correctly

### ISSUE THREAD

**Issue by ben-st** [Microsoft/bedrock#13]
The deployment of the simple service is IMHO not working correctly.

the repo name refers to @timfpark  and i cannot push to this docker repo.
https://github.com/Microsoft/bedrock/blob/master/services/common/deploy-service#L26

![screenshot 2018-11-29 at 13 42 42](https://user-images.githubusercontent.com/18464684/49222907-8638ee00-f3dd-11e8-9db1-ca09acc67e5e.png)

possbile way to go: 

we change the values in the file:https://github.com/Microsoft/bedrock/blob/master/services/modules/simple-service/deploy-simple-service

or update the README with an overwrite of the default values.

or we could stop building it and relying on a prebuilt docker image.

The Dockerfile is currently missing the docker package and we would have to mount the docker socket into the container while starting it.

Steps done:
tried to test it via minikube:

`docker build -t bedrock:latest .`

```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --net=host -it -v ~/.minikube:/.minikube -v ~/.kube/config:/.kube/config -e TF_VAR_grafana_admin_password="SECRETpass" bedrock:latest /bin/bash
```

```
cd services/environments/dev
./init
./apply
```

@timfpark  what do you think?

All the best,

Benjamin

**Comment by timfpark** [comment]
I just noticed that there is a hardwired container repo path as well - I will fix that first and then try under docker again.

**Comment by NathanielRose** [comment]
Will be resolved in Gitops implementation

**Comment by andrebriggs** [comment]
@ben-st Is this still an issue? The [instructions](url
https://github.com/Microsoft/bedrock#deploy-a-service) have been updated say to replace docker.io/timfpark with your own account (e.g. docker.io/andrebriggs)

**Comment by ben-st** [comment]
Sounds Good to me, i will test it later but we can close this issue. 
Thanks for the fix
