### ISSUE TITLE
Simple test cluster doesnt work

### ISSUE THREAD

**Issue by 4c74356b41** [Microsoft/bedrock#130]
```
* module.flux.null_resource.deploy_flux: Error running command 'echo 'Need to use this var so terraform waits for kubeconfig ' 6903179110618493715;KUBECONFIG=./output/bedrock_kube_config /bedrock/cluster/environments/azure-test/.terraform/modules/67e616151dc15db5ba0540c2b00cbed7/deploy_flux.sh -b master -f https://github.com/weaveworks/flux.git -g git@github.com:4c74356b41/fabrikate-cloud-native-manifests.git -k key -d bedrock-flux': exit status 127. Output: Need to use this var so terraform waits for kubeconfig  6903179110618493715
/bin/sh: /bedrock/cluster/environments/azure-test/.terraform/modules/67e616151dc15db5ba0540c2b00cbed7/deploy_flux.sh: not found
```

tried several times, slightly different containers. the path its referring to doesnt exist indeed, but I would expect ti to be populated by TF. I think the issue is with path.module.

tools:
```
HELM_VERSION="v2.8.0"
KUBECTL_VERSION="v1.13.3"
TERRAFORM_VERSION="0.11.11"
latest cli
```

**Comment by 4c74356b41** [comment]
I've edited the task to be:
```
  provisioner "local-exec" {
    command = "KUBECONFIG=${var.output_directory}/${var.kubeconfig_filename} hardcoded_path/deploy_flux.sh -b ${var.gitops_url_branch} -f ${var.flux_repo_url} -g ${var.gitops_url} -k ${var.gitops_ssh_key} -d ${var.flux_clone_dir}"
  }
```

still facing the same error, questionmark

**Comment by 4c74356b41** [comment]
ok, never mind, stupid git did checkout crlf, for some unknown reason.

**Comment by 4c74356b41** [comment]
Appears I was too hasty:
```
error: Error loading config file "./output/bedrock_kube_config": yaml: mapping values are not allowed in this context
ERROR: failed to create kubernetes namespace flux
```

the config is returned as a single string with `\n` and kubectl cannot parse that

**Comment by timfpark** [comment]
Very strange - which shell / OS are you using?

**Comment by 4c74356b41** [comment]
alpine container\bash. it works for me if I replace your code with this:

```
\"${azurerm_kubernetes_cluster.cluster.kube_config_raw}\"
```

**Comment by 4c74356b41** [comment]
completely unrelated, is there a slack or something where I can reach you guys? also, I'm really new to ELK, will it gather all the logs from the pods or do I have to configure something? I dont think I saw any docs on components you are installing. I'm quite familiar with istio,flux and prometheus, not quite with all the others. so not sure how those are configured. any readings?

**Comment by timfpark** [comment]
Ok - let me test your change on the other configurations - I can't remember why we were using jsonencode there.

**Comment by timfpark** [comment]
@4c74356b41 We don't yet - but that is a great idea. I will start one when I get a chance.

On the "cloud native" stacks - I would recommend having a look at the documentation for each on https://github.com/helm/charts

On EFK in particular - yes, the stack as configured will deploy elasticsearch, fluentd, and kibana.  Once you have the cluster spun up you should be able to do a:

```
export KIBANA_POD=$(kubectl get pods --namespace kibana -l "app=kibana,release=kibana" -o jsonpath="{.items[0].metadata.name}")
`sleep 1 && open http://localhost:5601/app/kibana#/discover` &
kubectl port-forward --namespace kibana $KIBANA_POD 5601
```

and start querying the logs in your Elasticsearch instance from Kibana.  Fluentd is installed as a daemonset and should immediately start collecting logs.

**Comment by 4c74356b41** [comment]
ah, so you "just" compiled individual charts to work together: elasticsearch, fluentd and kibana, right?

**Comment by timfpark** [comment]
That's right - we are calling them "stacks" - and our goal is to make it easier to use these platforms by providing them as preconfigured bundles.  That is technically part of the [Fabrikate project](https://github.com/Microsoft/fabrikate) - and we just use a [cloud native one](https://github.com/timfpark/fabrikate-cloud-native) as a sample here in Bedrock.

**Comment by 4c74356b41** [comment]
yes, thank you. That I do understand ;) I see you created a PR, so it doesnt work for you as well, or it works for you both ways?

**Comment by timfpark** [comment]
It works for me without the jsonencode as well on bash/MacOS - testing now on Bash under WSL on Windows as well.

**Comment by timfpark** [comment]
Thank you for your bug report - we merged your suggested change in https://github.com/Microsoft/bedrock/commit/b5be1fd15eaaea63840bf687914d1b2644287de2.

**Comment by 4c74356b41** [comment]
thanks, @timfpark how can I contribute to this project? I mean, I'm not exactly the smartest person, but I could do some stuff ;)

**Comment by timfpark** [comment]
Absolutely - just use it for your projects and keep suggesting improvements and give us feedback on what could be easier.

**Comment by timfpark** [comment]
Naturally pull requests for things you need are gratefully accepted as well - open an issue to discuss first.
