### ISSUE TITLE
Error loading SPK configuration file during tutorial

### ISSUE THREAD

**Issue by jsturtevant** [microsoft/bedrock#1304]
**Describe the bug:**
When following the [First workload](https://github.com/microsoft/bedrock/tree/master/docs/firstWorkload) tutorial after running 

```
spk infra scaffold --name cluster --source https://github.com/microsoft/bedrock --version master --template cluster/environments/azure-simple                                                      
```

I get the following message:

```
warn:    Error loading SPK configuration file; run `spk init` to initialize your global configuration or ensure you have passed all required parameters to the called function.
warn:    The infrastructure repository containing the remote terraform template repo and access token was not specified. Checking passed arguments.
info:    All required options are configured via command line for scaffolding, expecting public remote repository for terraform templates or PAT embedded in source URL.
info:    Converted to: _microsoft_bedrock
info:    Checking if source: /home/jstur/.spk/templates/_microsoft_bedrock is stored locally.
info:    Source template folder found. Validating existence of repository.
info:    Remote source repo: https://github.com/microsoft/bedrock exists.
info:    Checking if source repo: https://github.com/microsoft/bedrock has been already cloned to: /home/jstur/.spk/templates/_microsoft_bedrock.
info:    https://github.com/microsoft/bedrock already cloned. Performing 'git pull'...
info:    Checking out template version: master
info:    Terraform template files copied from /home/jstur/.spk/templates/_microsoft_bedrock/cluster/environments/azure-simple
info:    Terraform variables.tf file found. Attempting to generate definition.yaml file.
info:    No remote backend configuration was found.
info:    A variables.tf file found : cluster/variables.tf
```

It appears that some information gets scaffoled but the warning and error lead me to think I did something wrong.  

**To Reproduce:**

**Expected behavior:**
Tutorial scaffolding is successful with no warnings.  It is unclear if this is expected behavior or how to resolve it.  Should I be running `spk init` before first scaffolding?  Is that a warning I can skip for now?  What are the required parameters?

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by NathanielRose** [comment]
@jsturtevant, It looks like the scaffold command did run successfully but you are seeing warning messages pertaining to initializing the cli `spk init`.  It runs a `constructSource` which pulls in the `spk.config` file if used. We'll update the documentation to reflect this behavior.

**Comment by jsturtevant** [comment]
It does seem spk completed correctly.  For someone new to spk it was a bit confusing. Docs explaining warning and options for configuring should help 👍

**Comment by andrebriggs** [comment]
Should be covered in the next release. See https://github.com/microsoft/bedrock/issues/1140 Please reopen if this doesn't cover
