### ISSUE TITLE
Error codes, error chain for project commands

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#1305]
**As a:**
User

**I want:**
error specific codes and error chaining for spk project: create-variable-group, init commands

**So that:**
I can understand the root cause.

**Describe the solution you'd like:**
add error code and maintain exception chain

**Acceptance Criteria:**

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
No

part of https://github.com/microsoft/bedrock/issues/1088

**Comment by dennisseah** [comment]
closed by https://github.com/CatalystCode/spk/pull/514
