### ISSUE TITLE
Dashboard should utilize caching in front end

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#1318]
**As a:** developer of Spektate

**I want:** to utilize caching in the backend

**So that:** front end does not have to call 4 different endpoints, and API limits would not be hit

**Describe the solution you'd like:**
- [x] There's a [branch](https://github.com/microsoft/spektate/tree/backendCaching) in spektate with backend caching work. Utilize this and extend it to be used in front end. 
    - Find every API call that is being made for every deployment (it should be just /api/author and /api/pr) these should be contained within the data returned from /api/deployments and the API calls for these should be removed. Extract this data from /api/deployments instead 
    - /api/clustersync is a single one time call and can stay 
    - Test the scenario where deployments that are in progress are being refreshed quickly, whereas deployments that have completed and will never change can be fetched from cache repeatedly.

**Acceptance Criteria:**
Caching is being used through the dashboard 

**Describe alternatives you've considered:**
No caching 

**Additional context:**

**Does this require updates to documentation?:** No

**Comment by andrebriggs** [comment]
@samiyaakhtar please break this up

**Comment by samiyaakhtar** [comment]
@andrebriggs it's a little hard to break when I'm not fully sure what work it will require. Changing to a medium

**Comment by andrebriggs** [comment]
@samiyaakhtar do we have at least a high level idea? If so let's share it. If not we need to reevaluate

**Comment by samiyaakhtar** [comment]
@andrebriggs added more detail.
