### ISSUE TITLE
Spektate dashboard has performance issues with many rows loading.

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1335]
**Describe the bug:**
Spektate dashboard  has a performance problem when too many rows get loaded. This gets worse when it takes over 30 seconds to load the page then  the dashboard decided to refresh itself even though it didn’t finish loading data.

Related: https://github.com/microsoft/bedrock/issues/800#issuecomment-605148138

**To Reproduce:**
I suggest you stress test the the dashboard by generating dummy data in the Storage Account table with valid Azure DevOps references (repeated).

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/3119513/78955816-4a17a200-7a95-11ea-8c04-ef1626d4594b.png">

**Expected behavior:**
The page should not refresh is the page is still loading. Otherwise put a cap on the number of rows loaded.

**TODO**
- [x] Limit the number of rows
- [x] Create a task to edit refresh time in Spektate

**Comment by andrebriggs** [comment]
An initial mitigation as discussed is to limit the number of rows we display. This should be configuration for the moment. cc @samiyaakhtar

**Comment by evanlouie** [comment]
followup ticket to add user defined refresh/polling rate: https://github.com/microsoft/bedrock/issues/1359
