### ISSUE TITLE
spk init -i should log with the config file is created

### ISSUE THREAD

**Issue by jsturtevant** [microsoft/bedrock#1349]
After running `spk init -i` there is no indication of where a file created. Let's add information to improve the DX.

- [x] Add logging to indicate where the config file is created
- [x] Update [--help documentation](init.decorator.json) to hint at where the default config location is 

This well help folks know where to go in order to override or copy a config file.

**Comment by andrebriggs** [comment]
@jsturtevant can you please provide the version of the CLI and platform?

Also is your expectation that the config file appears in your current working directory?

**Comment by andrebriggs** [comment]
Chatted with @jsturtevant and will convert this to a feature request. Updating description

**Comment by dennisseah** [comment]
the first statement in our doc already indicates where config.yaml is created.
https://catalystcode.github.io/spk/commands/#master@init
```
this command creates a configuration file, config.yaml in a folder .spk under your home directory.
```

it already creates a file and we already indicated where it is.

**Comment by andrebriggs** [comment]
> the first statement in our doc already indicates where config.yaml is created.
> https://catalystcode.github.io/spk/commands/#master@init
> 
> ```
> this command creates a configuration file, config.yaml in a folder .spk under your home directory.
> ```
> 
> it already creates a file and we already indicated where it is.

Good point @dennisseah. I think @jsturtevant means in the `--help` command. We can add this information in the `init.decorator.json` file.

**Comment by jsturtevant** [comment]
Thanks! I missed that reference in the docs.  The PR looks like a good update to the tool!
