### ISSUE TITLE
Spektate repo needs frontend and backend separation

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1353]
## Problem
We have [backend](https://github.com/microsoft/spektate/tree/master/src/backend) and [frontend](https://github.com/microsoft/spektate/tree/master/src/client) code in different directories in the [Spektate](https://github.com/microsoft/spektate) repo.

We do not have separate `packages.json` for the two distinct codebases. Instead a single `package.json` lives at the root.

## Proposed Change
Create a `package.json` explicitly for the frontend and backend. A future version of the top level Spektate repo could look like 

```
.
├── backend
│   ├── package.json
│   └── ...
├── frontend
│   ├── package.json
│   └── ...
└── packages/Spektate
│   ├── package.json
    └── ...
```

## Why

Coupling the frontend and backend codebase makes it harder for use to innovate independently. For instance if we add logic to the `backend` it will force a dependency in the `frontend`. Many UI related libraries may require versions of dependencies that conflict with the backend.

Moreover it is a typical pattern to separate a `frontend` and `backend`. See this [example](https://medium.com/codeduck/a-real-world-project-typescript-express-and-react-4701c0458e9c) and [repo](
https://github.com/Dirk94/express-react-app) of best practices for structuring a react app. 

## Additional considerations

Eventually we may want to consider [Lerna](https://github.com/lerna/lerna) as a way to handle mono-repo structures with some dependency management help built in. For the moment we should at least separate the frontend and backend

Related to #1090

**Comment by samiyaakhtar** [comment]
>if we add logic to the backend it will force a dependency in the frontend.

The backend is a very simple Node.js express server, and all it does is preserve the config and serve data from spektate package to the dashboard. It's also used only by the dashboard, and it's simpler to have them under a common package.json. We had this exact design decision to make while originally implementing, and @dennisseah had some useful resources that explained the pros and cons of both, but I can't seem to find that link right now. Dennis, looking for your thoughts here :) 

Also, that this introduces extra complexity: we will be building separate docker images for front end and back end, versioning and maintaining the two, complex debugging and deploying. Having them in the same one meant that the backend is accessible through /api/, and making a request to * serves the html. It's not necessarily a bad practice, but we should have a discussion before proceeding with any changes here. 

Is there an example of how the current design is holding us back?

**Comment by andrebriggs** [comment]
Yes. The [backendCaching](https://github.com/microsoft/spektate/tree/backendCaching) branch of Spektate basically needs this to work correctly.
