### ISSUE TITLE
Some parts of documentation were a little confusing during first-time setup

### ISSUE THREAD

**Issue by ghost** [Microsoft/bedrock#137]
Couple of notes on some confusion we encountered during our first-time runthrough of setup:

1) In "Creating a new Cluster Environment" it was not immediately clear to me that we were prescribing the variables for a cluster that we *intended* to create - initially I thought we needed to deploy a cluster and then fill in cluster.tfvars with the information from that cluster.  Some of the wording implies that we have already created a cluster:
"...copy our generic environment to a new subdirectory with the name of your cluster"
"Next, edit environments/azure/my-cluster/cluster.tfvars (adjusting this for what you named your cluster)…"
Note: It is very clear in the following section on "Deploying Cluster" that the .tfvars file is being used to deploy the cluster, but perhaps this should be mentioned before the user is instructed to fill in values for the variables.

2) It appears that what is currently "cluster.tfvars" in the documentation is now "terraform.tfvars" in the repo

3) A little more detail what the value of dns_prefix should be - allowed characters, etc.

4) More detail on what exactly needs to be copied into the values for ssh_public_key and gitops_ssh_key - also with these values include information on how to generate these.  I initially didn't realize the process for generating the SSH keys was described in the "Setting Up Gitops Repository for Flux" section at the bottom of the page.

**Comment by sarath-p** [comment]
Referencing similar doc issue #125 and #124.

**Comment by timfpark** [comment]
Closed after @aka-msft's PR - let us know if the current documentation is not clear.
