### ISSUE TITLE
Better support for HLD only changes in Spektate dashboard

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1372]
Currently the Spektate dashboard displays a row with empty values for `service`, `ring`, `SRC to ACR`, `ACR to HLD`, `Approved Pull Request`, and `Merged By` columns for changes that are made only in the HLD repository. 

With the Bedrock CLI there is a feature for [reconciliation](https://github.com/microsoft/bedrock-cli/blob/60c89e1d7c09ae55bb622359baa3a6bbba2824a0/src/commands/hld/reconcile.md) that will trigger pipeline runs that modify the HLD repo.
 
The current behavior of Spektate doesn't make it obvious that this row (circled in screenshot) is a change to the HLD associated with a `service`.

This can also happen with some makes one off changes to the HLD repo for any over modifications (e.g. hand tweaked configuration changes). 

The current experience is that you get a row that is mostly empty and breaks continuity in the dashboard results.

<img width="1780" alt="image" src="https://user-images.githubusercontent.com/3119513/79811147-d2b20000-8329-11ea-9f0a-19b78a0c2ea3.png">

Some ideas: 
- An argument can we pass to the CLI reference in the pipeline to attribute HLD pipeline with an existing `service`
- We can have an easy way to filter these "empty" rows out ( I realize we can filter by `service` but that isn't good enough)

As discussed in meeting 05/01: 
- [x] Add a filter dropdown that contains "Manual HLD Edits" and "Bedrock deployments" (wording to be discussed), and by default only "Bedrock deployments" should be selected when the page loads. The user can select both and have a view like the one we currently allow.
- [x] For rows that are manual HLD edits, under the ACR to HLD column (to be renamed), add the text "Manual HLD Edit" to indicate that HLD metadata was manually modified, which led to a build under HLD to manifest column. Use the same font and text as service / author cell.

**Comment by samiyaakhtar** [comment]
The changes needed to support better understanding of HLD change, as discussed in today's meeting: 
- Add a filter dropdown that contains "Manual HLD Edits" and "Bedrock deployments" (wording to be discussed), and by default only "Bedrock deployments" should be selected when the page loads. The user can select both and have a view like the one we currently allow. 
- For rows that are manual HLD edits, under the ACR to HLD column (to be renamed), add the text "Manual HLD Edit" to indicate that HLD metadata was manually modified, which led to a build under HLD to manifest column. Use the same font and text as service / author cell.
