### ISSUE TITLE
Explain how to upgrade CLI generated pipelines

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1386]
**As a:**
developer 

**I want:**
Know what changes I have to make to be existing `bedrock` generated pipelines to upgrade to the latest release 

**So that:**
I can take advantage of improvements in `bedrock`

**Describe the solution you'd like:**
Something like this might be good enough for the moment:

> 1. Download latest version of Bedrock CLI
> 2. Navigate to local cloned repo on the branch you’re working on
> 3. Rename `hld-lifecycle.yaml` to `hld-lifecycle.yaml.backup`
> 4. Run spk project init
> 5. Tweak newly created `hld-lifecycle.yaml` by comparing to `hld-lifecycle.yaml.backup`
> 6. Rename `build-update-hld.yaml` to `build-update-hld.yaml.backup` for service I want
> 7. Run `bedrock service create` for service I want (with the original options and flags used in the initial run)
> 8. Tweak newly created `build-update-hld.yaml` by comparing to `build-update-hld.yaml.backup`
> 9. Repeat steps 6,7, and 8 for any additional services
> 10. Git commit and push

**Acceptance Criteria:**
This documentation exists on the Bedrock CLI repo. I know how to update my application pipelines and `bedrock.yaml`

**Does this require updates to documentation?:**
Yes

**Comment by evanlouie** [comment]
documentation should be in service management guide.
