### ISSUE TITLE
Guidance on how to configure replicasCount for a service per ring

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1388]
**As a:**
developer 

**I want:**
Know how I can edit the `replicaCount` of a service in a particular [ring](https://github.com/microsoft/bedrock-cli/blob/master/guides/rings-101.md).

**So that:**
I can vary replica counts on a per service and ring basis

**Describe the solution you'd like:**
Documentation

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
I believe @mtarng has provided some guidance here. I've modified below:

A Helm chart needs to have a variable for replicas and that should tie to your deployment. An example `values.yaml` file:
<pre>
# This is a YAML-formatted file.

apiVersion: apps/v1
kind: Deployment

serviceName: fabrikam-service
majorVersion: v1

<b>replicaCount: 3</b>

(removed for brevity)
</pre>

You'll need that variable in the deployment template. For storage-service that's already done here: 

<pre>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  labels:
{{ include "fabrikam-service.labels" . | indent 4 }}
    app: {{ .Values.serviceName }}

spec:
  replicas: <b>{{ .Values.replicaCount }}</b>
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fabrikam-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ .Values.serviceName }}
</pre>

As bedrock.yaml does not support configurations per service and ring, you'll need to add the number of replicas you want for each ring and service combination in the HLD repository config. This can really be configured at any config level of the HLD. An example of doing this for fabrikam-service (fictional) in the master ring is here: 

<pre>
subcomponents:
  chart:
    config:
      image:
        repository: contoso.azurecr.io/fabrikam-service
        tag: master-20200422.1
      serviceName:fabrikam-service-master
     <b> replicaCount: 2</b>
</pre>

**Comment by evanlouie** [comment]
As high level context for doc: "How to customize your helm chart via fabrikate"

**Comment by mtarng** [comment]
Hm, do you think we need a specific guide on replicaCount, or is this more of a guide on "How to configure services per ring through manual editing of config files in the HLD repository, or by using fabrikate set"?

@evanlouie @andrebriggs

**Comment by evanlouie** [comment]
I think the context should be broad (e.g "how to configure services") but the example used in it should be of how to configure replicaCount
