### ISSUE TITLE
Dashboard missing data due to CLI generated pipelines rely on string matching

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1389]
**Describe the bug:**

Enabling a preview feature in AzDO changes the title of merged pull requests. This results in unexpected behavior for introspection features of Bedrock and the dashboard.

Below we can clearly see there is a reliance on string matching:
<pre>
- script: |-
      set -e
      cd "$HOME"/${MANIFEST_REPO##*/}
      commitId=$(Build.SourceVersion)
      commitId=$(echo "${commitId:0:7}")
      latest_commit=$(git rev-parse --short HEAD)
      url=$(git remote --verbose | grep origin | grep fetch | cut -f2 | cut -d' ' -f1)
      repourl=${url##*@}
      echo "Downloading SPK"
      curl https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh > build.sh
      chmod +x build.sh
      . ./build.sh --source-only
      get_spk_version
      download_spk
      message="$(Build.SourceVersionMessage)"
     <b> if [[ $message == *"Merged PR"* ]]; then</b>
      pr_id=$(echo $message | grep -oE '[0-9]+' | head -1 | sed -e 's/^0\+//')
      ./spk/spk deployment create -n $(INTROSPECTION_ACCOUNT_NAME) -k $(INTROSPECTION_ACCOUNT_KEY) -t $(INTROSPECTION_TABLE_NAME) -p $(INTROSPECTION_PARTITION_KEY) --p3 $(Build.BuildId) --hld-commit-id $commitId --manifest-commit-id $latest_commit --pr $pr_id --repository $repourl
      else
      ./spk/spk deployment create -n $(INTROSPECTION_ACCOUNT_NAME) -k $(INTROSPECTION_ACCOUNT_KEY) -t $(INTROSPECTION_TABLE_NAME) -p $(INTROSPECTION_PARTITION_KEY) --p3 $(Build.BuildId) --hld-commit-id $commitId --manifest-commit-id $latest_commit --repository $repourl
      fi
    displayName: 'If configured, update manifest pipeline details in Spektate db'
    condition: 'and(ne(variables[''INTROSPECTION_ACCOUNT_NAME''], ''''), ne(variables[''INTROSPECTION_ACCOUNT_KEY''], ''''),ne(variables[''INTROSPECTION_TABLE_NAME''], ''''),ne(variables[''INTROSPECTION_PARTITION_KEY''], ''''))'
</pre>

### The dashboard result:

![image](https://user-images.githubusercontent.com/3119513/80335151-4bbcc600-8808-11ea-96a2-611f80541e00.png)

**To Reproduce:**
Enable preview feature in AzDO. run pipelines, and then look at Spektate dashboard.

![image](https://user-images.githubusercontent.com/3119513/80335091-1f08ae80-8808-11ea-893d-07d9f4c793b5.png)

**Expected behavior:**
The dashboard should display the correct information.

**Comment by samiyaakhtar** [comment]
Reference: https://devblogs.microsoft.com/devops/introducing-the-new-pull-request-experience-for-azure-repos/#comment-1273
