### ISSUE TITLE
setup_bedrock_cli.sh Prereq Script Not Working

### ISSUE THREAD

**Issue by SignalRichard** [microsoft/bedrock#1390]
Running the script, `setup_bedrock_cli.sh` does not correctly download the bedrock CLI.  From a bit of debugging it appears that the line to set the `BEDROCK_CLI_VERSION` is not correclty finding the latest version.

The result is a file being put in `/usr/local/bin` called `bedrock` with the internal text "Not found".

This issue can be reproduced by following the steps in the prereqs README.md file to setup bedrock by running: `sudo ./setup_bedrock_cli.sh`

**Comment by andrebriggs** [comment]
Hi @SignalRichard, thanks for noting this. Please see if this [PR](https://github.com/microsoft/bedrock/pull/1391) resolves your issue

**Comment by SignalRichard** [comment]
Yep, issue is resolved.  Thank you!
