### ISSUE TITLE
bedrock service install-build-pipeline is not validating the correct pipeline definition value

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#1405]
**Describe the bug:**
bedrock service install-build-pipeline is not validating the correct pipeline definition value
**To Reproduce:**
```sh
bedrock service create azure-vote azure-vote-app --helm-config-git https://github.com/mtarng/helm-charts.git --helm-config-branch master --helm-config-path chart-source/azure-vote
git commit -am 'Adding azure-vote'
git push
spk service install-build-pipeline azure-vote
```
should succeed, instead we get:

```sh
error:   
code: 1000
message: service-install-build-pipeline-cmd-failed: Service install build pipeline was not successfully executed.
  code: 1100
  message: git-azure-file-no-exist-in-repo: File azure-vote/build-update-hld.yaml did not exist in master branch in repository fabrikam2019.
```

**Expected behavior:**

**Screenshots:**

**Additional context:**
https://github.com/microsoft/bedrock-cli/blob/master/src/commands/service/pipeline.ts#L199-L203
This block should look up the service path and not use the service name.

Follow up question, should we remove the flag for a "packages" directory?

**Does this require updates to documentation?:**
No. Documentation is accurate, but service-path isn't.

**Comment by mtarng** [comment]
Follow up question, should we remove the flag for a "packages" directory? We are currently passing the full path to the service when running `bedrock service create`, the packages path flag may cause confusion.

Thoughts @andrebriggs @evanlouie @bnookala

**Comment by bnookala** [comment]
@mtarng happy to remove it if it's not being used
