### ISSUE TITLE
Fabrikate generation needs to support multiple config

### ISSUE THREAD

**Issue by samiyaakhtar** [Microsoft/bedrock#141]
Currently we run `fab generate prod` but we need to support the possibility where they would need to pass us a config as env variable which we would need to generate, like `dev` or `test`

**Comment by andrebriggs** [comment]
One solution would be to accept multiple configurations via an environment variable in the CI/CD orchestration:

![image](https://user-images.githubusercontent.com/3119513/53738034-1a6e9180-3eb4-11e9-8b36-02643c8fd3c4.png)

Multiple configuration are delimited by commas. The build.sh file would parse and iterate over the env configurations.

I have an example of what the build.sh changes would look like [here](https://github.com/andrebriggs/bedrock/commit/1da324f910c8c63387a4483d84a4651831a04b8c)

Thoughts on this approach? 

cc @samiyaakhtar @yradsmikham @timfpark

**Comment by samiyaakhtar** [comment]
The approach sounds good to me, tested and verified it works well and we are making it backwards compatible according to the discussion today. I will make a PR soon
