### ISSUE TITLE
Pull request fails with Travis CI due to limitations on security

### ISSUE THREAD

**Issue by NathanielRose** [Microsoft/bedrock#144]
Pull requests sent from forked repositories do not have access to encrypted variables or data in Travis.
https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
Switch to AzDo or submit a work around.

**Comment by NathanielRose** [comment]
After some testing, the package manager I use to install terratest and other package modules for the testing suit require the dep golang package manager. The preview go pipeline does not come with dep pre-configured as TravisCI. Installation of dep is always tricky as using the apt-get requires 18.x for Ubuntu which Azure devops agents currently dont support (16.04) and the gopath /gobin are located in a temp [path](https://dev.azure.com/appserviceloadman/bedrockGO/_build/results?buildId=17&_a=summary)?

@dtzar curious to get your thoughts.

**Comment by dtzar** [comment]
This is now working via #199 at https://dev.azure.com/epicstuff/bedrock/_build?definitionId=54
