### ISSUE TITLE
Kubediff integration test

### ISSUE THREAD

**Issue by samiyaakhtar** [Microsoft/bedrock#145]
Moving from [here](https://github.com/Microsoft/bedrock/issues/90#issuecomment-464919761):

We should extend the [bedrock integration test](https://github.com/Microsoft/bedrock/blob/travis/testing/bedrock_azure_simple_test.go#L52) to include a verification that Kubediff is installed.

The first verification would be to check for the Kubediff namespace (that we should create if it's being installed to default). An example of this for flux is [here](https://github.com/Microsoft/bedrock/blob/4e5aad1b461216f30ff62ffc5d262be32e2fbd1b/testing/bedrock_azure_simple_test.go#L52). The method call appears to just write out to STDOUT. Will see if we plan to actually _assert_ on the result.

This is an extension to #8

**Comment by andrebriggs** [comment]
@samiyaakhtar can we close this?
