### ISSUE TITLE
Invalid length of admin password

### ISSUE THREAD

**Issue by amit1411** [microsoft/bedrock#1452]
containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="WindowsProfilePasswordInvalid" Message="Invalid adminPassword. Error: Length of password is invalid. Required length: [14, 123]. Minimum password length required by AKS for AzSecPack is longer. Please see https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/createorupdate#virtualmachinescalesetosprofile

**To Reproduce:**

Deploy the cluster using the bedrock templates

**Expected behavior:**

The cluster should be deployed

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by cannibal-kush** [comment]
I can confirm I am having this exact issue too :(

**Comment by amit1411** [comment]
> I can confirm I am having this exact issue too :(

For a workaround i changed the admin password to more than 14 characters in main.tf and it worked but yes a change in code needs to be done.

**Comment by timfpark** [comment]
I was able to repro this.  Looking at fix.

**Comment by timfpark** [comment]
Fixed in 3c74110207c095173fba42bfbb3ec0b82615a0b0.

**Comment by timfpark** [comment]
Windows profile block is now unnecessary, so removed it in 724861cb0a66084da788f562b7ad14801882ec7a
