### ISSUE TITLE
Use different cluster name for each region in multicluster template

### ISSUE THREAD

**Issue by timfpark** [Microsoft/bedrock#172]
Otherwise when folks try to merge all of the kube configs they can't switch between them because they all have the same name.

eg.  let's adjust

```
module "central_aks" {
...
   cluster_name             = "${var.cluster_name}"
```

to 

```
module "central_aks" {
...
   cluster_name             = "${var.cluster_name}-central"
```

and etc. for the other clusters.

**Comment by timfpark** [comment]
PR https://github.com/Microsoft/bedrock/pull/193 is out to fix this.

**Comment by jmspring** [comment]
PR merged and done.
