### ISSUE TITLE
Support for APIM and WAF deployment

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#183]
Across multi region we need support for setting up API Management and WAF. We need to be able to configure the APIs to be internal and external.  Ideally this would all be with Terraform

**Comment by NathanielRose** [comment]
API Management Terraform deployment (for Testing) now available:
- Through [Arm Resource Terraform Provider](https://github.com/Microsoft/bedrock/tree/api-mgmt/cluster/azure/api-mgmt-v2)
- Through [API Management Terraform Provider and Configuration Script](https://github.com/Microsoft/bedrock/tree/api-mgmt/cluster/environments/azure-api-mgmt)

**Comment by NathanielRose** [comment]
@jred55 I wanted to make sure WAF deployment was completed before we closed this issue, and if there was any feedback from the APIM terraform deployment options.

**Comment by NathanielRose** [comment]
New updates to APIM may simplify current terraform deployment - https://github.com/terraform-providers/terraform-provider-azurerm/pull/3151
Will need to explore changes

**Comment by jmspring** [comment]
Per the review on 5/8/2019, the following tasks were identified for the PR:

For Terraform:
- Consolidate modules into `cluster/azure`
  - `tm-waf`
  - `api-gateway`
- Leverage `azure-common`
- Add subnet for WAF into the existing VNet
  - Given `vnet_name`, one can add a `subnet` to an existing `vnet` without impacting the deployment that created the `vnet`
- For API Management, use the `ARM` template
  - Create issue for tracking API management TF provider and migrate away from ARM when possible
- Policy needs to be documented
- Tracking ticket/issue needed on how to test WAF

**Comment by NathanielRose** [comment]
WAF support completed, stale issue
