### ISSUE TITLE
Egress controlled routing to external geo-replicated endpoints

### ISSUE THREAD

**Issue by andrebriggs** [Microsoft/bedrock#186]
As an operator, if my cluster consumes a service from a georeplicated external source, my cluster should be able to ping a single egress controlled endpoint within my cluster which will automatically route the request to the nearest working endpoint.

- The egress endpoint should periodically do liveness probes to the available endpoints.
- The egress endpoint should be able to accept configurations for ordered/weighted usage of the available external endpoints.

![img_20190222_110226](https://user-images.githubusercontent.com/2081587/53264922-bc5ed480-3691-11e9-8c5a-c55c25dfc9a6.jpg)

https://github.com/CatalystCode/kubemalt/issues/43

**Comment by evanlouie** [comment]
Closed and resolved in https://github.com/evanlouie/fabrikate-external-services
