### ISSUE TITLE
Spike: Deploy a multi cluster version of Project Jackson

### ISSUE THREAD

**Issue by andrebriggs** [Microsoft/bedrock#188]
Determine the steps necessary to get a full reference app of Project Jackson running on multiple clusters that can be used an example.

- Domain name provision
- Setup of various repos (HLD, etc)
- Deploying Project Jackson by default in Bedrock (as a linked Fab definition)  
- All the Project Jackson logical setup for multi cluster

**Comment by andrebriggs** [comment]
@bnookala I believed your already did this, right?

**Comment by bnookala** [comment]
Yeah, we can close this.
