### ISSUE TITLE
Explore/document service principal permissions requirements

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#195]

**Comment by jmspring** [comment]
It is likely that certain deployment patterns will require owner level permissions for deployment.  One option might be to give an SP write permissions on the sub for roles.  This task should look at where owner is required and document the options.  

In most enterprise situations, engineers are likely going to have locked down permissions/limited access.

**Comment by jred55** [comment]
Closing as this appears to be done.

**Comment by jred55** [comment]
@jmspring
