### ISSUE TITLE
Build Dockerfile for project that includes tooling prereqs

### ISSUE THREAD

**Issue by ben-st** [Microsoft/bedrock#2]
is there a minimum terraform version required?

and have you considered providing  a docker container with binaries and scripts included?
If there is a need for this, i can send a PR.

All the best,

Benjamin

**Comment by timfpark** [comment]
That's a great idea - that would make it even easier for folks to get started - I'd love a PR for that.

**Comment by timfpark** [comment]
Sketch for how this could be implemented in a Dockerfile:

1. Start from base Alpine Linux image
2. Install Linux versions of all required tooling
3. Copy entire repo into Docker image as /bedrock.

User can then run image, cd to /bedrock, and use distribution immediately.

**Comment by ben-st** [comment]
hi @timfpark 
i pushed this one.
https://github.com/ben-st/bedrock/blob/Dockerfile/Dockerfile

but before the PR, how should we present the README?
User runs the image with bash and then starts the scripts or do you have something else in mind?
`docker run -it -e TF_VAR_grafana_admin_password="SECRETpass" microsoft/bedrock:latest /bin/bash`

**Comment by timfpark** [comment]
That Dockerfile looks great.  

Yes - for the README.md let's just go with something basic like that - I think for real deployments that they would actually want to start on this Dockerfile and derive a second one from it such that they could push a container with config like this (the grafana admin password) and probably their .kube/config to a private repo.  

Any strong thoughts on what you think is the right answer here?

**Comment by ben-st** [comment]
Baking in, the config is an option for private registries and we don't prevent anybody from doing so with the current Dockerfile, so all good :)
I think i would mount the config files as  i need them everytime i start the container.
What did you have in mind the first time you thought about it?

**Comment by ben-st** [comment]
PR is done ;)
i will update it with your improvements.
Thanks for the feedback

**Comment by timfpark** [comment]
Thanks again - merger!
