### ISSUE TITLE
Automate imagePullSecrets for private images for flux

### ISSUE THREAD

**Issue by samiyaakhtar** [Microsoft/bedrock#204]
Currently, when we use a private image for Project Jackson, we see that flux is able to deploy the clusters, but since it doesn't have access to the image itself, it can't poll changes to the image. This step is necessary in order to automate ACR image triggers for the gitops pipeline. 

- [ ] Deploy registry secrets for flux to have access to the ACR using an SP. We can reuse the SP that is being currently used. Given [this PR](https://github.com/weaveworks/flux/pull/1694), we should be able to configure flux to use the SP directly
- [ ] Provide guidance or SP creation command which includes ACR access as part of the SP. Since the terraform scripts don't create the SP for the user, it's not possible to grant access to the ACR after an SP has been created.

**Comment by timfpark** [comment]
@jmspring We should look at automating granting access to ACR (or at least documenting how to do it) such that the cluster has access when it spins up.

**Comment by jmspring** [comment]
@timfpark - this link describes options.  https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/container-registry/container-registry-auth-aks.md

**Comment by andrebriggs** [comment]
@samiyaakhtar do the instructions [here](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-aks#grant-aks-access-to-acr) help to unblock? Should be the same as what @jmspring linked.

**Comment by samiyaakhtar** [comment]
Yes, although this issue is related to flux having access to ACR, which is separate from AKS having access

**Comment by samiyaakhtar** [comment]
From more testing and quick discussion, we need to automate these on top of what we already have: 
1. Deploy registry secrets for flux to have access to the ACR using an SP. We can reuse the SP that is being currently used. (Flux uses `imagePullSecrets` to access the ACR and will not have access to it unless this secret is deployed, even if AKS has access. Without the secret, it's able to deploy the manifest but can't poll changes from registry)
2. Give this SP access to the ACR, which can be used by the AKS cluster too (and the above secret, which grants flux access to ACR)

**Comment by dtzar** [comment]
Second checkbox should be a new item on the backlog :)

**Comment by samiyaakhtar** [comment]
@dtzar Done #255
