### ISSUE TITLE
Ingress controllers should bind to terraform provisioned IPs

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#207]
Via terraform, bedrock should provision an IP address (with a corresponding dns label), to which an ingress controller will bind to within Kubernetes.

**Comment by sarath-p** [comment]
Currently, the dns label is derived from [ip address name with a "-dns" suffix](https://github.com/Microsoft/bedrock/blob/6e32991e956b6a1311d592f658e984d4aae2f63f/cluster/azure/tm-endpoint-ip/main.tf#L6) that we an make it configurable with a variable.

**Comment by bnookala** [comment]
Current status: istio ingress provisions its own public IP address within the aks resource group, and not the management resource group. Each ingress controller service should be configured with a pre-provisioned IP like so: https://docs.microsoft.com/en-us/azure/aks/static-ip#use-a-static-ip-address-outside-of-the-node-resource-group

**Comment by jred55** [comment]
Provided guidance via docs.ms.com link
