### ISSUE TITLE
Provision Traffic Manager profile per environment

### ISSUE THREAD

**Issue by bnookala** [Microsoft/bedrock#208]
Via terraform, we should provision a traffic manager profile that has endpoints identified by the IP addresses provisioned by #207

**Comment by sarath-p** [comment]
The traffic manager profile is created per environment with [Multiple AKS Clusters Deployment with Azure Traffic Manager](https://github.com/Microsoft/bedrock/tree/master/cluster/environments/azure-multiple-clusters) template. Are you using this template or a different one?
