### ISSUE TITLE
Distribute wildcard ssl certificate to clusters via keyvault

### ISSUE THREAD

**Issue by bnookala** [Microsoft/bedrock#209]
Currently, TLS secrets are deployed via kubernetes secrets, and kept within the cluster
https://istio.io/docs/tasks/traffic-management/secure-ingress/#configure-a-tls-ingress-gateway

We should distribute these via keyvault instead.

**Comment by jmspring** [comment]
@bnookala is this work dependent upon #225 ?

**Comment by bnookala** [comment]
@jmspring no, they're just related
