### ISSUE TITLE
Put together documentation on how the fabrikate + bedrock + cloud native stack and project jackson come together

### ISSUE THREAD

**Issue by evanlouie** [Microsoft/bedrock#214]
https://github.com/CatalystCode/kubemalt/issues/44

**Comment by evanlouie** [comment]
@timfpark whats the status of this ticket?

**Comment by evanlouie** [comment]
@timfpark @andrebriggs what do want done in regards to this?

**Comment by andrebriggs** [comment]
@evanlouie @bnookala https://github.com/Microsoft/bedrock/issues/140#issuecomment-474946426 

I'll create an Issue

**Comment by evanlouie** [comment]
Closing; stale.
