### ISSUE TITLE
Prometheus Node Health Alerting

### ISSUE THREAD

**Issue by evanlouie** [Microsoft/bedrock#216]
As an operator of my K8s cluster agents, I'd like to ensure that the cluster is healthy and be notified/alerted if something is broken or about to break.

This could mean Prometheus + Grafana provides alert rules and dashboards with configurable notifications going to social channel of choice.

There are already a ton of alert rules here for Prometheus which can be utilized without the Prometheus operator and links to relevant Grafana dashboards too from that article.
https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus

AC: Setup a working example of configuration for the cloud-native stack that sets up [alertmanager](https://prometheus.io/docs/alerting/configuration/) to send an email alert to an email injected via the HLD config. The metric can be any of your choosing (CPU usage to high, out of ram, error deploying pods, etc...)

**Comment by edaena** [comment]
I can take this one. I'm unable to assign it to myself though.

**Comment by mtarng** [comment]
@edaena you may need to join https://github.com/orgs/Microsoft/teams/bedrock-contributors

**Comment by edaena** [comment]
PR available here: https://github.com/timfpark/fabrikate-prometheus-grafana/pull/3/files
