### ISSUE TITLE
Cloud Monitoring: On Cluster Prometheus -> Azure Monitor

### ISSUE THREAD

**Issue by evanlouie** [Microsoft/bedrock#217]
As a operator, I want a working example of pushing metrics of Prometheus ot Azure Monitor so that I can utilize an Azure Monitor instance as means to monitor multi cluster deployments.

AC: documentation on how-to and limitations of pushing metrics from Prometheus to Azure Monitor. Store the docs in the KubeMalt Wiki.

**Comment by mtarng** [comment]
Wiki created [here](https://github.com/CatalystCode/kubemalt/wiki/Prometheus-Metrics-Exporting-to-Azure-Monitor). Will continue to update through creation of HLD/fabrikate and open sourced deployment version.
