### ISSUE TITLE
[Multiple clusters] "West" public IP address gets provisioned in the cluster resource group, not the management group

### ISSUE THREAD

**Issue by bnookala** [Microsoft/bedrock#218]
![Screen Shot 2019-03-18 at 4 44 44 PM](https://user-images.githubusercontent.com/87996/54570806-389cbd00-499d-11e9-8e7c-47a9767770ca.png)

See `jackson-prod-ip` above

**Comment by jmspring** [comment]
fixed previously, due to a typo
