### ISSUE TITLE
Migrate to Istio 1.1

### ISSUE THREAD

**Issue by timfpark** [Microsoft/bedrock#224]
Istio 1.1 was released, we should migrate fabrikate-istio to it.

https://istio.io/blog/2019/announcing-1.1/

@evanlouie

**Comment by dtzar** [comment]
We should ensure that the mixer subchart in the 1.1 install has the `useAdapterCRDs=false` set to turn off a [large chunk of the required config watches](https://github.com/istio/istio/pull/8356).
This switch to disable [will become the default in 1.2](https://github.com/istio/istio/issues/7675#issuecomment-432838799) and enables better performance for Istio overall and mitigates[ AKS-specific issues](https://github.com/Azure/AKS/issues/232).

**Comment by timfpark** [comment]
CC @jmspring - let's gate worrying about Istio perf / stability on resolving this issue.

**Comment by evanlouie** [comment]
upgraded in: https://github.com/evanlouie/fabrikate-istio/commit/674ead4c77da4cd761b5e39ab264e1276ab508dc
