### ISSUE TITLE
Promethus->AzureMonitor HLD

### ISSUE THREAD

**Issue by evanlouie** [Microsoft/bedrock#226]
As an operator I want an example HLD of a prometheus setup that would push some metrics to azure monitor so that I can have a general scaffold to adopt to my needs.

AC: An HLD (or documentation on how to) setup prometheus so that it will push either all or a subset of its metrics (whichever is easier) to an Azure Monitor instance.

**Comment by mtarng** [comment]
3 repositories created:

1. https://github.com/mtarng/prom2azure-private (holds code to prom2azure service. Needs to be scanned through Component Governance before we can release this as OSS)
2. https://github.com/mtarng/prometheus-to-azure-monitor (holds helm chart information)
3. https://github.com/mtarng/prom2azure-hld (fabrikate hld)

**Comment by mtarng** [comment]
Added new section to the wiki: https://github.com/CatalystCode/kubemalt/wiki/Prometheus-Metrics-Exporting-to-Azure-Monitor#fabrike-deployment

Also spent 2 days on a spike for Azure Keyvault env var injections without any results. May revisit in the future.
https://mrdevops.io/introducing-azure-key-vault-to-kubernetes-931f82364354
https://github.com/SparebankenVest/azure-key-vault-to-kubernetes
