### ISSUE TITLE
Enable turning on Flux garbage collection mode

### ISSUE THREAD

**Issue by timfpark** [microsoft/bedrock#228]
Flux has recently added the capability of removing obsolete resource manifests in addition to adding new ones.  

As an operator this fits better in my mental model for how Flux should work.  Let's dig into what this support means, understand its stability better, and either turn it on by default or provide instructions for how to turn it on.

https://github.com/weaveworks/flux/blob/1.11.0/site/garbagecollection.md

**Comment by andrebriggs** [comment]
Adding the services team to explore this as well. When thinking about gitops rollback scenarios (#152) having Flux remove resources it created is useful.

**Comment by andrebriggs** [comment]
Flux GC has been enabled for all templates. Closing
