### ISSUE TITLE
Cluster Level HLD

### ISSUE THREAD

**Issue by evanlouie** [Microsoft/bedrock#231]
As a Project Jackson operator, I want a working cluster level HLD which can be used to deploy my entire infrastructure and application stack so that I know all my in cluster infrastructure tooling works with my application.

AC: an HLD which uses the cloud-native stack and project jackson components as subcomponents and configures them so that the the application properly utilizes all the services made available from the cloud-native stack. The Jackson component should have a canary and stable deployment definition, an Istio virtual service traffic split between them, and a ConfigMap to configure it

**Comment by evanlouie** [comment]
@timfpark thoughts on any additional requirements?

**Comment by evanlouie** [comment]
@timfpark thoughts on any additional requirements?

**Comment by timfpark** [comment]
The cluster Fabrikate definition, should essentially be a definition of the common observability and other infrastructure and then links out, per Evan's proposal (https://github.com/evanlouie/gitops-promotion-workflow), to each of the microservices deployed in the cluster's Fabrikate definitions.

Each of the microservice definitions should probably look something like this:
https://github.com/timfpark/fabrikate-microservice

That assumes a Istio service mesh and that the app dev team wants to do a canary of the service, but those are great things to demonstrate.

**Comment by evanlouie** [comment]
@timfpark my proposed workflow is running somewhat counter to what @andrebriggs has been actively setting up for promotion workflows. Should we setup a working example using my proposed workflow in addition to @andrebriggs'?

**Comment by samiyaakhtar** [comment]
@evanlouie We created a fab definition for (strictly) Project Jackson [here](https://github.com/microsoft/fabrikate-entref-spring-boot) and this HLD would constitute the fab definition and cloud native/any other components?

**Comment by evanlouie** [comment]
done in: https://github.com/Microsoft/fabrikate-production-cluster-demo
