### ISSUE TITLE
Consolidate Fabrikate Definitions

### ISSUE THREAD

**Issue by evanlouie** [Microsoft/bedrock#236]
As a fabrikate user, I want fabrikate definitions to be in a more centralized/curated location so that I can have more confidence in the definitions I am using.

Having Fabrikate definitions live in wild where people could accidently delete or change repos makes the definitions quite fragile out of the box. I believe we should centralize them ala a chart repo. Thoughts?

**Comment by andrebriggs** [comment]
@evanlouie something similar to https://github.com/helm/charts but specifically for Bedrock Fabrikate definitions? Users of Bedrock could have their own consolidated repo.

**Comment by dtzar** [comment]
The helm charts repo is a great model to follow.  It allows for delegation/ownership of paths corresponding to charts --> fabrikate HLDs.  

I wouldn't say the repo is tied to bedrock, but just fabrikate.  i.e. People could use Fabrikate HLDs --> manifest repos with any GitOps setup which applies the manifests.

**Comment by evanlouie** [comment]
@andrebriggs yes something akin to the helm repos. My main concern is that all of the fabrikate components are currently living in our own GitHub accounts, but we are actively using them in prod deployments. I think this makes this fairly fragile as someone could make a breaking change to a component without anyone knowing.

This also brings up the question of some sort of version control for definitions, but I think a different/wider topic.

**Comment by andrebriggs** [comment]
I thought we already have an issue in Fabrikate about pinning to particular versions. If not we should create on. We already see issues with dependent items in a the cloud native stack incrementing dot releases daily.

**Comment by timfpark** [comment]
Fabrikate can already pin versions of a remote component as of this commit https://github.com/Microsoft/fabrikate/commit/52c8ed942e7792b3bab0e39e7e869442601f2a52

**Comment by edaena** [comment]
Here's a wiki with some of the ones that would need to be ported to the Fabrikate components repo:
https://github.com/CatalystCode/kubemalt/wiki/Fabrikate-Components

**Comment by evanlouie** [comment]
Closing: repo now at https://github.com/Microsoft/fabrikate-definitions/
