### ISSUE TITLE
Create project Jackson specific high level definition

### ISSUE THREAD

**Issue by andrebriggs** [Microsoft/bedrock#242]
Building upon what is mentioned [here](https://github.com/Microsoft/bedrock/issues/140#issuecomment-474946426)

- [x] Breakout the fab repo here to be strictly for cobalt/project jackson
- [x] Move the new repo to be part of the GitHub.com/Microsoft org

**Comment by samiyaakhtar** [comment]
Working on [this repo](https://github.com/samiyaakhtar/fabrikate-entref-spring-boot) as a starter for strictly project jackson fabrikate repo

**Comment by bnookala** [comment]
@andrebriggs @samiyaakhtar can we:

1. add the cloud native stack to this
2. create an azdo gitops pipeline to render the manifests to a target repository?

from there, we can push deployments to jack5on.io

**Comment by samiyaakhtar** [comment]
@bnookala did you mean something like [this](https://github.com/samiyaakhtar/jackson-source/blob/master/component.yaml)? This project is setup with the gitops pipeline and uses cloud native + project Jackson stack

**Comment by bnookala** [comment]
@samiyaakhtar sorry, i should clarify… it would be good to have https://github.com/microsoft/fabrikate-entref-spring-boot use the cloud-native stack, along with a gitops pipeline to render manifests to another git repository

**Comment by samiyaakhtar** [comment]
@bnookala Okay I get what you're looking for, so we will be creating a new one under microsoft github for this. This `fabrikate-entref-spring-boot` was intended to be strictly just project Jackson, the intention was to separate it out from cloud native. I'll work on a new one for what you're looking for

**Comment by bnookala** [comment]
@samiyaakhtar ah sorry - just spoke with @evanlouie, and he mentioned that we have a seperate ticket for the cloud native HLD + `fabrikate-entref-spring-boot`, that we are handling: https://github.com/Microsoft/bedrock/issues/231

**Comment by andrebriggs** [comment]
Closing given https://github.com/Microsoft/bedrock/issues/242#issuecomment-476373754
