### ISSUE TITLE
Operators should know where they are in the GitOps process

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#248]
An operator would like to know where in they are in the GitOps process. 

Some useful things to know would be:

- I want to see the git commit history for the HLD and manifest repos
  - Identify changes/rollbacks from on place
- I want to know the state of the CI/CD and statistics
  - Is a certain part of this taking a long time? I want to check from a single place instead of jumping around pages
- I want to know the state of Flux and control the checking intervals
  - Has flux checked yet? Has is applied changes yet?
- I want to know the state of kubediff and control the checking intervals
  - Did flux operate correctly?  What exactly is different? I can I see this without context switching or having to use kubectl all the time?
- I want to know if there was any failure during fabrikate generate for eg. some green/red lights show on this dashboard
- I want to visualize errors, for eg. if PAT expires or we need to notify them to regularly update it for security

**Comment by samiyaakhtar** [comment]
As I spend some time thinking and prototyping what this dashboard should look like and contain, we almost need to make sure we're able to do the following:
- [ ] Collect logs from azure pipelines to get the state of CI/CD
  - [ ] To get the ACR build progress
  - [ ] To get Fabrikate logs when generating manifest files
- [ ] Collect git logs from the Github/ADO api which will be used for viewing the HLD/app commits
- [ ] Prototype to verify we have at least one way to access logs from Kubernetes, using either of the following methods: 
  - [ ] A back end that collects Kubernetes logs for flux, kubediff (we could deploy a web service that collects logs from Kubernetes and exposes an endpoint for the dashboard)
  - [ ] A Kubernetes Javascript client such as [here](https://github.com/kubernetes-client/javascript)
- [ ] A personal access token has no expiry, so this will have to be stored in a service and suggested expiration set manually

**Comment by andrebriggs** [comment]
Being able to measure the end to end loop from application code change to getting your application on cluster(s) would be interesting. This could be possibly be Prometheus metric

**Comment by samiyaakhtar** [comment]
Here are some of the ideas that came across as a result of this spike and verified to make sure the APIs are tested and have the potential to be used in this upcoming feature. 

# Possible features

There's an option to provide a CLI experience for this, if not a visual dashboard. An operator/developer would be interested in seeing some of the following features on this dashboard/CLI:

## Pipeline progress display 

A progress display will be helpful in visualizing the current state of any active pipeline. This can be retrieved by checking if there’s any in progress pipelines in Azure DevOps, or the image tag picked up by flux does not match the one specified in HLD etc. Here’s an example below:

![image](https://user-images.githubusercontent.com/1795990/55996179-796db600-5c6b-11e9-8c63-67fecc22a4d4.png)

## Logs from Azure pipelines

The logs from these pipelines is crucial to know the state, progress and success of the pipeline. The API [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get%20build%20logs?view=azure-devops-rest-5.0) can help access these logs. 

![image](https://user-images.githubusercontent.com/1795990/55996335-f6009480-5c6b-11e9-9cc3-94ad7a066884.png)

## State of environments

Describe the current state of each environment (such as dev, QA, staging, prod), their image tags, any in-progress releases, to visualize where each environment is at. This should help the operator visualize if any environment needs to be approved for another release.

## Kubernetes logs 

Get logs from flux and pods running on the cluster to help debug any ongoing issues with deployment or failures in flux. There’s a [Kubernetes client](https://github.com/kubernetes-client/python) available in Python and JavaScript which is useful for getting any pod specific information.

![image](https://user-images.githubusercontent.com/1795990/55996563-99ea4000-5c6c-11e9-9096-681d1bece6ed.png)

## Audit logs

The operator would like to know details about who kicked off releases and when, along with information on commits that have been included in the deployed images along with their author information. This information is available via the [GitHub](https://developer.github.com/v3/repos/commits/#get-a-single-commit)
) and [Azure DevOps](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/commits/get%20commits?view=azure-devops-rest-5.0) APIs.

**Comment by andrebriggs** [comment]
@samiyaakhtar can you create a short one pager with some ideas for what a CLI experience would look like?

**Comment by andrebriggs** [comment]
An alternative/complementary approach to tell `flux` status is to look at the the `--git-sync-tag` that flux sets on our manifest repo. For instance 
![image](https://user-images.githubusercontent.com/3119513/56933385-6d238e80-6a9c-11e9-919a-a7b1a3a4560e.png)

A `commit id` referenced in the tag matches the commit id in the repo to let you know it synced

![image](https://user-images.githubusercontent.com/3119513/56933584-55003f00-6a9d-11e9-9590-892aad2f2363.png)

By default the tag is `flux-sync` but can be alter (see [docs](https://github.com/weaveworks/flux/blob/master/site/daemon.md))

cc @yradsmikham @samiyaakhtar

**Comment by andrebriggs** [comment]
Related repo: https://github.com/microsoft/spektate

**Comment by andrebriggs** [comment]
Closing
