### ISSUE TITLE
Ensure SP has access to private ACR

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#255]
**Describe the bug:** Provide guidance or SP create command which includes ACR access as part of the SP. Since the terraform scripts currently don't create the SP for the user, it's not possible to grant access to the ACR after an SP has been created.

**Comment by andrebriggs** [comment]
@samiyaakhtar is this still an issue?

**Comment by samiyaakhtar** [comment]
I think so, the documentation [here](https://github.com/Microsoft/bedrock/tree/master/cluster/azure#create-an-azure-service-principal) does not include the part about access to the ACR, which is needed by flux to poll the latest image if it receives an update. However, if it does not have access, flux will not show errors. Since we can't script to grant access to the ACR, maybe we just need to update this documentation?

**Comment by andrebriggs** [comment]
@samiyaakhtar yes let's just update the documentation
