### ISSUE TITLE
Flux fails with lstat /tmp/flux-working076343399/-s: no such file or directory

### ISSUE THREAD

**Issue by timfpark** [Microsoft/bedrock#260]
**Describe the bug:**

After creating a cluster, flux starts but immediately runs into a problem with logs that look like this:

```
ts=2019-03-24T02:28:16.577277288Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: walking \"/tmp/flux-working012153773/-s\" for yamels: lstat /tmp/flux-working012153773/-s: no such file or directory"
ts=2019-03-24T02:28:35.771627762Z caller=loop.go:92 component=sync-loop err="loading resources from repo: walking \"/tmp/flux-working976942888/-s\" for yamels: lstat /tmp/flux-working976942888/-s: no such file or directory"
ts=2019-03-24T02:28:35.772966461Z caller=loop.go:105 component=sync-loop event=refreshed url=git@github.com:timfpark/rhom-resource-manifests.git branch=master HEAD=582ede9b3b6ee70d29401230e99a4ddb92e06a7d
ts=2019-03-24T02:29:16.966338803Z caller=images.go:17 component=sync-loop msg="polling images"
ts=2019-03-24T02:29:16.995389768Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: walking \"/tmp/flux-working076343399/-s\" for yamels: lstat /tmp/flux-working076343399/-s: no such file or directory"
ts=2019-03-24T02:30:16.928327747Z caller=images.go:17 component=sync-loop msg="polling images"
ts=2019-03-24T02:30:16.953397217Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: walking \"/tmp/flux-working147238554/-s\" for yamels: lstat /tmp/flux-working147238554/-s: no such file or directory"
ts=2019-03-24T02:31:15.951970614Z caller=images.go:17 component=sync-loop msg="polling images"
ts=2019-03-24T02:31:15.977193884Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: walking \"/tmp/flux-working757723953/-s\" for yamels: lstat /tmp/flux-working757723953/-s: no such file or directory"
ts=2019-03-24T02:32:16.318187378Z caller=images.go:17 component=sync-loop msg="polling images"
ts=2019-03-24T02:32:16.347189544Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: walking \"/tmp/flux-working265530076/-s\" for yamels: lstat /tmp/flux-working265530076/-s: no such file or directory"
ts=2019-03-24T02:33:16.617364508Z caller=images.go:17 component=sync-loop msg="polling images"
```

**To Reproduce:**

I believe this is reproducible using the `azure-advanced` environment on master.

**Additional context:**

Logs from my flux:
[flux.log](https://github.com/Microsoft/bedrock/files/3000010/flux.log)

**Comment by andrebriggs** [comment]
I can confirm the same for `azure-simple` as well

**Comment by andrebriggs** [comment]
@timfpark what do you have set for your `gitops_path` in `terraform.tfvars`?

In my `terraform.tfvars` file for my custom environment had an empty string for **gitops_path** --> `gitops_path = ""`

This caused the helm chart templating to set  **-s** as the value. I temporarily got around this issue by commenting out in the `--git-path` setting (see below). This file should be in your /bedrock/cluster/environments/(CUSTOM_ENV_NAME)/(GENERATED_ENV_NAME)/flux/chart/flux/manifests/flux/templates/deployment.yaml path:

         args:
          - --ssh-keygen-dir=/var/fluxd/keygen
          - --k8s-secret-name=flux-ssh
          - --memcached-hostname=flux-memcached
          - --memcached-service=
          - --git-url=git@github.com:andrebriggs/go-server-manifests.git
          - --git-branch=master
          #- --git-path=-s
          - --git-user=Weave Flux
          - --git-email=support@weave.works
          - --git-set-author=false
          - --git-poll-interval=5m
          - --git-timeout=20s
          - --sync-interval=5m
          - --git-ci-skip=false
          - --registry-poll-interval=5m
          - --registry-rps=200
          - --registry-burst=125
          - --registry-trace=false

I will have to test later but I believe this is caused when `var.gitops_path` is an empty string it takes the `-s` flag for `var.acr_enabled` as an argument. Hence  `--git-path`  value is `-s` CC @samiyaakhtar 

This happens in the [main.tf](https://github.com/Microsoft/bedrock/blob/ef447bdd0d6af3e048646fe8f44f5df61fd2b6c0/cluster/common/flux/main.tf#L9) file for flux:
`... -e ${var.gitops_path} -s ${var.acr_enabled}"`

The easier hack to unblock may be to switch the order to `... -s ${var.acr_enabled} -e ${var.gitops_path} "` if your `gitops_path` value is an empty string

@yradsmikham @dtzar How sure are we that we should be using "/" as a [default value](https://github.com/Microsoft/bedrock/pull/190#discussion_r266662636)? The Flux code [seems to throw an error](https://github.com/weaveworks/flux/blob/267e0115d1a2a74956c94d37e844ffa531ce9f9c/cmd/fluxd/main.go#L202) if you start with "/" for the gitops_path parameter.

I noticed in `azure-advanced` we set a default value of **"/"** in [variables.tf](https://github.com/Microsoft/bedrock/pull/227/files) however in `azure-simple` we have **""** as the default value in [variables.tf](https://github.com/Microsoft/bedrock/pull/190/files).

**Comment by timfpark** [comment]
Yes, likewise I have an empty string for `gitops_path` and like @andrebriggs I found that using "/" caused Flux to fail with the same error.

**Comment by timfpark** [comment]
Confirmed that removing `--set git.path=$GITOPS_PATH` from the arguments to Flux solves this.  Perhaps we can solve this by quoting the path above (ala `--set git.path="$GITOPS_PATH"`) such that it doesn't treat the next flag as the argument.

**Comment by samiyaakhtar** [comment]
Very interesting find. It now explains why it was working when it was the last variable being sent in, but when it's not, it breaks flux. @yradsmikham and I will take a look at this first thing in the morning!

**Comment by dtzar** [comment]
The `/` for gitops path was only a suggestion on the PR to enable this switch so there was a default value instead of empty string (I was concerned there would be issues back then), but I didn't test this value.  Maybe `\` would work?

**Comment by yradsmikham** [comment]
@sarath-p and I had stumbled upon this error a little while back, which is why we removed the default for `gitops_path` and had moved it as the last variable that is set.

Obviously this becomes a little more complicated when additional variables are involved. Looking into this now!

**Comment by yradsmikham** [comment]
https://github.com/Microsoft/bedrock/pull/264
