### ISSUE TITLE
Move documentation for three levels of deployment options  - Azure Simple, multi-cluster, cluster with KeyVault to Bedrock main page

### ISSUE THREAD

**Issue by jred55** [Microsoft/bedrock#267]
**As a:** Operator

**I want:**
Bedrock main page documentation give a clear guidance on various flavors of clusters that can be deployed using Bedrock 
**So that:**
I have clear guidance on which option I can choose
**Describe the solution you'd like:**
Improve getting started guide
**Describe alternatives you've considered:**

**Additional context:**

**Comment by jmspring** [comment]
The main page links to the two easiest to get started, since we will support multiple providers, the specific providers each list and describe the possible combinations.
