### ISSUE TITLE
Add covering test for azure-advanced

### ISSUE THREAD

**Issue by timfpark** [Microsoft/bedrock#272]
As a developer, I want to have confidence that the changes I am making to the azure-advanced environment (or the test itself) are covered by an integration test that creates and deletes this environment that can run on both my development machine and as part of each commit in our CI/CD environment.

**Comment by NathanielRose** [comment]
#250 Will also close with completion of this issue.

**Comment by timfpark** [comment]
Closing this one and consolidating with #250.
