### ISSUE TITLE
Configure Cloud-Native tracing with Istio 1.1

### ISSUE THREAD

**Issue by evanlouie** [Microsoft/bedrock#276]
**As a:** Operator

**I want:** service calls between services hosted within the istio mesh to be surfaceable in Jaeger.

**So that:** I can gain insight into the performance of my microservices and highlight any bottlenecks.

**Describe the solution you'd like:** Now that the cloud-native stack uses istio 1.1, Configure the `common.yaml` file in the the cloud-native stack to pass configuration to the istio component to make distributed tracing work for all in-mesh services.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by bnookala** [comment]
If this PR gets merged, Jaeger (deployed via istio) will be able to push spans to an existing ES cluster. which should solve some of our issues: https://github.com/istio/istio/pull/13331

**Comment by bnookala** [comment]
https://github.com/timfpark/fabrikate-cloud-native/pull/14

**Comment by evanlouie** [comment]
closed: https://github.com/Microsoft/fabrikate-definitions/pull/1
