### ISSUE TITLE
As a developer I want to deploy BookInfo app with multi-level cluster, Keyvault and Istio Service Mesh 

### ISSUE THREAD

**Issue by jred55** [Microsoft/bedrock#277]
**As a:**

**I want:**

**So that:**
I can demonstrate the end-to-end enterprise scenario of having 

Multi cluster deployment 
Keyvault capability 
Service Mesh Istio enabled 
BookInfo app deployed 

and any documentation to go with this setup. 

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by bnookala** [comment]
@evanlouie see: https://github.com/Microsoft/fabrikate-production-cluster-demo

**Comment by evanlouie** [comment]
closed by https://github.com/Microsoft/fabrikate-production-cluster-demo/pull/15
