### ISSUE TITLE
CI/CI that publishes Fabrikate artifacts

### ISSUE THREAD

**Issue by andrebriggs** [Microsoft/bedrock#28]
Related to #27 we need to take the generated yam artifacts and git commit/push this files to a source of truth repo. For the moment we may be able to utilize the Azure Pipelines GitHub App to authenticate the git push command.

**Comment by yradsmikham** [comment]
Shell script in Azure Pipeline build downloads, installs and executes Fabrikate. The Fabrikate artifacts are published to destination git repo.
