### ISSUE TITLE
Migrate multiple cluster to utilize common template

### ISSUE THREAD

**Issue by jmspring** [Microsoft/bedrock#283]

**Comment by timfpark** [comment]
As an operator, I want to utilize a common cluster creation module so that changes to this are centralized. 

An example of this work is in https://github.com/Microsoft/bedrock/blob/master/cluster/environments/azure-single-keyvault/main.tf

**Comment by jmspring** [comment]
As part of the PR, work should include modifying/updating the tests appropriately.
