### ISSUE TITLE
Handle Kubernetes upgrades

### ISSUE THREAD

**Issue by timfpark** [Microsoft/bedrock#304]
In an operations role, I would like to be able to upgrade my cluster from Kubernetes version to Kubernetes version.  Investigate what the best approach is for doing this is.

**Comment by jmspring** [comment]
I need to do a test of a totally functional live site, but changing `kubernetes_version` performs in the same manner as doing a version upgrade from the az-cli.  IF one were to do an upgrade mixing TF and CLI, the TFState would become invalid.

Recommendation would be:
- figure the best manner to plumb the Kubernetes version through that there is a valid default, but also the person managing the cluster can control the version.
