### ISSUE TITLE
Remove vnet_subnet_id from inputs to clusters

### ISSUE THREAD

**Issue by timfpark** [microsoft/bedrock#310]
As an operator, I don't want to have to specify inputs multiple times.  In the current cluster specs, there is a `vnet_subnet_id` that is complex and composed of multiple subcomponents that we already have, including `subscription_id`, `common_resource_group`, `vnet_name`, and `subnet_name`.  

Remove this separate definition and build it up internally to the module instead.

**Comment by jmspring** [comment]
@timfpark - in `azure-simple`, there is sufficient information to construct this value.  in `azure-single-keyvault`, as the vnet is created with `azure-common-infra`, there is not.

In `azure-single-keyvault`, the checked in `terraform.tfvars` file has extraneous values that are not used.

I think it makes more sense to have the inputs be the values you specify above and rework things accordingly.

Thoughts?

**Comment by jmspring** [comment]
This is no longer valid.  We use a vnet/subnet name / data source rather than the id.
