### ISSUE TITLE
Author name in commits for auditing

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#314]
**As an operator** I'd like the commit to come from the author who initiated the build/release rather than from an automated account

**Describe the solution you'd like:** Would be nice to see the commit being linked to the actual github user who commited a change, but since this requires personal access tokens, at least having their name instead of automated account may be sufficient for now

**Additional context:** While demoing the gitops workflow at the dashboard design meeting we got feedback for this feature on being asked why we use the term "Automated Account" and not the name of the user account. The more GitOps way to go about it is to have actual author information included in the commits.

**Comment by samiyaakhtar** [comment]
Opened [issue](https://github.com/MicrosoftDocs/vsts-docs/issues/3923) with vsts as their build variables aren't providing the author name we need in order to accomplish this.

**Comment by andrebriggs** [comment]
@samiyaakhtar is this still an issue?

**Comment by samiyaakhtar** [comment]
@andrebriggs no, this has been resolved. Closing
