### ISSUE TITLE
As a developer, I want to setup a base docker image for terraform unit and integration testing

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#318]
Based on [Cobalt/#55](https://github.com/Microsoft/cobalt/issues/55)
As a developer, I want to setup a docker image base for terraform unit and integration testing
Terraform unit and integration test modules will be written in GoLang. The goal of this feature is automating the pre-requisite installation steps and provide a base docker image that installs:

Go programming language: Terraform test cases are written in Go.
dep: dep is a dependency management tool for Go.
Azure CLI
mage: simplifies running Terratest cases.
Acceptance Criteria
- [x] Should assert that I can build the image successfully on both a windows and mac machine.
- [x] Should assert that go, terraform, azure cli, dep and mage are installed when ssh'd into the container docker run -it $(IMAGE_NAME) /bin/sh
- [x] Should assert that the image is pushed to a public docker registry
- [x]  Pair with @erikschlegel and verify that this image will work for bedrock unit and integration tests.
- [ ] Should add the Dockerfile to the root of the test directory
- [x] Should assert that both the terraform and golang versions are docker arguments.
- [x] Should update the README in the tests directory on sample docker usage.

Resources
Mockups
Screenshots of the golang, terraform, azure cli and mage versions printed out when ssh'd into the docker container.

Tasks
Add a baseline Dockerfile as per the above story details.
Push docker image to a public / central docker registry.
Update README in tests

**Comment by NathanielRose** [comment]
Dual partnership with cobalt for building base image and setup script. For monitoring progress view [Cobalt:#81](https://github.com/microsoft/cobalt/pull/81)

**Comment by NathanielRose** [comment]
Will need bedrock custom image to ensure helm and kubectl are installed in base image

**Comment by andrebriggs** [comment]
@NathanielRose can we close this?

**Comment by NathanielRose** [comment]
Closed with #439
