### ISSUE TITLE
Investigate automation to update keys on repo after they periodically expire

### ISSUE THREAD

**Issue by samiyaakhtar** [Microsoft/bedrock#32]
We're planning to use deploy keys for flux and ssh keys for pushing to the second repo from a script, but we would like to refresh these keys periodically and when we do that, it would need to be automatically updated on the github repo via a script. Explore the options for automating it (see github API)

**Comment by andrebriggs** [comment]
@samiyaakhtar given that we are using PAT do you think can close this issue and reopen if needed?

**Comment by samiyaakhtar** [comment]
Closing issue for now since we're sticking to PAT
