### ISSUE TITLE
Remove (gitignore) .tfvars files in the repo

### ISSUE THREAD

**Issue by sarath-p** [microsoft/bedrock#322]
As a developer, it is preferable to gitignore _.tfvars_ files so configurations will not be pushed to the repo by mistake and saves undo with commits and push.

**Comment by timfpark** [comment]
It also sounded like from our previous discussion that you were proposing that we remove the current .tfvars files from our environments since this is the idiomatic way people share Terraform scripts (without .tfvars files).  Is that right?

**Comment by sarath-p** [comment]
That is correct. It will not expose secrets by mistake and also saves time without having to undo config values in tfvars when pushing changes.

The downside of it is everyone needs to keep a local copy of the .tfvars file with values based on the input variables. 

The other option is to break current tfvars file into two. One local tfvars file for secrets like ssh keys, service principal, etc. Second tfvars file is for general cluster configuration that can be shared with others in the repo as described [here](https://learn.hashicorp.com/terraform/getting-started/variables.html#assigning-variables).

+ @jmspring, @dtzar, and @NathanielRose to comment.

**Comment by dtzar** [comment]
We already have this in `.gitignore` [here](https://github.com/Microsoft/bedrock/blob/a82117c96a033df0a398ca27bcb84d374b52a0f6/.gitignore#L7).

**Comment by jmspring** [comment]
I am of the opinion that having a skeleton terraform.tfvars is work having (commented, concise) so that people have an easy place to get started.  Going through the docs or manually entering each requested value when prompted by terraform will make the initial experience more difficult.

Note, there is a difference between individual tfvar files that one is using for deployment and having a skeleton where people start from.

I believe the skeleton should be there.

**Comment by jmspring** [comment]
Further - if you use `-var-file=...`, by default `terraform` ignores tfvars in the directory one is doing the init/plan.

**Comment by sarath-p** [comment]
> We already have this in `.gitignore` [here](https://github.com/Microsoft/bedrock/blob/a82117c96a033df0a398ca27bcb84d374b52a0f6/.gitignore#L7).

It seems .gitignore is overwritten somewhere in the configuration since it is tracked in the changes.

**Comment by andrebriggs** [comment]
@sarath-p can we close this?

**Comment by sarath-p** [comment]
@andrebriggs - sure, closing it.
