### ISSUE TITLE
More Aggressive Labelling of Issues

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#327]
In order to surface cross-team collaboration points within the backlog, leads are to try and enforce more heavy/aggressive usage of labels on issues.

If a label doesn't exist which you think is relevant, add it.

- All issues should have be tagged with one of the `effort` tags (we now have 5 ranging from `effort - XS` to `effort - XL`)
- Be liberal with tagging, we want to facilitate and surface cross team collaboration points

**Comment by andrebriggs** [comment]
@evanlouie I think we have been doing this. Close?
