### ISSUE TITLE
Write up an FAQ for commonly asked questions and frequently encountered issues

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#328]
**As a developer** who is looking at Bedrock from a fresh perspective, there's a lot of questions that are not answered directly by our docs. 

When we had some hacks with customers or explained the project to folks from other teams, there were questions that always popped up, such as what's the point of using an HLD or adding the complexity of an extra repo in the middle. A lot of technical troubleshooting questions also seem to be repeated by those who are trying to run this project, and all these can be addressed in a single FAQ which makes searching easy. A good sample is [here](https://github.com/weaveworks/flux/blob/master/site/faq.md).

**Describe the solution you'd like**: Ideally it would be nice for any of us who runs into an issue and then ends up solving it, to go ahead and add the solution to the FAQ if it's not already there, once we're done making a simple starting point for everyone to contribute to.

**Comment by jred55** [comment]
One way to do this is to use Wiki https://github.com/Microsoft/bedrock/wiki page for the project. I came across a good FAQ at this location we can model after https://github.com/Microsoft/TypeScript/wiki/FAQ

**Comment by samiyaakhtar** [comment]
@jred55 Working on this one here: https://github.com/Microsoft/bedrock/wiki/FAQ 

I'm wondering if we almost need to split up technical faq from faq now! There's going to be a lot of technical issues to list here.

**Comment by jred55** [comment]
@samiyaakhtar we could split. Can we also get Table of contents since I anticipate this list of FAQ to get long..

**Comment by andrebriggs** [comment]
@samiyaakhtar I updated your TOC changes and used this tool to generate: https://github.com/ekalinin/github-markdown-toc

**Comment by andrebriggs** [comment]
@samiyaakhtar one other thing we can do is link to the FAQ page from the main page in the [Community section](https://github.com/Microsoft/bedrock#community) perhaps? This way we can drive traffic to the FAQ and wiki. Thoughts?
