### ISSUE TITLE
Expose flux branch variable as part of tf scripts

### ISSUE THREAD

**Issue by samiyaakhtar** [Microsoft/bedrock#354]
**As a developer:** I would like to modify the branch flux is pointing to without having to manually modifying the flux deployment after it's complete

**Additional context:** During the mini-hack on blue green deployments and further testing I'm running into several scenarios where this would be useful to have, especially because we expose `git-poll-interval` and `git-path` from flux in our tf scripts

**Comment by samiyaakhtar** [comment]
Already available in [azure-single-keyvault](https://github.com/Microsoft/bedrock/blob/master/cluster/environments/azure-single-keyvault/terraform.tfvars#L19), provide the option in other environments possibly? @andrebriggs @yradsmikham

**Comment by andrebriggs** [comment]
@samiyaakhtar Sounds reasonable
