### ISSUE TITLE
Add tags to all modules

### ISSUE THREAD

**Issue by code4clouds** [microsoft/bedrock#355]
**As a:** Developer using Bedrock modules from Cobalt

**I want:** to be able to use tags on all Bedrock modules referenced

**So that:** I can "tag"and list the resources when query the environment.

**Describe the solution you'd like:**
Add a consistent variable and expose either resource_tags (i.e api-mgmt) or tags (i.e. vnet) for all Bedrock modules using the variables.tf file in their directory. 

**Describe alternatives you've considered:**

**Additional context:**

**Comment by andrebriggs** [comment]
I’m looking from my phone but I thought we have this now? If not it seems fairly easy to add in the most used templates. Agree? @jmspring @NathanielRose

**Comment by jmspring** [comment]
@andrebriggs - tags are missing from a few modules - including azure/aks, so this is still valid.
