### ISSUE TITLE
Investigate using Octopus for GitOps orchestration

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#358]
Some getting started help on Azure here: https://ms.portal.azure.com/#blade/Microsoft_Azure_Marketplace/GalleryFeaturedMenuItemBlade/selectedMenuItemId/home/resetMenuId/

Related to #356

**Comment by yradsmikham** [comment]
The following items will be completed as part of this sprint issue:

- [ ] Research how Octopus Deploy can fit into the GitOps workflow
- [ ] Learn to use Octopus Deploy and create a working pipeline that fits in our GitOps workflow
- [ ] Documentation

**Comment by yradsmikham** [comment]
Have researched Github triggers, and currently the best option appears to be using scheduled deployments in Octopus Deploy. In addition, there is no support to build custom plugins/extensions with Octopus.

**Comment by andrebriggs** [comment]
@yradsmikham closing this based on #409
