### ISSUE TITLE
Quick updating of the git repository Flux uses on a cluster 

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#361]
As a developer I want to quickly switch the git repository Flux uses on my cluster(s) after deployment so that my development velocity is increased.

Right now if I have another git repository that I would like to use for my manifest repository instead of what was originally configured via Bedrock terraform scripts I must go through a difficult process of exporting the deployment yaml for Flux on all my clusters, editing the public and private SSH keys then re-apply the deployment all all clusters.

For many it might be easier to just create a new cluster which can be wasteful of resources and time consuming.

Something as simple as a script or CLI tool to allow hot-swapping of the manifest repositories on one to all clusters might be useful.

**Comment by samiyaakhtar** [comment]
Sounds like a good idea, we need the same for swapping flux secrets as well.

**Comment by andrebriggs** [comment]
After some exploring the most straightforward way to control flux is to use `fluxctl`. The more difficult yet precise method is it use `kubectl patch` commands to get explicitly change a container arg on the flux deployment. Closing this issue
