### ISSUE TITLE
Integration tests use current repo source tf modules instead of local source cause build failures

### ISSUE THREAD

**Issue by NathanielRose** [Microsoft/bedrock#364]
Builds are currently failing when new changes to the tf module source path
For eg, we’re using `source = "github.com/Microsoft/bedrock/cluster/azure/aks-gitops"` vs `source = "../../azure/aks-gitops"`

Build example:
https://dev.azure.com/epicstuff/bedrock/_build/results?buildId=3080

**Comment by sarath-p** [comment]
duplicate of https://github.com/Microsoft/bedrock/issues/293

**Comment by NathanielRose** [comment]
Closing issue (Duplicate)
