### ISSUE TITLE
Jaeger dashboard not displaying traces

### ISSUE THREAD

**Issue by andrebriggs** [Microsoft/bedrock#37]
Commit #21 fixed the Jaeger UI not showing up but no services show up in the UI. The correct way to pull the Istio based Jaeger UI is 
```
kubectl port-forward -n istio-system $(kubectl get pod -n istio-system -l app=jaeger -o jsonpath='{.items[0].metadata.name}') 16686:16686 &
```
As referenced [here](https://istio.io/docs/tasks/telemetry/distributed-tracing/#accessing-the-dashboard). 

After making this change I see a trace from the simple-service application with custom user-agent referenced. I only see one reference. This could be due to how tracing is implemented in [simple-service](https://github.com/timfpark/simple-service/blob/master/server.js). I'm going to investigate further to try other jaeger-client operations.

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/3119513/51458083-c8f5b300-1d08-11e9-9288-e73fd6325b17.png">

**Comment by timfpark** [comment]
Given that we have switched to a new mechanism for deploying Jaeger, should we close and reopen if we see it with that?
