### ISSUE TITLE
Investigate container promotion with Octopus

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#371]
As a developer I would like to see an example of an augmentation pipeline using Octopus. Similar to #356

**Comment by yradsmikham** [comment]
Octopus Deploy supports the concept of having different environments (e.g. Dev, QA, etc.). For this issue,  an Image Tag Release pipeline was tested and documented [here](https://github.com/yradsmikham/bedrock/blob/octopus-image-tag-release/gitops/octopus/ImageTagRelease.md). This pipeline is an "add-on" to the manifest generation pipeline.
