### ISSUE TITLE
Release pipeline is checking in components and helm_repos

### ISSUE THREAD

**Issue by timfpark** [Microsoft/bedrock#373]
With Azure Devops, when you setup and run a release pipeline, the release.sh script executes a `fab install` on the Fabrikate definition you are operating on with `fab set`.  When the release pipeline goes to try to check this Fabrikate definition in (usually with an image tag change etc.) it also seems to check in the components and helm_repos that were downloaded in the process because it is doing a `git add .` to gather the files that it should check in.

Screenshot of this happening: 
<img width="1000" alt="Screen Shot 2019-04-29 at 3 38 01 PM" src="https://user-images.githubusercontent.com/712001/56931550-339b5500-6a95-11e9-875e-1d5b63838772.png">

It seems like this could be resolved by simply skipping the `fab install` during the script.  (`fab set` does not need that in order to operate on the Fabrikate definition anyway.)

**Comment by andrebriggs** [comment]
This was addressed in #368
