### ISSUE TITLE
Integrate release pipeline with manifest generation in GitOps documentation

### ISSUE THREAD

**Issue by timfpark** [Microsoft/bedrock#376]
As a newcomer to the project, I would like an end to end explanation for how I should set up a GitOps pipeline for my project.  We do a great job of that right now in terms of explaining how to set up manifest generation and have documentation for how to set up a release pipeline connected to our container build CI/CD pipeline but it is not connected into the rest of the documentation.

**Comment by andrebriggs** [comment]
This was addressed in #368.
