### ISSUE TITLE
implement / deploy Kubernetes based chaos

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#39]
Allow for the deployment of a Kubernetes / pod level chaos solution.

Implementation should include documenting available tests as well as implementing knobs to enable/disable tests.

- [x] Implement Pod level chaos testing
- [x] Implement latency injection istio fabrikate HDL
- [x] Implement Fabrikate component for chaos stack
- [x] Add Documentation for fabrikate component

**Comment by shwetams** [comment]
1. Implement Pod Level Chaos

**Comment by munishm** [comment]
fabrikate HLD is available at https://github.com/munishm/fabrikate-kubemonkey

**Comment by shwetams** [comment]
- [x] Implement Pod level chaos testing
- [x] Implement latency injection istio fabrikate HDL
- [x] Implement Fabrikate component for chaos stack
- [ ] Add Documentation for fabrikate component

**Comment by munishm** [comment]
https://github.com/munishm/fabrikate-istiochaos

**Comment by jmspring** [comment]
While https://github.com/munishm/fabrikate-kubemonkey wraps https://github.com/asobti/kube-monkey, it feels like a bit more documentation could be added ... maybe include an example config not just additional config options.

**Comment by jred55** [comment]
@evanlouie pls take a look

**Comment by jred55** [comment]
Closing since the individual work items are done
