### ISSUE TITLE
Installation and configuration of Velero

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#401]
As an operator of a Kubernetes cluster with a Kafka stateful workload, I want to understand how to install and run [Velero](https://github.com/heptio/velero) to take regular snapshots of the Kafka deployment.

This task includes:
- defining a Fabricate definition for installing Velero
- document / define any components that must be put in place for the backups to occur

**Comment by sayar** [comment]
Quick update prior to standup. 

Fabrikate component: https://github.com/sayar/fabrikate-velero
Working through installation and configurations issues at the moment.
