### ISSUE TITLE
[SPIKE] Node Pool Support for Terraform AKS resource

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#417]
**As a:**

Cluster Operator

**I want:**

Node pool support in our terraform scripts

**So that:**

I can have multiple agent pools for my AKS cluster of varying VM SKUs, or (if i've reached my agent node limit per pool) have multiple agent pools of the same VM SKU.

**Describe the solution you'd like:**

An upstream terraform contribution to add node pool support to the AKS resource in the Azure terraform provider.

**Additional context:**

No existing work item exists in the upstream repository: https://github.com/terraform-providers/terraform-provider-azurerm/issues?utf8=%E2%9C%93&q=is%3Aissue+node+pool+

The google provider has a good way to implement node pool support: https://www.terraform.io/docs/providers/google/r/container_cluster.html

**Does this require updates to documentation?:**

Yes.

**Comment by brusMX** [comment]
This is also important because inherently you are allowing VMSS and you will also put the firs stone for Windows on AKS

**Comment by gled4er** [comment]
Hello @bnookala ,

Thank you for opening the issue!

I think this functionality will be very useful.

Let us know how we can help to prioritize.

Thank you!

**Comment by schefs** [comment]
would like to have that feature also !
all my deployments are terraform based and we want to start using multiple node pool with terraform.
can't go to production without it.

**Comment by bnookala** [comment]
The azure terraform resource provider now has node pool support https://github.com/terraform-providers/terraform-provider-azurerm/pull/3422

**Comment by bnookala** [comment]
Azure terraform provider is receiving a new resource to manage node pools independently allowing things like autoscaling - let's keep track of this while working on agent pool support independently: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4001

In addition: https://github.com/terraform-providers/terraform-provider-azurerm/issues/3971 seems to be a present issue in the terraform provider, which should be noted.

**Comment by NathanielRose** [comment]
[SPIKE] - Node pools w/availability zones (in Azure preview)
[ ] - Can this be turned on & off
[ ] -  A scaffold of the module in template
[ ] - Dependencies and Preview caveats
[ ] - Instructions with scaling in the cluster.

**Comment by NathanielRose** [comment]
Updates for Node Pools added to Master terraform provider for azure - https://github.com/terraform-providers/terraform-provider-azurerm/commit/424e973898a11a29a5243f2b520f0438a677fcae
Needs testing then integration to Bedrock.

**Comment by jluk** [comment]
FYI this was enabled in provider v 1.37 so this looks stale but I stumbled here from google 😄 

https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster_node_pool.html

**Comment by yradsmikham** [comment]
@NathanielRose From the last comment, it appears that this may be resolved now?

**Comment by NathanielRose** [comment]
Yes, @yradsmikham. Let's get a quick test log and doc proofing it out and this can be closed.
