### ISSUE TITLE
As an SRE, I want to make sure automated tests don't accumulate and clutter the subscription.

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#428]

**Comment by joelong01** [comment]
"all tests should go through the setup, run, and cleanup stages."

**Comment by jmspring** [comment]
@joelong01 - Joe - agreed, however, there are times when the test fails in a pass where terraform destroy doesn't clean things up.  So a reaper script is helpful in those edge cases.

**Comment by jmspring** [comment]
Script in place and working.
