### ISSUE TITLE
gitops build.sh script removes all files in current directory

### ISSUE THREAD

**Issue by dobrzyn2** [microsoft/bedrock#446]
When build.sh (Microsoft/bedrock/master/gitops/azure-devops/build.sh) runs it will remove files in present working directory.

To Reproduce: Allow build.sh's script to run through the transform step and then attempt to download the log files for that step.

Expected behavior: Log files should be available, azure devops should allow for the download of the zip

![image](https://user-images.githubusercontent.com/4944990/58511993-d99fb500-8150-11e9-8a1e-258cf86dbc82.png)

**Comment by andrebriggs** [comment]
@dobrzyn2 I wasn't able to reproduce. Are you using a public ADO pipeline we can reproduce on?  I'm able to download logs from the ADO UI at the `transform fabrikate definitions and publish to YAML manifests to repo`

The only file removal code current in `build.sh` is [here](https://github.com/microsoft/bedrock/blob/eacf448590959a03f03651a58fb8bf90266aa3c1/gitops/azure-devops/build.sh#L172) which removes files in the manifest remove before publishing new files.

Closing but re-open if you still have an issue we can reproduce.
