### ISSUE TITLE
Support Terraform 0.12

### ISSUE THREAD

**Issue by sayar** [microsoft/bedrock#450]
**As a:** SRE

**I want:** to be able to use Terraform 0.12

**So that:** I can take advantage of improved HCL

**Describe the solution you'd like:** There is a version constraint on some of the terraform modules that prevents using Terraform 0.12.

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by jmspring** [comment]
@sayar - currently looking into this.  There are two cases - new deployments.  Which, so far, doesn’t look too bad.  The second will be interacting with current deployments, that seems more problematic.

**Comment by jmspring** [comment]
Scripts are 0.12 compatible.
