### ISSUE TITLE
Base-image for bedrock environment is fairly large in size

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#456]
Bedrock docker base image in `test/docker/base-images/Dockerfile` creates a bunch of image layers resulting in a larger image.

Need to eventually decrease the size of the image.

**Comment by andrebriggs** [comment]
@NathanielRose  What is large? Do we have a measurement?

**Comment by NathanielRose** [comment]
@andrebriggs Its almost hitting 4gbs, should we look into decreasing the size or is this fine for now?:
```
nmrose@MININT-86O9IGE:/mnt/c/Users/naros/bedrock/terrafomUpgradeTest/bedrock$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
msftcse/bedrock-test-base   g1.11t0.11.13       f2a88cd962ca        3 minutes ago       3.69GB
golang                      1.11-stretch        1147781e1000        5 days ago          757MB
```

**Comment by jmspring** [comment]
It might be as simple as changing the underlying is image the base image is built upon.

**Comment by andrebriggs** [comment]
@NathanielRose is this still a bug? Are we blocked by it? Cc @jmspring

**Comment by NathanielRose** [comment]
@andrebriggs Not blocked by it as we are currently not leveraging this image and have plans to use potentially terrratest abstraction module for testing. This can be closed.
