### ISSUE TITLE
running 'terraform apply' in '/cluster/azure/backend-state' fails

### ISSUE THREAD

**Issue by reisholmes** [microsoft/bedrock#465]
**Describe the bug:**
Attempting to use terraform apply in /cluster/azure/backend-state results in the following error:

Error: Unsupported block type

  on storage-account.tf line 4, in resource "random_id" "remotestate_account_name":
   4:   keepers {

Blocks of type "keepers" are not expected here. Did you mean to define
argument "keepers"? If so, use the equals sign to assign it a value.

**To Reproduce:**
cd to /cluster/azure/backend-state
run: 
> terraform apply -var 'name=<storage account name>' -var 'location=<storage account location>' -var 'resource_group_name=<storage account resource group>'

You will get the following error:
---------------
Error: Unsupported block type

  on storage-account.tf line 4, in resource "random_id" "remotestate_account_name":
   4:   keepers {

Blocks of type "keepers" are not expected here. Did you mean to define
argument "keepers"? If so, use the equals sign to assign it a value.
---------------

Changing "keepers {" to "keepers = {" as suggested resolves the issue: 

https://github.com/microsoft/bedrock/blob/6914144f13fe315b0a34ef1dc8011e95d3505f55/cluster/azure/backend-state/storage-account.tf#L4

**Expected behavior:**
Terraform generates an execution plan

**Comment by luisamiranda** [comment]
@reisholmes I'm unable to replicate this bug. Can I ask for a little more information?

- Can you give a little more detail on the environment in which you were running the command - Windows/Unix, powershell/bash? Which version of terraform?

- Did you verify that the names you gave for the storage account and resource group were valid names for those Azure resources (hyphens allowed, globally unique, etc,)? Invalid names cause an error, though not this exact error (for me).

**Comment by andrebriggs** [comment]
Closing
