### ISSUE TITLE
Terraform 12.x is not supported

### ISSUE THREAD

**Issue by helayoty** [microsoft/bedrock#470]
**Describe the bug:**
Any Terraform version after 0.11.14 is not working  

**To Reproduce:**
- install Terrafrom as prerequisite (0.12.1 or 0.12.3)
- follow the instruction [here](https://github.com/jmspring/bedrock-tutorials/tree/master/walkthroughs/azure-simple#deploy-the-azure-simple-template) to deploy Bedrock simple app
- run  terraform init

**Expected behavior:**
Bedrock should work normally with any Terraform version or documentations state the supported versions. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/31887807/60383075-455f9100-9a21-11e9-93b2-b48cbb062448.png)

**Additional context:**
I downgrade Terraform to 11.14 and everything went well

**Does this require updates to documentation?:**
Yes

**Comment by jmspring** [comment]
Fixed awhile ago.  Closing.
