### ISSUE TITLE
Tag fabrikate version to a major

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#471]
**As a:** ops engineer

**I want:** the bedrock builds scripts to download a tagged SemVer Major version

**So that:** I can be assured that I download the latest non breaking bersion

**Describe the solution you'd like:** Make the build scripts tagged to pull the great 0.x.x version

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by yradsmikham** [comment]
https://github.com/microsoft/bedrock/pull/485.
