### ISSUE TITLE
Bedrock should have instructions to access existing ACR 

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#476]
**As a:** Developer

**I want:**
Documentation to setup the right privileges for Service Principal access to existing ACR to pull the container image
**So that:**

**Describe the solution you'd like:**
Documentation update
**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
Possible dupe of #255

**Comment by andrebriggs** [comment]
Fixed in #255
