### ISSUE TITLE
Add a note to the documentation regarding Terraform destroy and possibility of resource loss

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#490]
**Describe the bug:**
There could be scenarios where if one uses the existing resource group (with existing resources), terraform destroy can delete all the resources. 

**To Reproduce:**

**Expected behavior:**

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by jmspring** [comment]
Fixed with PR #491
