### ISSUE TITLE
Document expected cluster-deployment machine OS, shell, setup

### ISSUE THREAD

**Issue by luisamiranda** [microsoft/bedrock#494]
**As an:**
Infrastructure Engineer/Operator

**I want:**
To know how to set up my machine or a jumpbox to deploy Bedrock Terraform templates correctly the first time.

**So that:**
I don't have to manually install anything that should have been installed by the template, or start over in a new OS or shell.

**Describe the solution you'd like:**
Document expected cluster-deployment machine OS (Unix-like), shell (bash), setup (Terraform MUST be .11.14), you need to add some k8s secrets before your pods will pull images or access a keyvault

**Describe alternatives you've considered:**
There's no replacement for documentation

**Additional context:**
Each time I have worked through this deployment with customers or fellow developers, we have run into similar issues, with the simple fixes being passed around by word of mouth, though they are very simple to document.

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@jmspring regarding 

> To know how to set up my machine or a jumpbox to deploy Bedrock Terraform templates correctly the first time.

Do we have a docker image containing everything?

**Comment by andrebriggs** [comment]
We have a a requirements page that includes shell scripts to install dependencies now. Closing but free to reopen
