### ISSUE TITLE
Cannot deploy environment on Windows through CMD or PowerShell

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#498]
**Describe the bug:**
When running terraform apply with a configured azure-single-keyvault environment on Windows CMD or PowerShell, the command to get the cluster credentials fails due to the command being too long.

https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation

**To Reproduce:**
run `terraform apply` on a configured azure-single-keyvault environment on Windows CMD or PowerShell

**Expected behavior:**
The deployment completes successfully.

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**
For now, the work around is to use windows subsystem for linux, if possible.

**Comment by jmspring** [comment]
Bedrock uses bash scripts which require some form of *nix.

**Comment by mtarng** [comment]
Hm, okay. If that's the case, we probably just need to update the required tools section: https://github.com/microsoft/bedrock/tree/master/cluster#required-tools ?

**Comment by luisamiranda** [comment]
@mtarng That is related to my issue [#494 ](https://github.com/microsoft/bedrock/issues/494)

**Comment by andrebriggs** [comment]
Looks like we can close this. Please re-open if not satisfied @mtarng cc @jmspring
