### ISSUE TITLE
As a Developer I want to use addons on my AKS cluster

### ISSUE THREAD

**Issue by syedhassaanahmed** [microsoft/bedrock#499]
**As a:**
Developer
**I want:**
to use addons on my AKS cluster
**So that:**
I can enable Azure Monitor for Containers

**Describe the solution you'd like:**
The [azurerm_kubernetes_cluster](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html) terraform resource allows you to enable addons via the `addon_profile` block. We can expose this block in the [Bedrock AKS module](https://github.com/microsoft/bedrock/blob/master/cluster/azure/aks/main.tf).

**Additional context:**
Customer would like to use [Azure Monitor for Containers](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-overview)

cc @sachinkundu

**Comment by andrebriggs** [comment]
Hi @syedhassaanahmed, I assume you're talking about this section?

![image](https://user-images.githubusercontent.com/3119513/61892287-4cfb4400-aec0-11e9-888b-409db2f58191.png)

**Comment by syedhassaanahmed** [comment]
@andrebriggs Correct, this is the section.

**Comment by yradsmikham** [comment]
https://github.com/microsoft/bedrock/pull/526

**Comment by yradsmikham** [comment]
@syedhassaanahmed @sachinkundu 

We just created a PR for this issue. Can you confirm that this accomplishes what you want?

**Comment by syedhassaanahmed** [comment]
@yradsmikham @andrebriggs I can confirm the PR accomplishes exactly what we want. Many thanks for addressing this issue swiftly.

**Comment by andrebriggs** [comment]
Closed via #532 

cc @syedhassaanahmed @sachinkundu
