### ISSUE TITLE
As a developer, I would like an initial Bedrock release with Terraform 0.12 support

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#507]
**As a:** developer

**I want:** a Bedrock release supporting Terraform 0.12

**So that:** I can work with up to date versions of Terraform and do so reliably (static remote references)

**Describe the solution you'd like:** Upon completion of #506 I'd like a parity release with the 0.11 branch discussed in #505 ...

**Does this require updates to documentation?:** Yes

**Comment by smartpcr** [comment]
terraform has a bug before v0.11.14, please bump terraform support to version beyond 0.11.14. thanks!

[bug](https://github.com/hashicorp/terraform/issues/22315)

**Comment by jred55** [comment]
According to Jim, this is done. Hence closing
