### ISSUE TITLE
As a developer I would like to guidance on pro-active monitoring solutions for Kafka

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#510]
- [x] Samples showing to how set up Grafana templates for Kafka and Zookeeper
- [ ] Documentation or samples that show how to set up a logging solution for Kafka (ELK or EFK)

**Comment by edaena** [comment]
Dashboards samples in [sayar/fabrikate-kafka-sample/tree/master/dashboards](https://github.com/sayar/fabrikate-kafka-sample/tree/master/dashboards)
