### ISSUE TITLE
As a developer I would like a Kafka deployment sample with Fabrikate 

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#515]
Samples of composing a Fabrikate definition with GitOps
- [x] Strimzi Kafka
- [x] Portworx/StorageOS
- [x] Kafka Connect
- [x] Network Policies

**Comment by edaena** [comment]
- [ ] Change Kafka Connect sample to use TLS

- [ ] Add documentation about the sample to [sayar/fabrikate-kafka](https://github.com/sayar/fabrikate-kafka)

**Comment by edaena** [comment]
The Kafka Connect piece is in [PR review](https://github.com/sayar/fabrikate-kafka-sample/pull/8).

**Comment by edaena** [comment]
Adding Nate for the Portworx piece.

**Comment by edaena** [comment]
@andrebriggs what do you mean by network policies? There are already networking policies in place, is that sufficient? [fabrikate-kafka-sample manifests](https://github.com/sayar/fabrikate-kafka-sample/tree/master/manifests)

**Comment by andrebriggs** [comment]
@edaena updated
