### ISSUE TITLE
Go tests are picking up API management test and failing due to dependency

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#516]
**Describe the bug:** . Go tests are picking up API management test and failing due to dependency

Temporary fix will be to move the test into a temporary directory in the environment.  Once there is a release process and testing enhancements, the test will be moved back and fixed.

**Comment by andrebriggs** [comment]
@jmspring @NathanielRose is this still an issue?

**Comment by NathanielRose** [comment]
@andrebriggs @jmspring I think we can close this issue as the current APIM environment needs to be upgraded to terraform 0.12 and the latest provider 2.6

**Comment by jmspring** [comment]
agreed
