### ISSUE TITLE
As a developer, I would like concise documentation around Kafka load testing

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#518]
**As a:**
Infrastructure/ Operations Engineer

**Describe the solution you'd like:**
- [ ] Strimzi +  Portworx needs TLS testing and Perf test metrics outcome (Docs)
- [ ] Sanity Test: Validating that messages are received off the Kafka Broker (Related to #508)
   - [ ] Get the count read off a Broker? (Investigate)
- [x] Merge Initial Kafka Perf Outcome + Portworx & Strimz Load Test Docs into Markdown (Docs)

**Describe alternatives you've considered:**
- [ ] Comparison between operator: Strimzi vs Banzai 
- [ ] Comparison between operator: StorageOS vs Portworx

**Additional context:**
Docs will be in draft repo until completed - https://github.com/cnadolny/azure-kafka-kubernetes

**Comment by NathanielRose** [comment]
@cnadolny

**Comment by andrebriggs** [comment]
@NathanielRose  @cnadolny is the task list update to date?

**Comment by andrebriggs** [comment]
@NathanielRose @cnadolny where do we stand with this?

**Comment by cnadolny** [comment]
> @NathanielRose @cnadolny where do we stand with this?

Had a sync up with @NathanielRose today. The testing around the work is completed for this task, and I believe Michael took care of the sanity test requirement in another task.

Nathaniel and I created an internal document analyzing the performance of these tests. I think that it would be a good fit to add that document or parts of that document as a markdown file to the Kafka sample test folder in the Fabrikate repository. Will have another sync up next week after he's had time to go through the document.

**Comment by andrebriggs** [comment]
> Merge Initial Kafka Perf Outcome + Portworx & Strimz Load Test Docs into Markdown (Docs)

Docs added to https://github.com/microsoft/fabrikate-definitions/blob/master/samples/kafka-strimzi-portworx/test/Kafka-Performance.md
