### ISSUE TITLE
Kafka Deployment / Liveness / Functionality Test

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#520]
From #508 

Build testing script off of the kafka deployment done here: https://github.com/sayar/fabrikate-kafka-sample

Current working assumptions:
1. The deployed Kafka image provides various .sh files we can use to test via `kubectl exec`.
2. We can test by creating a new topic, publishing, then consuming messages on that topic.
3. For the fabrikate-kafka-sample, we're using the strimzi operator, which uses CRDs to deploy topics. This test script _should_ be flexible to deploy topics via CRD, and eventually though `kafka-topics.sh`.

Acceptance Criteria:
As a developer with a fabrikate-kafka-sample deployed cluster, I have a script I can run against the cluster to test the kafka message production and consumption. The documentation for this should provide all arguments and/or environment variables I need to set for the test.

- [x] Test from inside the cluster using a kafka client  via `kubectl exec`
- [x] Test with a producer/consumer app using ingress
- [x] External test with SSL/mTLS
- [x] Sample test showcasing kafkaconnect

Future considerations:
This script could be run against any kafka deployment on a kubernetes cluster, and perhaps as an bedrock sample environment integration test.

**Comment by andrebriggs** [comment]
@mtarng updated the description with with a task list. The PR https://github.com/sayar/fabrikate-kafka-sample/pull/11/ refers to the 1st item in the task list

**Comment by andrebriggs** [comment]
@mtarng is "Sample test showcasing kafkaconnect" now done?

**Comment by mtarng** [comment]
@andrebriggs yup, just merged, the changes. That should wrap up the work for this ticket.
