### ISSUE TITLE
Add ELK Stack and Capture Kafka Logs

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#525]
As a developer I want and ELK Stack so that I can Capture Kafka Logs.

Related to #510 

- [ ] Kafka logs appear in Kibana

- [ ] Instructions on logs

Resources:
[strimzi logging](https://strimzi.io/docs/latest/#assembly-logging-deployment-configuration-kafka)

**Comment by andrebriggs** [comment]
@edaena I updated the description to link to the parent story. What is the acceptance criteria here?

**Comment by andrebriggs** [comment]
@edaena please update here

**Comment by andrebriggs** [comment]
@edaena should we close this?
