### ISSUE TITLE
As a developer, I would like to secure my virtual storage Portworx in a kafka cluster

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#529]
As a developer, I would like to enable SSL and best practice security measures with Portworx so that it can receive data from a secure Kafka instance.

The current Kafka sample is plain text with no authentication. Portworx will need to encrypt messages in transit and at rest.

- [x] Volume Encryption with a cluster wide secret key
- [ ] Secret Store Type Target: Key Vault
- [ ] TLS & SSL with PX-Secure
- [ ] Container-Granular role-based authentication, authorization & Ownership

Related to #513

**Comment by andrebriggs** [comment]
@NathanielRose can you add more specific acceptance criteria? What behaviors should be expect once the task list is completed? What does that look like from the point of view of a Kafka producer? How do we verify the items in the task list?

**Comment by NathanielRose** [comment]
Acceptance Criteria:
- Attributes on volumes after running `pxctl volume inspect encrypted_volume` displays `Encrypted`
- Portworx configures with `secret type`: `key-vault`. Store cluster wide secret in key vault
- Use TLS protocol for ssl certificate access from Kafka broker to Px volume
- (Stretch) Use Openstorage with token granted users assign to broker for volume read/write permissions

**Comment by NathanielRose** [comment]
Currently, the method in which we can retrieve access to Azure Key Vault through portrworx, relies on exposing Service Principal tokens statically through environmental variables for Portworx to access the resource. We may need to look at alternative ways to attain authentication for keyvault or investigate a terraform approach to deploying portworx. - https://registry.terraform.io/modules/portworx/portworx-instance/portworx/1.0.4

**Comment by andrebriggs** [comment]
@NathanielRose I'm moving this to in progress. Please update the task list as things get merged

**Comment by andrebriggs** [comment]
@NathanielRose We should close this if we aren't going to revisit

**Comment by NathanielRose** [comment]
Will revisit as Phase 2 backlog availability clears up with upcoming sprints
