### ISSUE TITLE
Spike: Handling configuration differences between region (or environment)

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#56]

**Comment by jmspring** [comment]
When deploying a DR scenario (multiple clusters) or maybe dev/prod, there is the possibility of configuration differences.  What are ways to handle this?

First case would be the DR case outlined in #42

**Comment by andrebriggs** [comment]
We need an East, West, and Central configuration for Project Jackson.  Each region will have a env configuration for "preferred region". We will need a way to set this in an automated manner. 

cc @shwetams

**Comment by sarath-p** [comment]
@andrebriggs - are you looking for additional configuration options in addition to tfvars file?

**Comment by jred55** [comment]
Infra SPK commands and Fabrikate environments address this issue.
