### ISSUE TITLE
No passphrase prompt for gitops ssh key

### ISSUE THREAD

**Issue by archerpmorgan** [microsoft/bedrock#572]
Summary of Issue: in the azure-simple deployment demo the Flux pod cannot access private ssh key when the key has an associated passphrase, and thus cannot connect to Github manifest repository. 

-----------

When running through the azure-simple bedrock deployment, one of the flux pods was in crashloopbackoff. 

<img width="681" alt="Screen Shot 2019-09-05 at 8 18 46 AM" src="https://user-images.githubusercontent.com/27871818/64356183-4a0f6b00-cfb7-11e9-9ff4-2017ae667282.png">

Checking the logs, I saw the following:

<img width="1386" alt="Screen Shot 2019-09-05 at 8 18 33 AM" src="https://user-images.githubusercontent.com/27871818/64357018-af179080-cfb8-11e9-93b3-2c9bb301cd85.png">

The SSH key I created was created with a passphrase, which seems to have automatically and silently been asked for and not provided.

Preparing a new key with no passphrase solved the issue. So I propose either prompting explicitly for a passphrase if needed or updating the docs to explicitly direct users not to make one. Thanks!!!

**Comment by bnookala** [comment]
Related to #1241

**Comment by yradsmikham** [comment]
From their documentation: https://github.com/fluxcd/flux/blob/master/docs/references/git-gpg.md#creating-a-gpg-signing-key, step 7, it seems like you should be creating keys **without** passphrase.

I have also confirmed this by reaching out to Weaveworks directly on their Slack channel.

We will update our documentation.
