### ISSUE TITLE
Create a Fabrikate definition for the ES operator 

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#573]
**As a:**
Developer

**I want:**
To crate a Fabrikate definition for the ES Operator
**So that:**
I can efficiently deploy Elastic Search on AKS 
**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by NathanielRose** [comment]
Helm chart does not exist at this time for ECK - https://github.com/elastic/cloud-on-k8s/issues/938

**Comment by edaena** [comment]
@NathanielRose you can just add the remote url to the yaml in the fabrikate component. As this has been resolved: [fabrikate/issues/249](https://github.com/microsoft/fabrikate/issues/249)

**Comment by NathanielRose** [comment]
Currently being reviewed - https://github.com/microsoft/fabrikate-definitions/pull/30

**Comment by NathanielRose** [comment]
PR Approved & Merged.
