### ISSUE TITLE
As an org, I want to setup an AKS cluster with Azure Monitor and other components

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#574]
As a developer adopting Bedrock patterns and practices I would a deployment that install my cloud infrastructure needs with minimal configuration. The is environment should include the following:

- Single AKS
- Key Vault
- Azure Monitor
- Node pools w/availability zones (in Azure preview)
- ACR

A suggestion of further issues:
- [ ] Spike on enabling Node Pools with availability zones
  - [ ] Create Node Pool w/availability zone Terraform module
- [ ] Create a new Terraform environment template with all the pieces integrated

**Comment by jmspring** [comment]
Terraform module for ACR -- https://www.terraform.io/docs/providers/azurerm/r/container_registry.html

**Comment by NathanielRose** [comment]
[SPIKE] - Node pools w/availability zones (in Azure preview) - https://github.com/microsoft/bedrock/issues/417

**Comment by yradsmikham** [comment]
closing this because it appears to be duplicate of 585
