### ISSUE TITLE
As a developer, I want to verify if Elastic Search operator is compatible with custom ES images

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#576]
**As a:**
Developer
**I want:**
As a developer, I want to verify if Elastic Search operator is compatible with custom ES images
**So that:**
I can make changes to base ES images 
**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by NathanielRose** [comment]
Instructions for  custom ES Images - https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-bundles-plugins.html

**Comment by NathanielRose** [comment]
Closing
