### ISSUE TITLE
As I developer, I want to investigate mono-repo capabilities within Azure Devops

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#578]
**As a:**

Developer

**I want:**

To investigate the ins and out of structuring multiple services within a single mono-repository

**So that:**

I can better accommodate situations in which a team manages multiple docker container images/services from a single git repository 

**Describe the solution you'd like:**

A spike/investigatory sprint to identify how we Azure DevOps behaves when only a single git repository can be used for multiple application source/services

**Describe alternatives you've considered:**

The status quo, at present, is to utilize a unique git repository for every service deployed to the cluster.

**Additional context:**

Customer teams have approached us with the need to deploy multiple services from a single source repository to a cluster. Presently, we do not accommodate this, but we should be able to. 

**Does this require updates to documentation?:**

Yes

**Comment by andrebriggs** [comment]
I've updated an example mono-repo [here](https://github.com/andrebriggs/monorepo-example). The take away is that when someone changes a "service":

1. An image will be built and pushed to ACR. This is the "build" stage. 
2. The next stage is a the "release" stage (which I didn't build out). This release stage is just making a PR to a HLD repo that updates the image tag. Using this method we will always have the latest image tags for image that weren't built in a particular run.

The service specific [azure-pipelines.yaml](https://github.com/andrebriggs/monorepo-example/blob/master/service-A/azure-pipelines.yml) files might be useful when thinking about building the service creation. 
The in snippet below I've had to hard code the service name (which is also the directory name). We need to generate this in the service creation code:

<pre>
trigger:
  branches:
    include:
    - <b>master</b>
  paths:
    include:
    #Can't use a variable since they are evaluated at runtime, not at trigger time.
    #Hardcoding for now
    - '/<b>service-A</b>/*' 
</pre>

I've also bolded the fact that the build is only triggered on master branch. If we want a trigger on other branch patterns we should add them.

cc @mtarng @bnookala @evanlouie

**Comment by evanlouie** [comment]
@andrebriggs I actually already templatized a bit of your starter yaml. The current implementation defaults to triggering on master and will swap out `service-a` to the appropriate directory:

If you ran `spk project init` in `my-standard-repo`:

- my-standard-repo/
  - azure-pipelines.yaml // `paths will be './'`

If you ran `spk project init --mono-repo --packages-dir packages` in `my-mono-repo`:

- my-mono-repo/
  - packages/
    - service-a/
      - azure-pipelines.yaml // `paths will be './packages/service-a/'`
    - service-b/
      - azure-pipelines.yaml // `paths will be './packages/service-b/'`
    - service-c/
      - azure-pipelines.yaml // `paths will be './packages/service-c/'`

**Comment by andrebriggs** [comment]
Awesome @evanlouie

**Comment by mtarng** [comment]
@andrebriggs @jred55 @evanlouie @bnookala closing this ticket as the work we've done with spk supports using a mono-repository.
