### ISSUE TITLE
As a developer I want to create a service revision

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#579]
**As a:**

Developer

**I want:**

To create a service revision (a deployable version of my application) using my CLI I must:

- [x] Specify the initial branch/ring to deploy to in bedrockconfig (perhaps this is done as a consequence of initialization)
- [x] Invoke a CLI command that would take in a branch name or use the present branch name to create a PR against the initial branch/ring - rebase against initial branch required

**So that:**

I can push a deployable version of my application to my cluster

**Describe the solution you'd like:**

A bedrock CLI based shortcut for automating the process of creating automating  a pull request from my feature branch to my QA branch, which itself represents the QA ring.

**Describe alternatives you've considered:**

**Additional context:**

To provide devs the opportunity to test their applications in a production-like environment, we must give them the ability to deploy their applications to the QA ring.

**Does this require updates to documentation?:**

Yes

**Comment by andrebriggs** [comment]
@evanlouie this was moved to in review. Can you link the associated PR?

**Comment by mtarng** [comment]
Closed via: https://github.com/CatalystCode/spk/pull/62
