### ISSUE TITLE
Investigate/Automate getting deployment information for a single service across all pipelines and cluster deployment 

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#580]
As an SRE or developer I want observability into the journey my services take from application code repository commits to the Kubernetes cluster.

**So that:**

- [x] I can see deployment information for a single service across all pipelines and cluster deployment
- [x] I can get information about the app code build pipeline
- [x] I can get information about the associated High Level Definition pipeline (PR’s based upon app code builds)
- [x] I can get information about the associated Manifest repository changes (from the pushed HLD repo changes)
- [x] I can get information about the Flux commit id that has been applied to the cluster

**Comment by samiyaakhtar** [comment]
Closing this as it's covered and closed in other issues
