### ISSUE TITLE
As a developer, I would like to initialize a mono-repository

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#581]
**As a:**

Developer

**I want:**

"Initialize" a mono-repository. The git repository may already exist, but I would like to use my CLI to create services and produce container images within it in the future.

I expect that initialization will:

- [x] Create a Maintainers file
- [x] Create a Bedrockconfig outlining the services defined within the repository.

**So that:**

I can create multiple services within the mono-repository and have them deployed to a kubernetes cluster

**Describe the solution you'd like:**

A CLI based tool to onboard or create a mono-repository, that sets up azure pipelines to build container images and to configure my Cluster HLD

**Describe alternatives you've considered:**

None

**Additional context:**

Drawing from the needs of customers, we will need to support creating and managing repositories for applications deployed to a cluster.

**Does this require updates to documentation?:**

Yes

**Comment by evanlouie** [comment]
Re-opening until we have a more finalized solution
