### ISSUE TITLE
(Spike) Explore service hooks available in ADO for onboarding

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#582]
**As a** developer, I would like to know the method(s) for how I can onboard to start using the Spektate tool and send data to the tool from all the pipelines. 

**I want:** a complete guide on how to onboard to use the Spektate tool, both CLI and dashboard.

**Additional context:**
Methods for updating the pipeline from a task:
- [x] send POST request to an azure function
- [x] download and run a python script
- [x] (Spike) explore the service hooks available in Azure DevOps (and see if these can be extended to tools outside ADO or if they would remain Azure specific, in which an alternative needs to be setup)
    - [x] Push a message to azure storage queue when a build starts
    - [x] Run a script that dequeues this message and gets the build id
        - [x] Query the azure API to get variables for this specific build, to get image tag, hld commit id, etc. 

**Does this require updates to documentation?:** Yes

**Acceptance Criteria:**

A document/artifact explaining why we can/cannot use the service hooks in AzDO for sending data to the pipelines. If we can use this method, ideally, a working example of sending data to the pipelines would be useful

**Comment by samiyaakhtar** [comment]
It looks like there's no way to trigger an event when a build _starts_, only when the build _completes_. This will make the deployment visible on the introspection tool very late, possible after it has failed or completed.

**Comment by andrebriggs** [comment]
@samiyaakhtar I wonder if this combination fulfills the same need 
<img width="609" alt="image" src="https://user-images.githubusercontent.com/3119513/65735641-f57a7f80-e08c-11e9-82af-4aeedc233560.png">

**Comment by samiyaakhtar** [comment]
I keep getting this error when I try to create a service hook for "Run state changed", but I was able to get a hook working for "Build completed"

![Screen Shot 2019-09-27 at 11 46 14 AM](https://user-images.githubusercontent.com/1795990/65794177-73d23280-e11c-11e9-8f3a-ac3abdc4aeb7.png)

**Comment by andrebriggs** [comment]
Added a write up of the spike here: https://github.com/andrebriggs/service-introspection

**Comment by samiyaakhtar** [comment]
Closing this task but created a few follow ups: https://github.com/microsoft/bedrock/issues/690, https://github.com/microsoft/bedrock/issues/686
