### ISSUE TITLE
As a developer, I want to implement infra validations prior to deploying resources

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#589]
**As a:**
Developer

**I want:**
a CLI to perform validation against a local environment to ensure all prerequisites are installed and authentication (to Azure) is valid

**So that:**
an environment is prepared to deploy resources

**Describe the solution you'd like:**
The CLI command should do the following:
  - [x] Verify prerequisites are installed (az cli, terraform, git, and helm)
  - [x] Authenticate with Azure
  - [x] Check to see that environment variables are set

E.g. `spk infra init`

**Additional context:**

**Acceptance Criteria:**

spk tool (CLI) can be used to validate prerequisites, check for Bedrock repo clone and environment variables for service principal.

**Does this require updates to documentation?:**
Yes

**Comment by NathanielRose** [comment]
Unit Tests
- [ ] Remove prereqs from path to assure function throws a fail
- [ ]  Auth: sign in&out?

**Comment by jmspring** [comment]
@yradsmikham - let's work together to get some acceptance criteria on this issue today
