### ISSUE TITLE
As a developer, I want to create an azure-simple cluster 

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#590]
**As a:**
Developer

**I want:**
a CLI to automate the creation of the Bedrock azure-simple cluster

**So that:**
much of the manual steps involved in deploying the azure-simple cluster can be automated

**Describe the solution you'd like:**
The CLI command should resemble the following:

`spk infra create azure-simple --resource-group <resource group name> --cluster-name <cluster name> --gitops-url <manifest repo in ssh format> --sp <service principal> --secret <service principal password>`

The `spk infra create` command(s) do the following behind the scenes:
- [ ] take in argument values as use them in a .tfvars file
- [ ] `terraform init`
- [ ] `terraform plan`
- [ ] `terraform apply`
- [ ] creates rg for BYO

**Describe alternatives you've considered:**
Many iterations of this may exist. For now, it may be simpler to leave other variables in Terraform as a default.

**Additional context:**
We are assuming that the user already has the prerequisites installed, the Bedrock repo cloned, and the template copied.

**Acceptance Criteria:**

- spk tool (CLI) can be used to create a simple Azure AKS Cluster given the required parameters (Resource Group, Cluster Name, GitOps Url, Service Principal, and Secret) 

**Does this require updates to documentation?:**
Yes

**Comment by NathanielRose** [comment]
Unit Testing
- [ ] environment init (Service Principal)
- [ ] Copying the template
- [ ] ssh-keygen
- [ ] Check for Env Vars

**Comment by evanlouie** [comment]
Triage and break down into smaller stories

**Comment by NathanielRose** [comment]
Needs Revision: Awaiting @jmspring Updates

**Comment by NathanielRose** [comment]
SPK will no longer handle the direct deployment of a terraform infrastructure. This is handled by the user's method choice for validating their infra confguration. We will provide documentation guidance on terragrunt deployment coupled with SPK.
