### ISSUE TITLE
Initialize the tool on a new machine for the first time

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#593]
**As a:** developer/operator

**I want:** the ability to initialize the tool on a new machine for the first time

**So that:** I can introspect my services  

**Does this require updates to documentation?:** Yes, provide examples on how to run this command. 

**Implementation Details:**

Use and combine information from the global init command in SPK which should already have some of the fields needed by service introspection. In future, use all configuration available in the Azure Keyvault which should be the only entry point to all configuration needed by the tool. 

Configuration currently needed by Spektate CLI:
- --azure-org <azure-org>   
- --azure-pipeline-access-token <azure-pipeline-access-token>   
- --azure-project <azure-project>  
- --manifest <manifest>  
- --manifest-access-token <manifest-access-token>   
- --github-manifest-username <github-manifest-username>    
- --storage-account-key <storage-account-key>  
- --storage-account-name <storage-account-name> 
- --storage-partition-key <storage-partition-key>   
- --storage-table-name <storage-table-name> 

- [x] Take into account global init command
- [x] Explore all the different methods of storing private access keys as config, based on the global init command
    - different methods were explored in multiple team discussions, and the option of initializing via a config.yml file that references env variables for secret config was the decision made

**Comment by evanlouie** [comment]
Break down into smaller stories: (eg; extract keyvault out)

**Comment by samiyaakhtar** [comment]
Separated portions of this one into https://github.com/microsoft/bedrock/issues/626
