### ISSUE TITLE
Enhance List of Deployments

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#605]
**As a:**
Deveoper/operator

**I want:**
To get a list of all the deployments associated to a service or any filters of my choice

**So that:**
So that I can observe what has been deployed and the associated information to the deployment

**Implementation details:**
- ~~Given an author (into src repo), display all the deployments created by them~~
- [x] Provide the option to `--watch` the deployments for a live view  [PR](https://github.com/CatalystCode/spk/pull/32) 

**Acceptance Criteria:**

User is able to filter via author and also watch the deployments for a live view

**Comment by samiyaakhtar** [comment]
Closing since cli enhancements are covered in other issues
