### ISSUE TITLE
Spike: Investigate ways to test CI/CD shell scripts

### ISSUE THREAD

**Issue by yradsmikham** [Microsoft/bedrock#61]
Looked at a few options for developing unit tests, and it appears the using a shell script may be the simplest approach for now. Stumbled upon shUnit2, which is a unit test framework, and could be using it to aid in developing the unit test.

After discussing with the team, it appears that the following steps will take place:

1) Refactor build.sh so that it is broken up into functions. That way, the unit test can source build.sh and reference reusable blocks of code from the script for testing.

2) Develop unit test shell script that will specify default environment variables and call functions from build.sh to run for testing. This should be able to run locally and report results.

**Comment by andrebriggs** [comment]
@yradsmikham when you're done investigating can you describe the next steps you plan to take?

**Comment by yradsmikham** [comment]
Updated description.

**Comment by NathanielRose** [comment]
@andrebriggs @yradsmikham @samiyaakhtar  Is there any over lay with #8 for this issue?

**Comment by yradsmikham** [comment]
@NathanielRose, there should not be any overlap. This unit test is built around the shell script used in the Azure DevOps pipeline.

> @andrebriggs @yradsmikham @samiyaakhtar Is there any over lay with #8 for this issue?
