### ISSUE TITLE
Invalid source path for acr module in azure-single-keyvault terraform template

### ISSUE THREAD

**Issue by telleluy** [microsoft/bedrock#612]
**Description**
When following the doc/guidelines at 
https://github.com/microsoft/bedrock/tree/master/cluster/environments/azure-single-keyvault

terraform reports an error when running terraform init step.

**To Reproduce:**
Follow the instructions for azure-single-keyvault template described in the link in description above

**Expected behavior:**
terraform will create AKS service, 

**Actual behavior:**
terraform reports that acr module cannot be read:
```
Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../azure: no such file or
directory


Error: Failed to read module directory

Module directory  does not exist or cannot be read.
```

**Additional context:**
Steps in Create common infra as described in
https://github.com/microsoft/bedrock/tree/master/cluster/environments/azure-common-infra
executed and common-infra has been created.

**Does this require updates to documentation?:**
No.

**Temporary solution:**
After copying the azure-single-keyvault folder, change the _source_ value in 
azure-single-keyvault/acr.tf to 
`"github.com/microsoft/bedrock?ref=master//cluster/azure/acr"`

**Comment by yradsmikham** [comment]
Just tested this with the current master version of Bedrock branch. The azure-single-keyvault environment appears to be deploying successfully. I think it's safe this close this issue.
