### ISSUE TITLE
[SPK] Retrieving PAT stored in an azure keyvault for running spk commands

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#617]
**As a:** spk user

**I want:** to be able to run `spk` with permissions against an azure devops project without having to save my PAT in the spk-config.yaml file.

**So that:** I can deploy manipulate my azdo org

**Describe the solution you'd like:** 
If I have my PAT stored in an azure keyvault and the required configuration pointing to that key in spk-config.yaml, then `spk` will load that PAT value when it needs it.

The priority for PAT should be:

1. Passed via flag
2. From the config file
3. Tries to fetch from keyvault, if it's configured and exists
4. Throws error.

**Describe alternatives you've considered:** Manually storing PAT in env or as a flag

**Additional context:** Expectation is a keyvault is created via the `spk infra init` function and a PAT is also populated in it

**Does this require updates to documentation?:**
Yes

**Comment by evanlouie** [comment]
Potentially needs to be broken down as it requires coordination with infra

**Comment by mtarng** [comment]
May not be needed. #678 covers this for pipeline related stuff.

**Comment by mtarng** [comment]
Reopening. #678 is for the Pipelines to use the PAT via Variable groups. This ticket is to have the ability for spk to fetch a PAT from keyvault. The priority for PAT should be:

1. Passed via flag
2. From the config file
3. Tries to fetch from keyvault, if it's configured and exists
4. Throws error.

**Comment by andrebriggs** [comment]
@mtarng I'm trying to see how this fits in right now. Let me know if still valid

**Comment by andrebriggs** [comment]
@sarath-p We already have this functionality, right? cc @mtarng

**Comment by sarath-p** [comment]
@andrebriggs - we have PAT mapped to Key Vault secret in variable group which is different than this. This issue is particularly for `spk` config similar to storage access key.

**Comment by mtarng** [comment]
Ah, let me rewrite some of this ticket then. That makes sense, but I don't think this ticket is a high priority.

**Comment by mtarng** [comment]
Marking this as "won't fix" as we have not encountered this use case. We can revisit this as needed.
