### ISSUE TITLE
Create PR checks as a verification before merge into master

### ISSUE THREAD

**Issue by samiyaakhtar** [Microsoft/bedrock#62]
This should run fab generation as a verification to make sure components are valid and build passes before it's merged into master

**Comment by andrebriggs** [comment]
@samiyaakhtar as there are examples of the "Run check on PR" and "Run check on merge to master" in YAML files [here](https://github.com/Microsoft/azure-devops-cli-extension/blob/master/.azure-pipelines/azure-pipelines-pr.yml
) and [here](https://github.com/Microsoft/azure-devops-cli-extension/blob/master/.azure-pipelines/azure-pipelines-merge.yml). Thanks @atbagga for directing us to these examples 🙌🏾

The key yaml configuration for "Run check on PR" (where we do a simple validation) looks like 
```
pr:
- master

trigger: none
```

For "Run check on merge to master" (where we run fab generate)
```
trigger:
- master

pr: none
```

**Comment by samiyaakhtar** [comment]
Yes we're doing a `fab generate prod` as a test but not doing anything with the generated files. I'm looking at a solution like this as a possible solution (except it needs to checkout the right branch for verification):
`

**Comment by samiyaakhtar** [comment]
Completed
