### ISSUE TITLE
Update pipelines to include introspection storage update scripts

### ISSUE THREAD

**Issue by sarath-p** [microsoft/bedrock#621]
**As a:** Developer/operator
 
**I want:** the 3 service introspection scripts to be present in the yaml that is generated from the spk commands

**So that:** I have the option to start using introspection without having to manually insert the scripts into the pipeline yaml files.

**Describe the solution you'd like:**
Currently, the pipeline commands generate `azure-pipelines.yaml` file that performs all the basic steps but does not include the introspection scripts within it. If we add the scripts with a condition that they should only be run when the variables containing the storage are defined, then we will not break existing pipelines, and also make it easy to onboard to use introspection in future. This also makes integration testing for https://github.com/microsoft/bedrock/issues/891 possible. 

**Describe alternatives you've considered:** Setup manually by following the docs which is tedious and error prone.

**Additional context:** Simplified and improved user experience customers. 

**Does this require updates to documentation?:** Yes

**Implementation details:**
Update the existing yaml files to include: 
- [x] script that sends data to storage for the src -> acr pipeline
- [x] script that sends data to storage for acr -> hld pipeline within the same multi-stage pipeline
- [x] script that sends data to storage for hld -> manifest pipeline
- [x] all these scripts will not fail if the introspection storage variables are missing. They should only be executed when the 4 variables essential for introspection are **defined** (add a `condition` to the yaml scripts)

**Acceptance Criteria:**
Integration tests can be run easily, and users who built pipelines using our automation can onboard to introspection easily.

**Comment by andrebriggs** [comment]
@samiyaakhtar @sarath-p @edaena this is marked as a `effort -L`

Seems like  `Create a script that will let us inject a task into a pipeline to update storage db` is really about creating a reusable piece of code of script that appends tasks to an existing yaml file. This seems complicated. Do we have a prototype of something that would give us confidence about being able to do this? 

I could see complexity based upon the various parts of in a `azure-pipelines.yaml` file. If a client adds a new application code repo when should they run this new tool to update their `azure-pipelines.yaml` file?

Perhaps let's break this down to a smaller piece or investigate?

**Comment by sarath-p** [comment]
Will need to update this issue based on the outcome of microsoft/bedrock#582 and prioritize.

**Comment by andrebriggs** [comment]
@samiyaakhtar please update the description to describe your solution

**Comment by samiyaakhtar** [comment]
@andrebriggs I've updated the description. Is there something in particular missing?
