### ISSUE TITLE
spk deployment init using keyvault

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#626]
**As a:** developer

**I want:** to store all my configuration in an azure keyvault

**So that:** I can specify a single keyvault name to access all my config

**Describe the solution you'd like:**
This would expand the `spk deployment init` command to offer the option of initializing via an azure keyvault

**Additional context:**
- [ ] Support the option of supporting this initialization via Azure Keyvault
    - [ ] Make sure keyvault is being used by pipelines via variable groups
    - [ ] Make sure keyvault can be initialized via the init command
    - [ ] Make sure non-keyvault initialization is still supported if it's still needed (sync with folks from other teams)

**Comment by edaena** [comment]
Related to #649 and also to #591
