### ISSUE TITLE
[SPK] Getting Started Guide - Kickoff

### ISSUE THREAD

**Issue by mydiemho** [microsoft/bedrock#628]
**As a:** Developer

**I want:** to know what the getting started guide should look like

**So that:** I can begin to write an end-to-end scenario doc for how to get started with SPK

**Describe the solution you'd like:**
a `Getting Started` guide

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by mtarng** [comment]
From meeting on 10/14:

TODOs:
- [ ] Create a What and Why for SPK in the main README.
- [ ] Attach simple diagrams from gameplan.
- [ ] Move current how-to documentation into a `/docs` subdirectory.
- [ ] For releases, we should have a checklist to go through to make sure all documentation supports the latest changes.

@andrebriggs @mydiemho @samiyaakhtar @yradsmikham @jred55
