### ISSUE TITLE
[SPK] argument to create directory on project init

### ISSUE THREAD

**Issue by mydiemho** [microsoft/bedrock#629]
**As a:**
Developer

**I want:**
to be able to specify a path 

**So that:**
the folder is created on project init

**Describe the solution you'd like:**
`./spk -p sample-project` will create a folder and stored all the new code in it

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by bnookala** [comment]
@mydiemho we envision this tool to work sort of like how npm works - npm can only work in a project directory with a `package.json` for example, so we will not be doing this.
