### ISSUE TITLE
[SPK] add .gitignore for project template

### ISSUE THREAD

**Issue by mydiemho** [microsoft/bedrock#630]
**Describe the bug:** 
spk.log should be ignored.

**To Reproduce:**

**Expected behavior:**

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by evanlouie** [comment]
This file should already be captured by https://github.com/CatalystCode/spk/blob/master/.gitignore#L8

Is your git client still picking up the file?

**Comment by mydiemho** [comment]
@evanlouie this is for new project created from running `spk init project create`
