### ISSUE TITLE
[SPK] create helper methods for validating cli input

### ISSUE THREAD

**Issue by mydiemho** [microsoft/bedrock#634]
**As a:**
Developer

**I want:**
to be able to call helper that can validate input to check for empty/null/expression validity.  

**So that:**

**Describe the solution you'd like:**
helper methods 

**Describe alternatives you've considered:**

**Additional context:**
adopted these methods from an existing project https://github.com/serverless/serverless-azure-functions/blob/master/src/shared/guard.ts

**Does this require updates to documentation?:**

**Comment by bnookala** [comment]
@mydiemho I think we're going to punt on this work since TS3.7 comes in a month and supports guard functions at the language level https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/
