### ISSUE TITLE
[SPK] Pipeline Stage to build container image, push to ACR

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#646]
**As a:** developer

**I want:** the auto generated azure-pipelines.yaml file from `spk project init` to automatically trigger ACR builds

**So that:** every commit to my project get a new image

**Describe the solution you'd like:** 
- [x] Fix the current starter pipeline to allow multiple variable groups
- [x] Modify the existing `services` azure-pipelines.yaml template to include the an ACR build job as the first build stage. The target ACR resource can be referenced from the pipeline variables
- [ ] Save the container tag/id for the second build stage - #647 

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by bnookala** [comment]
See: https://github.com/microsoft/bedrock/blob/master/gitops/azure-devops/ImageTagRelease.md#2-create-application-code-pipeline

**Comment by andrebriggs** [comment]
@evanlouie @mtarng @bnookala It's not clear where we are in this process. Can we at least add a task list with some steps of the implementation that is being performed?

Moreover, this issue is a dependency for #693 and if this current issue will be down in time to unblock #693

**Comment by andrebriggs** [comment]
> The target ACR resource can be referenced from the pipeline variables.

Do you meanIn a multistage YAML pipeline we know the ACR image name like [here](https://github.com/andrebriggs/spartan-app/blob/e8351a1e9e865e3549d47fe15177c0893c35d84b/azure-pipelines.yml#L70) and can use it to set information with Fabrikate like [here](https://github.com/andrebriggs/spartan-app/blob/e8351a1e9e865e3549d47fe15177c0893c35d84b/azure-pipelines.yml#L162)?

@bnookala @mtarng `spk project init`  [documentation](https://github.com/CatalystCode/spk/blob/master/docs/project-management.md#init) says it will add a `azure-pipelines.yaml` file. I was under the impression that `spk service create` would add an `azure-pipeline.yaml` file. 

The documentation doesn't mention it. What is the order operations we expect a client to to use when starting from scratch?

Is it :
1. `spk project init` Initialize the bedrock repo workspace
2. `spk service create` Add new sub-directory to packages
3. Repeat step 2 until happy?

**Comment by bnookala** [comment]
@andrebriggs if you've already got a number of services that you want brought in and set up with `spk`, start with `spk project init`.

Then at some point if you need to add another service: `spk service create`
