### ISSUE TITLE
[SPK] Pipeline Stage to update HLD with latest ACR build tag and open PR

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#647]
**As a:** Developer

**I want:** To be able to instrument the ACR->HLD pipeline via spk

**So that:** I do not have to manually setup the pipeline myself

**Describe the solution you'd like:** 

With the first stage done and the container id from ACR known, the second stage of the pipeline should update my HLD with my latest tag for my service, and open a PR.

- [ ] Modify the existing services azure-pipelines.yaml template to have a second build stage that:
- Updates the HLD repository (variables can be from azure devops) with the latest container id from #646 
- Opens a PR on the HLD repository using azure devops CLI.

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
Ya

**Comment by bnookala** [comment]
On discussion, we think that likely the easiest approach to handle this would be to modify the yaml pipeline that we use and generate for `spk create services` to be a multi stage pipeline. This way, we don't have to set up a service connection to container registry, and the HLD configuration pipeline would get kicked off after the build pipeline gets run.

**Comment by andrebriggs** [comment]
This is in the backlog and needs a task list @bnookala @mtarng
