### ISSUE TITLE
Instrument HLD -> Materialized Pipeline

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#648]
**As a:** developer

**I want:** to be able to (via spk) automatically instrument the pipeline which when a commit is made to the HLD master, regenerate and push the generated manifests to the materialized repo

**So that:** I do not have to setup the pipeline manually

**Describe the solution you'd like:** With a target HDL repo and Materialized repo referenced in the spk config file, setup a command to automatically setup the pipeline to publish HLD updates to the materialized repo

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by bnookala** [comment]
https://github.com/microsoft/bedrock/blob/master/gitops/azure-devops/ManifestGeneration.md#add-azure-pipelines-build-yaml
