### ISSUE TITLE
Create a Variable Group with a link to Azure KeyVault

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#649]
**As a:**

Developer/Operator

**I want:**

To be able to create a variable group in AzDo project with bedrock CLI. 

I expect my CLI to:
  - [x] Ability to create Variable Group in AzDo project from the configuration
     - [x] Create Variable Group with `Vsts` type
        - Map configured key/value pairs as Variables in the group.
     - [x] Create Variable Group with `AzureKeyVault` type
        - Map configured Azure Key Vault Secrets in Variable Group
        - Create Service Connection EndPoint to authenticate with Key Vault if Service Connection does not exist with the name in the payload.
- [x] Accept variable group payload from the command without depending on `spk` config including Service Creation payload for authorization with Key Vault
- [x] Create unit test cases

**So that:**

I can easily setup Bedrock GitOps features and using secrets from Azure Key Vault with out a manual process.

**Describe the solution you'd like:**

An option in CLI tool to create a Variable Group in AzDo project.

**Describe alternatives you've considered:**

Manual creation in AzDo UI

**Acceptance Criteria:**

An AzDo project contain newly created variable group with a link to Azure Key Vault for secrets. 

**Does this require updates to documentation?:**

Yes

**Comment by sarath-p** [comment]
@andrebriggs - which command initiates the call to create a variable group?

**Comment by andrebriggs** [comment]
@sarath-p @samiyaakhtar shall we move this to Sprint 5

**Comment by sarath-p** [comment]
@andrebriggs - i would not recommend it. I think we should be able to merge it on Monday morning.

**Comment by andrebriggs** [comment]
@sarath-p  @samiyaakhtar Then it's Sprint 5. I'm just trying to keep us honest

**Comment by sarath-p** [comment]
Let’s move it. It makes sense.
