### ISSUE TITLE
Investigate how flux can access Azure DevOps Git Repos

### ISSUE THREAD

**Issue by andrebriggs** [Microsoft/bedrock#65]
Investigate and prototype. 

Flux uses SSH based "deploy keys" to communicate with GitHub repos. It's unclear how we would authenticate with Azure DevOps git repos. Flux provides a guide on how to set up SSH keys on non GitHub repos [here](https://github.com/weaveworks/flux/blob/master/site/standalone-setup.md#using-a-private-git-host).

**Comment by dtzar** [comment]
You should be able to just add any desired public SSH key via a user's Azure DevOps account which has write access to the desired repository. [See article](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops).

There is no way I know of to have a "deploy key" equivalent in Azure DevOps which isn't attached to a user logging in and adding the key, although this would be helpful!
