### ISSUE TITLE
Release Creation Pipeline for SPK

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#651]
**Feature**

As an spk developer, I want 

1. a script that will bump the package version and create a new branch
1. A pipeline that will trigger on tag to publish a new release on GitHub

## Process
1. User use script to bump new version and create new branch
    * script take in release type: `major`, `minor` etc.
1. User create PR off the branch created in step 1
1. Once pr is merge, user can tag the commit on master and a pipeline will kick off
1. This pipeline will create artifact for each OS and create a new release on GitHub

**Will this require changes to documentation**

yes

**Comment by mydiemho** [comment]
@evanlouie @bnookala @mtarng  a few questions

1) How often do we want to release?
    * on merge to master?
    * trigger on schedule, end of day Friday?
    * manual only?
1) How do you want to version this? 
    * update `package.json` & use that (https://yarnpkg.com/lang/en/docs/cli/version/)
    * use git sha?

Thoughts on release this as npm library?

**Comment by evanlouie** [comment]
How often: I think manual for now
Versioning: I'd go with the version tracked in package.json

**Comment by andrebriggs** [comment]
@mydiemho agreed with @evanlouie

**Comment by mydiemho** [comment]
2 approaches

## Approach 1
1. Manually trigger pipeline
1. Pipeline will do the following
    * Update `package.json` with new versrion, commit to master
    * Package and create GitHub release

## Approach 2
1. Manually update package.json with new version
1. Create PR
1. Merge PR
1. Manually kick off pipeline to package and create GitHub release

**Comment by andrebriggs** [comment]
Perhaps another approach to keep parity with the release process of https://github.com/microsoft/fabrikate is to 

1. Have a shell script that takes in the version as a parameter and updates package.json and build artifacts for all platforms
2. Create PR
3. Merge PR
4. Create Release on GitHub with artifacts (https://github.com/(ORG)/(REPO)/releases/new 

Done the line I think an AzDO release pipeline makes sense for all Bedrock binaries. Thoughts? @evanlouie @bnookala @mydiemho

**Comment by mydiemho** [comment]
@andrebriggs  this sounds almost identical to the `Approach 2` I written above, only replacing step 4 with an AzDO pipeline (and also build the artifact in this step vs step 1).

**Comment by andrebriggs** [comment]
@mydiemho it's much simpler without introducing AzDO into the mix so pretty different.

**Comment by mydiemho** [comment]
@andrebriggs if we're not going to create a release pipeline as the work item stated, then I'm going to take this one off and create a new one with your desire acceptance criteria

**Comment by bnookala** [comment]
@mydiemho we expect that an assignee to a ticket will drive the acceptance criteria and the tickets completion - this may involve changing/editing the description/title etc to accurately reflect what we'd like to see, saying there's no work to be done here is somewhat inaccurate, as the task reflects a need.
