### ISSUE TITLE
As a developer, I want to better manage/modify terraform templates using `spk infra generate` by caching

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#653]
**As a:**
Developer

**I want:**
a CLI to generate Terraform scripts for all the infrastructure for a specific deployment. In such, I would like to locally cache the source repositories of the terraform environment templates my deployment is dependent on.

**So that:**
I can manage terraform templates at scale, update and version my deployment templates.

**Describe the solution you'd like:**
E.g:
`spk infra generate` 

The CLI command should include the following functionality:
- [x] Check if the source repo to a `temp` directory is provided in definition.json
- [x] Clone the repo if the provided definition.json source is not present on the machine
- [x] Logic to assure my cloned repos can later be checked for versioning

**Describe alternatives you've considered:**

**Acceptance Criteria:**
Logic handling the cloning of repo to later have the environment templates copy the appropriate files to a generated folder.

**Comment by yradsmikham** [comment]
Succeeds the work of https://github.com/microsoft/bedrock/issues/657.

**Comment by andrebriggs** [comment]
@yradsmikham @NathanielRose is this is valid?

**Comment by yradsmikham** [comment]
I think it's safe to say that issue has changed due to Terragrunt. @NathanielRose, should we close this one, or do you want to update this task and have it be around day 2 actions, such as "updating" infrastructure?

@andrebriggs

**Comment by NathanielRose** [comment]
Lets close, Generating of infra definitions has been migrated to Terragrunt HCLs - https://github.com/microsoft/bedrock/issues/668https://github.com/microsoft/bedrock/issues/668

**Comment by yradsmikham** [comment]
pivoting away from Terragrunt, so re-opening.

**Comment by andrebriggs** [comment]
@yradsmikham @NathanielRose is the approach and effort the same as before the task was re-opened?

**Comment by NathanielRose** [comment]
@andrebriggs Yes this is a task that was scoped prior to going down the terragrunt route. Additional layered functionality for generate has been added by Yvonne here: https://github.com/microsoft/bedrock/issues/721

**Comment by yradsmikham** [comment]
@andrebriggs, same approach, but I've broken it up into manageable tasks for a single sprint and created another `spk infra generate` task to handle the remainder of the tasks.

**Comment by NathanielRose** [comment]
We'll need to figure out private repos by modifying scaffold and `definition.json`. This is detailed here - https://github.com/microsoft/bedrock/issues/740

**Comment by yradsmikham** [comment]
A discussion around having `generated` and definition.json` files separated into different directories might help with coding logic around iterating through directories. It may make more sense to consider generating into a parallel directory with the same structure as the definition so the definition directory remains clean.

**Comment by yradsmikham** [comment]
Reducing the scope and effort of this task.

**Comment by NathanielRose** [comment]
Updating to reflect cloning cache work.

**Comment by NathanielRose** [comment]
Closed in https://github.com/CatalystCode/spk/pull/117
