### ISSUE TITLE
[SPIKE] As an operator, I want to enhanced support for Azure authentication by using managed identities

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#654]
**As an:**
Operator 

**I want:**
To use a [managed identity](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity) in AKS and pivot from no longer having to provision a service principal to manage cluster access to Azure (for infra like load balancer, disks, public ip address, etc).

**So that:**
Ease of management of azure credentials.

**Describe the solution you'd like:**
- [ ] Bedrock support and documentation for Managed Identity
- [ ] Support for `spk` & `spk.config` CLI for managed Identity

**Describe alternatives you've considered:**
Caveat: For now, if you are using any add-ons such as monitoring, virtual node, azure policy, and http application routing, you will need to add a service principal. Eventually, the requirement for a service principal to be created will be removed completely.

**Additional context:**
Related to [PR587](https://github.com/microsoft/bedrock/pull/587)

Getting started shell script:
```
export RESOURCEGROUP=AKS-ManagedIdentity
export AKS_NAME=aks-managedidentity
export KUBERNETES_VERSION=1.15.3
az extension add --name aks-preview
az extension update --name aks-preview
az feature register --name MSIPreview --namespace Microsoft.ContainerService
az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/MSIPreview')].{Name:name,State:properties.state}"
az provider register --namespace Microsoft.ContainerService
az group create --name $RESOURCEGROUP --location AustraliaEast
az aks create --name $AKS_NAME \
     --resource-group $RESOURCEGROUP \
     --node-resource-group "$RESOURCEGROUP-Nodes" \
     --kubernetes-version $KUBERNETES_VERSION --location AustraliaEast \
     --nodepool-name linux --node-count 3 --node-vm-size "Standard_D4s_v3" \
     --load-balancer-sku standard \
     --enable-vmss --enable-managed-identity \
     --network-plugin azure --network-policy azure \
     --ssh-key-value "~/.ssh/id_rsa.pub"
```

**Does this require updates to documentation?:**
Yes.

**Comment by jmspring** [comment]
As currently implemented, the MSI feature for AKS is not ready to be included in Bedrock.  The process makes permanent modifications to the cluster and must be setup *at cluster creation*.  Further, it leverages a custom CLI extension and there is no current support in the AKS terraform provider.

Suggest looking at closer to GA for the MSI for AKS feature.
