### ISSUE TITLE
As a developer, I would like to scaffold out a base infrastructure definition

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#657]
**As a:** developer

**I want:** a way to use spk to scaffold out a base cluster definition.

**So that:** I can have a base definition for creating specific clusters that share information.

**Describe the solution you'd like:** The implementation will be to add the command `spk infra scaffold`.  The initial implementation will take in the following variables:

`name` - the name of the base definition
`source` - a source repository for the deployment definition
`version` - a version of that repository (for specific reference to an implementation that doesn't change)
`template` - a direct path to a `variables.tf` file that will be parsed to create the base definition

**Describe alternatives you've considered:** Eventually (another issue will be filed) rather than hard coding the above information, it should be dynamically discovered.  However, for the moment, the definition of this area is being fleshed out and the simplest implementation is being fleshed out first.

**Does this require updates to documentation?:**
Yes

**Acceptance Criteria:**
- test that verify the variables.tf file can be parsed 
- test that the parsed variables.tf can generate the structure that will eventually be written out in json format

**Comment by yradsmikham** [comment]
The discussion around how to handle cloning Bedrock repos is still open-ended. The goal is to have the `--source` argument be able to accept a git url, in which case it will clone the Bedrock repo, or also have it take in a path to a local Bedrock repo, where it will not need to perform a git clone.
