### ISSUE TITLE
[spk] Support for private repositories and pipelines in introspection tool

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#659]
**Describe the bug:** Unable to use private pipelines/repos with spk 

**Expected behavior:** Everything should work as expected, just as with a public repo/pipelines

**Screenshots:**

**Additional context:** Getting CORS error in the http logs

**Comment by samiyaakhtar** [comment]
After more testing, finding that this error is not occurring on the docker build, which is the method being used for launching via the `spk deployment get` command.

**Comment by andrebriggs** [comment]
@samiyaakhtar Have you figured out the issue and can we create a new issue with concrete steps to fix? Right now it's hard to tell how long this issue will go on

**Comment by samiyaakhtar** [comment]
@andrebriggs closing this one and opened https://github.com/microsoft/bedrock/issues/699 as this one includes the steps to fix it.
