### ISSUE TITLE
Investigate/prototype solution to maintain manifest and cluster parity in a gitops workflow

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#66]
Look at [kubediff](https://github.com/weaveworks/kubediff) (and similar solutions) and come up with a recommendation on how to:

- [x] Deploy
- [x] Execute
- [ ] Be notified of cluster and manifest repo parity

Also so: https://github.com/Microsoft/fabrikate/issues/29

**Comment by andrebriggs** [comment]
@samiya as discussed earlier the pattern recommended on the [Kubediff repo](https://github.com/weaveworks/kubediff) is to run within Kubediff within the cluster (deploying using yaml like [this](https://github.com/weaveworks/kubediff/tree/master/k8s) then have a tool present the results as a Prometheus metric:
 
`Kubediff can also be run as a service on Kubernetes, periodically downloading the latest configuration from Github, comparing it to the running configuration. In this mode Kubediff will also offers a very simple UI showing the output and export the result to Prometheus, all courtesy to prom-run.`

I think we should try a manual deploy to a cluster and verify the flow works. Then we can think how this would fit into the terraform deployment (seems similar to Flux install) and make sure the Prometheus metric is configured with the stack. Thoughts?

An idea for the future:

+ Bedrock cluster deployment supports Kubediff install option
  + The result is a cluster deployed with flux and Kubediff
+ Kubediff runs on the cluster and metrics are captured in Prometheus
  + This is all configured in the Kubediff provided yaml
  + Kubediff polls the manifest repo at a similar interval to Flux
+ Alerts are triggered from consuming Prometheus metrics
  + Azure Monitor? Dashboard? TBD
  + Azure DevOps subscribes to a Prometheus endpoint and triggers something?

cc @sarath-p @mtarng on the above idea and if it fits into your mental model

**Comment by samiyaakhtar** [comment]
I was able to deploy it to a cluster today, it seems like the deployment configs are setup in a similar way to that of flux deployment yaml files. Would this be something that should just be deployed alongside flux at the time of cluster creation? I think that would make the most sense. Especially because our gitops scripts are not cluster aware just yet. I'm thinking about more ways we could have this running as a monitoring system. 

cc @andrebriggs @sarath-p

**Comment by andrebriggs** [comment]
Yes, deploying in the way we do flux is exactly what I was suggesting above, however I would like to see us go end to end with this so there are less unknowns when we assign tasks to others (or do it ourselves). Let's make an alert happen (inconsistent state). Let's see the metrics in prometheus. We can share some screen shots or create a write up.

**Comment by andrebriggs** [comment]
Leaning on #216 to see how to do alert notifications on Prometheus metrics

**Comment by jred55** [comment]
Addressed as part of Spektate dashboard changes
