### ISSUE TITLE
[SPK] Create Dockerfile for Service 

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#661]
**As a:**

Developer

**I want:**

A dockerfile for every new service created in my mono-repo, including the services initialized in `spk project init`.

**So that:**

I can build my services as container images and push them to my container registry

**Describe the solution you'd like:**

- [x] Create a lib util that does a `touch Dockerfile` in a given directory, only if it does not already have a `Dockerfile`.
- [x] `spk project init` should create dockerfiles for all services, using the util from task 1, if they do not have one.
- [x] `spk service create` should create a dockerfile for the new service, using the util from task 1, if it does not exist.

**Describe alternatives you've considered:**

None!

**Additional context:**

In order to automate HLD configuration, we need docker images for services

**Does this require updates to documentation?:**

Absolutely!

**Comment by mydiemho** [comment]
@mtarng 
1. what should be included in the dockerfile? 
1. What base image should we use?
    * alpine
    * ubunu
    * something else?
1. what default dependencies do we want to include?

**Comment by mtarng** [comment]
Comments from @bnookala and Myself:

> hm, i’m thinking that we could just copy a basic Dockerfile for something like node? Obviously whatever we place into that directory will never work with the application code, but it’s mostly for scaffolding and telling users that they need a Dockerfile for builds.

> Any simple “hello world” http server container image should be good enough for the task…
