### ISSUE TITLE
[spk] Documentation for all existing commands

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#662]
**As a:** developer/user

**I want:** to be able to read a guide on how to use the `spk` commands

**So that:** I can run the spk tool

**Describe the solution you'd like:**
Write documentation 

**Does this require updates to documentation?:** Yes

- [x] Service Introspection documentation task: #666 

- [x] Infra documentation task

- [x] Service Creation documentation task

**Comment by evanlouie** [comment]
Do after: #628

**Comment by mtarng** [comment]
We should have a template to follow for each command's documentation. This could be as simple as just saving the `commander` -h outputs, we can use a script to get these, or compile them else where.

Should we create a README in each command where we write short use case stories as well?

@andrebriggs @mydiemho @samiyaakhtar @yradsmikham @jred55

**Comment by andrebriggs** [comment]
@edaena @mtarng @samiyaakhtar @yradsmikham I check off Service introspection as being done on the task list

**Comment by yradsmikham** [comment]
Infra is checked as well.
