### ISSUE TITLE
Terragrunt implementation within bedrock CLI documentation

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#663]
**Describe the solution you'd like:**
As a developer, I want an example of how to implement terragrunt with integration for the existing CLI.

**Describe alternatives you've considered:**
Documentation where `spk infra scaffold` intersects with terragrunt.hcl and instructions on how to address top priority scenarios for deployment and identify necessary guard rails

Related to #656

**Additional context:**
- [x] Private Repository support with VSTS
- [x] Guard Rails
- [x] Common Scenarios
- [x] `spk` operability for terragrunt

**Does this require updates to documentation?:**
Yes

**Comment by NathanielRose** [comment]
- Documentation that captures design approach is provided here - https://github.com/NathanielRose/spk-terragrunt-tests/blob/master/SPK-Infra.md
- Infra Epic has been Updated - https://github.com/microsoft/bedrock/issues/585

**Comment by jmspring** [comment]
Based on the write up - it looks good to me.
