### ISSUE TITLE
E2E Tests -- flush out

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#664]
https://github.com/andrebriggs/bedrock-end-to-end-dx/blob/master/Integration-Test-CLI.md

**Comment by andrebriggs** [comment]
@bnookala @mtarng @bnookala thoughts on https://github.com/andrebriggs/bedrock-end-to-end-dx/blob/master/Integration-Test-CLI.md as a plan? The first test is using the `service create` scenario
