### ISSUE TITLE
Provide guidance on how to set up a bedrock gitops flow with Azure DevOps 

### ISSUE THREAD

**Issue by andrebriggs** [Microsoft/bedrock#67]
Expand on the [README](https://github.com/Microsoft/bedrock/blob/services/gitops/azure-devops/README.md) with detail instruction for steps that we currently can't automate. 

The expectation here is that from scratch one can:

- Create an AKS cluster
  - Reference bedrock cluster instructions
- See an example of a HLD repo and a manifest repo
  - Suggest forking the repos?
  - Suggest repo policies to prevent commits to master
- Set up a build pipeline in Azure Pipelines associated with the HLD repo
  - Set appropriate environment variables
  - Setup a GitHub Personal Access Token
  - Reference provided shell scripts in build pipeline
- Experience a bedrock Gitops flow™
  - Describe how to make a PR against their HLD repo

**Comment by andrebriggs** [comment]
@yradsmikham I went through the steps of creating ADO repos via the CLI. I wrote some instructions [here](https://github.com/andrebriggs/bedrock/blob/ado_doc/gitops/azure-devops/AzureDevOpsGit.md). This is incomplete because I'm waiting to see the code changes your making to the shell scripts to support git repos other than GitHub. Feedback is welcome on what is written so far

**Comment by yradsmikham** [comment]
@andrebriggs I have not submitted a pull request, because I'm still troubleshooting Flux. But check this out: https://github.com/yradsmikham/bedrock/tree/support_azure_repos/gitops/azure-devops

All of my updates regarding support for Azure DevOps repo is here for now.

Will go through your documentation and provide feedback. Thanks!

**Comment by yradsmikham** [comment]
@andrebriggs , updated documentation: https://github.com/yradsmikham/bedrock/blob/support_azure_repos/gitops/azure-devops/README.md

**Comment by andrebriggs** [comment]
@yradsmikham I'm thinking we can combine my documentation and our recent notes in the future.

**Comment by yradsmikham** [comment]
@andrebriggs Yes, let’s combine documentation starting now. Should I just work off of your AzureDevOpsGit.md?
