### ISSUE TITLE
[spk] Update more bedrock projects to use the introspection tool 

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#672]
**As a:** developer in an organization

**I want:** all my pipelines of a Bedrock project sending data to a Spektate storage

**So that:** I can introspect my services

**Describe the solution you'd like:**
Right now, the only project being used by introspection tool is the prototype project for `hello-bedrock` and `hello-spektate`. Start bringing more real projects to use the spk introspection tool.

- [x] a working example end-end of private ADO repos working in a private ADO pipeline
- [x] customer's service introspection tool dashboard and cli working

**Does this require updates to documentation?:** No

**Comment by andrebriggs** [comment]
> a working example end-end of private ADO repos working in a private ADO pipeline

@samiyaakhtar @sarath-p This sounds like an integration test environment. 

We should combine it with the integration env we want to support service management scenarios. How are thinking of creating this environment? 

Something that can be scripted out (e.g. create AzDO project, create repos, setup a sample application that pushes to ACR, Sets up AKS)?

^ This can affect the *effort* of this task. If it makes senses to combine this with other integration environments let's think about it. 

>  service introspection tool dashboard and cli working

Given that the above is setup this is now just a simple test. I see these two task list items as being a 90/10 split in terms of effort. Thoughts?

**Comment by samiyaakhtar** [comment]
@andrebriggs this was created as an effort to help on-board their projects to use the introspection tool after our Tuesday meeting. This isn’t for integration testing, I’m happy to close it if you don’t see it fit anymore, but I opened it because we had decided to do this task next week.

**Comment by sarath-p** [comment]
I think creating specific issues which are blocking the usage of the product would help to address gaps. We can brainstorm the existing gaps to come up with actionable issue list.

**Comment by samiyaakhtar** [comment]
Closing this since we had a successful run of cli and dashboard on 10/24
