### ISSUE TITLE
[SPK] Bug: Error running `spk infra validate` in Windows environment

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#673]
Running `spk init` or `spk infra validate` will fail in Windows environment when attempting to validate prerequisites because it relies on a shell command `which`, which is not native to Windows.

**Comment by andrebriggs** [comment]
@NathanielRose since we know the cause of the bug do we have plan on the steps tp resolve it?

**Comment by NathanielRose** [comment]
Havent put much thought but brute force way may be to grab os-name and pivot between `which` and `where` for the command.

**Comment by evanlouie** [comment]
Use the 'which' function in shelljs (we already use this lib throughout spk)
https://github.com/shelljs/shelljs/blob/master/README.md#whichcommand
