### ISSUE TITLE
[spk] dashboard docker run command does not work on windows

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#674]
**Describe the bug:** `spk deployment dashboard` command does not work on windows since entrypoint script is in shell. 

**To Reproduce:** 
`spk init -f ./spk-config.yaml`
`spk deployment dashboard`
Fails with error `image operating system "linux" cannot be used on this platform`

**Comment by andrebriggs** [comment]
Closing based on chat with @samiyaakhtar
