### ISSUE TITLE
[SPK] service, project, hld commands unit test hardening

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#677]
As a spk 'services' developer, I should have better unit test coverage on commands and libraries I own. Figure out how to test and verify error cases where applicable.

**Comment by andrebriggs** [comment]
@mtarng we should be adding testing goodness every time we touch an area. Creating a task to retrofit testing on existing code is very hard to estimate. Can we just do testing as we code?

**Comment by andrebriggs** [comment]
Closing and linking to this epic #885
