### ISSUE TITLE
Bedrock CLI should support  secure variable group creation

### ISSUE THREAD

**Issue by sarath-p** [microsoft/bedrock#678]
**As a:**
Developer/Operator

**I want:**

A SPK command that will create:
1. A service endpoint for Azure Keyvault
2. Variable group that maps to the values inside of this keyvault.

**So that:**

I can use Azure Key Vault secrets in AzDo pipelines through Variable Group.

**Describe the solution you'd like:**
Be able to manage Service Endpoint and Variable Group from `spk` cli.

Implementation
- [ ] A spk command for creating a service endpoint to an azure keyvault. eg. `spk service-endpoint create --name --subscription-id --subscription-name --service-principal-id --service-principal-secret --tenant_id --org --project --personal-access-token `
- [x] A spk command for creating a variable group that maps to the above key vault. eg. `spk variable-group create --name --type {vsts, azurekeyvault} --variables [key=value key=value] --authorize --description --org --project --personal-access-token `
  - Closed via https://github.com/microsoft/bedrock/issues/649 and https://github.com/microsoft/bedrock/issues/730

**Describe alternatives you've considered:**
Manual process.

**Additional context:**

**Does this require updates to documentation?:**

Yes

**Comment by mtarng** [comment]
related to #730

**Comment by andrebriggs** [comment]
@mtarng any reason we assigned @sarath-p  to this yet you added the effort tagging?

@sarath-p is this still valid?

**Comment by andrebriggs** [comment]
@mtarng @sarath-p Still valid?

**Comment by mtarng** [comment]
This slipped my notifications. I believe this should be an epic that handles both service connection and variable groups. Service connection is low priority as it is mainly used for github connections, which we're not supporting for now. Adding the related tickets for the second task that have been completed.
