### ISSUE TITLE
As a Developer I would like to Update definition.json files as part of `spk infra update`

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#679]
**As a:**
Developer

**I want:**
to update `definition.json` files based on args in a provided template folder (Leaf Deployments)

**So that:**
Terragrunt can update the configuration of Leaf deployments infrastructure.

**Describe the solution you'd like:**
`spk infra update` should provide an argument (e.g. `--template` `definition.json` / or `var`) that will pass the path to the leaf deployment definition to either update the json file or a var within the JSON file

**Additional context:**

`spk infra update --template "~/discover-service/cluster-west" --vars "[cluster-name=new-cluster-west-v2]"`

- [ ] Create `spk infra update` decorator
- [ ] Validate init has been successfully ran
- [ ] Pass a local template path and switch json files with a provided
- [ ] Pass a local template path and a variable map to switch vars in json

**Does this require updates to documentation?:**
Yes

**Comment by NathanielRose** [comment]
Additional context:
 Unit Tests - Invalid Vars mapping, No template found, Multiple var names
 Documentation Update

**Comment by andrebriggs** [comment]
> spk infra update --template "~/discover-service/cluster-west" --vars "[cluster-name=new-cluster-west-v2]"

@NathanielRose what would it look like if someone wanted to update several *vars* in one command?

> Create spk infra update decorator

Does this encapsulate all the implementation or just front end args? Meaning `spk infra update` will accept args but be a no-op. If the latter then that seems like your first place for unit tests.

**Comment by NathanielRose** [comment]
> > spk infra update --template "~/discover-service/cluster-west" --vars "[cluster-name=new-cluster-west-v2]"
> 
> @NathanielRose what would it look like if someone wanted to update several _vars_ in one command?

@andrebriggs the `--vars` arg is passed an array of variables. So something like `spk infra update --template "~/discover-service/cluster-west" --vars "[cluster-name=new-cluster-west-v2, vnet=mynewvnet]"` 

Alternatively we can simply switch out the `hcl` file with one that you pass.  `spk infra update --template "~/discover-service/cluster-west" --hcl "path/to/new/terragrunt.hcl"` 
> > Create spk infra update decorator
> 
> Does this encapsulate all the implementation or just front end args? Meaning `spk infra update` will accept args but be a no-op. If the latter then that seems like your first place for unit tests.

no-op and agreed!

**Comment by andrebriggs** [comment]
> @andrebriggs the --vars arg is passed an array of variables. So something like spk infra update --template "~/discover-service/cluster-west" --vars "[cluster-name=new-cluster-west-v2, vnet=mynewvnet]"

@NathanielRose are we expecting that clients will write this manually on the command like or script this with automation?

Also how many work days do you think `effort - M` is?

**Comment by NathanielRose** [comment]
> > @andrebriggs the --vars arg is passed an array of variables. So something like spk infra update --template "~/discover-service/cluster-west" --vars "[cluster-name=new-cluster-west-v2, vnet=mynewvnet]"
> 
> @NathanielRose are we expecting that clients will write this manually on the command like or script this with automation?

For quick variable changes, they may want to use args, for an extensive amount of vars to be replaced on 1 template they can switch the `.hcl` file. For iteration 1 they would have to handle each update command for that respective template through a script. Down the road, we want to add that scaling mechanism.
> Also how many workdays do you think `effort - M` is?
M= 3-4 Days

**Comment by andrebriggs** [comment]
@NathanielRose still valid?

**Comment by NathanielRose** [comment]
@andrebriggs Since we're handling upgrading templates through spk generate, I dont think this is needed atm. Will put on-hold then close if folks feel otherwise.

**Comment by evanlouie** [comment]
closing to do change in design
