### ISSUE TITLE
[spk] Introspection bash script in pipelines needs simplification

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#686]
**As a:** developer/operator

**I want:** to add a clean bash script into my pipelines

**So that:** my pipelines can send data to my introspection storage

**Describe the solution you'd like:**
Right now, we're making the users go through their pipelines and inject this huge bash task into their pipelines. 
<img width="913" alt="Screen Shot 2019-10-17 at 3 45 46 PM" src="https://user-images.githubusercontent.com/1795990/67053088-32b6b800-f0f5-11e9-8647-cca179850088.png">
If this bash script ends up in the user's pipeline, we can't fix bugs or make changes to it. 

- [x] Move these scripts into a folder in spk that contains them, and make the pipelines download and run this bash script
- ~~Create a working example end-end of a bedrock GitOps pipeline that is running this setup with cleaned up bash scripts, and able to work with introspection tool~~

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
>  Move these scripts into a folder in spk that contains them, and make the pipelines download and run this bash script

@samiyaakhtar this seems small

>  Create a working example end-end of a bedrock GitOps pipeline that is running this setup with cleaned up bash scripts, and able to work with introspection tool

@samiyaakhtar this seems like a larger effort. Why not break this two things up or create a way to ad-hoc test the first item. Creating an entire environment seems a little orthogonal. Marking as `un-scoped`, please remove label when broken up.

**Comment by samiyaakhtar** [comment]
I don’t think the second step is a large step, we have several bedrock pipelines for testing and we just need to update one of them to update storage via service hooks instead of python script. It’s a part of testing the first one. We can’t be confident the first step is done correctly till we see a working example of it

**Comment by andrebriggs** [comment]
@samiyaakhtar I'm thinking that one could wrap this logic below in a shell script as you mentioned. Then test just that shell script by setting up any ENV VAR that is needs. If one can do that, then the script is tested independently, right? 

![](https://user-images.githubusercontent.com/1795990/67053088-32b6b800-f0f5-11e9-8647-cca179850088.png)

Testing the script in the context of a full end to end is different. I'm not sure if we have automated testing for the logic above but the above proposal at least gets us there as the 1st step. Thoughts?

**Comment by samiyaakhtar** [comment]
@andrebriggs Right. Although, the env vars for a shell script ran locally don’t work the same way as variables from a variable group in azure pipelines when passed into a shell script. I’ve tried doing this task before as part of my prototype and there were errors accessing the variables from the shell script. 

If not a full end to end setup, we need at least one working example inside a pipeline. Thoughts?

**Comment by andrebriggs** [comment]
@samiyaakhtar  To be clear I'm thinking practice we would have something like:

`spektate.sh $(Build.BuildId) $(Build.Repository.Name) ...`

In a local test you would have something like 

`spektate.sh 32 test-repo ...`

Essentially the spektate.sh shouldn't refer directly to any AzDO env vars. Where you thinking the same thing and having issues?

**Comment by samiyaakhtar** [comment]
@andrebriggs sure, I'm fine with testing this way. I'll reword the issue

**Comment by samiyaakhtar** [comment]
What if we added a command in `spk`, such as `spk deployment update-storage <data from pipelines that needs to be sent to storage>`? That way, pipelines would download the version of spk that they would like to use if not the latest one (similar to what we do with fab), and execute the command. The logic which currently lives inside a python script can be either moved to typescript (it's simple enough to be re-written in typescript), or called from the spk executable for the time being. Thoughts? 

cc: @andrebriggs @sarath-p @edaena

**Comment by andrebriggs** [comment]
@samiyaakhtar that works too. How are you thinking of loading the necessary configuration? From the global config or have necessary args on the command (account key, table name, etc)  for `update-storage` command?

**Comment by samiyaakhtar** [comment]
@andrebriggs I think maybe just command line works better, so that the task doesn't have to initialize the entire config for introspection, at least for now. Do you think we should go with this method?

**Comment by samiyaakhtar** [comment]
Since we don't want to modify tasks when they're in progress, I'll create a new one for making this a command in `spk deployment`. Leaving this one to remain a simple bash task that downloads and executes a script.

**Comment by samiyaakhtar** [comment]
Opened this task https://github.com/microsoft/bedrock/issues/704 to track the feature discussed above.
