### ISSUE TITLE
Spektate dashboard after running live for a few hours shows only one deployment

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#689]
**Describe the bug:**
When you leave the dashboard running for a while, it only shows one deployment.

**To Reproduce:**
Launch the dashboard and leave it running for a long time. 

**Expected behavior:**
It should continue to show the right number of deployments

**Screenshots:**
<img width="1678" alt="Screen Shot 2019-10-17 at 5 07 14 PM" src="https://user-images.githubusercontent.com/1795990/67056395-a8745100-f100-11e9-98b1-bea42cece2f2.png">

**Additional context:**
There may be a bug in the timer or how deployments are being displayed when some fields are missing. 

**Does this require updates to documentation?:** No

**Comment by samiyaakhtar** [comment]
This seems like a bug with the azure table react component being used to render the deployment table. Refreshing the page solves the issue because the table is loaded out of the bad state it often goes into.

**Comment by andrebriggs** [comment]
@samiyaakhtar is this still an issue?

**Comment by samiyaakhtar** [comment]
@andrebriggs yes, when the page runs for long periods such that it loses network, this bug still triggers.

**Comment by andrebriggs** [comment]
@samiyaakhtar Closing unless we still see this after refactoring
