### ISSUE TITLE
[SPK] Create Service Component in HLD

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#691]
**As a:**

Developer

**I want:**

To create a service component in my HLD

**So that:**

I can create a service using `spk` in my Application Repository, merge the new resources created, and have my new Service appear in my HLD

**Describe the solution you'd like:**

`spk create service` _should_ add a service component by:

- [ ] Adding a directory for my new service in my HLD that maps to my application repository ie:

```
svcA/ (new)
    etc.
component.yaml
```

- [ ] Add a component.yaml in my service directory

```
svcA/ (new)
    component.yaml (new)
component.yaml
```

- [ ] Link my new service by adding it as a subcomponent in my top level HLD

```
svcA/ (new)
    component.yaml (new)
component.yaml (add subcomponent that references svcA)
```

All of these tasks must be performed as a single unit and the artifacts committed as a Pull Request

**Describe alternatives you've considered:**

This can potentially be performed in a pipeline

**Additional context:**

Adding a new service requires us to add it as a subcomponent

**Does this require updates to documentation?:**

Yep

**Comment by mtarng** [comment]
Closing this as Epic https://github.com/microsoft/bedrock/issues/688 and task https://github.com/microsoft/bedrock/issues/718 will cover this work.
