### ISSUE TITLE
[SPK] Create Ring Component in HLD

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#692]
**As a:**

Developer

**I want:**

To create a ring component for my service in my HLD

**So that:**

When I create a service it also adds ring components for all the rings in bedrock.yaml

**Describe the solution you'd like:**

`spk create service` _should_ add a ring component by:

- [ ] In the service directory in the HLD, add a directory for every ring in my bedrock.yaml in 
- [ ] Add a component.yaml in every new directory added, scaffold it with the values encoded in my service's bedrock.yaml
- [ ] Link my rings by adding them as subcomponent in my service level HLD

All of these tasks must be performed as a single unit and the artifacts committed as a Pull Request

**Describe alternatives you've considered:**

This can potentially be performed in a pipeline

**Additional context:**

Adding a new service requires us to add it as a subcomponent

**Does this require updates to documentation?:**

Yea

**Comment by mtarng** [comment]
tagging @bnookala to create directory mocks for acceptance criteria.

**Comment by mtarng** [comment]
Closing as this work is encapsulated by https://github.com/microsoft/bedrock/issues/717
