### ISSUE TITLE
[SPK] Pipeline stage to Update Build ID in HLD repository

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#693]
**As a:**

Developer

**I want:**

Newly built container images to update my component.yaml with the image ID of the container I have built

**So that:**

I can build container images by pushing to a git branch, and have that container image be configured on my HLD

**Describe the solution you'd like:**

My Application Repository -> HLD pipeline should:

- [ ] Be a multi stage pipeline triggered when my build pipeline ( #646 ) is done
- [ ] Configure the service component with the ID of the image that was built when I pushed my code

This task should create a Pull Request against the HLD repository.

**Describe alternatives you've considered:**

A service connection that triggers off of Docker

**Additional context:**

**Does this require updates to documentation?:**

Yea

**Comment by andrebriggs** [comment]
@mtarng @evanlouie how do you plan to invoke PRs for AzDO in the 2nd half of the multi-stage pipeline? Seems like building the multi-stage pipeline YAML is work in itself. You would want to test that manually perhaps first. Seems like something that could be done independently as a separate issue. Thoughts?

> Configure the service component with the ID of the image that was built when I pushed my code

I understand that we have "prior art" for this. This is essentially part of what is going on in the YAML. Think we need to rework the task list (or break into another issue) to represent the YAML work versus the code automation work with SPK.

**Comment by bnookala** [comment]
> Think we need to rework the task list (or break into another issue) to represent the YAML work versus the code automation work with SPK.

@andrebriggs there is no code automation work - we already have commands to create and install a pipeline for services, all of the work needed to update the HLD is strictly modifying the generated pipeline to reflect the necessary operations (build container, and update HLD)

**Comment by bnookala** [comment]
Moreover, we can invoke PRs in a pipeline via the devops CLI: https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/pr?view=azure-cli-latest#ext-azure-devops-az-repos-pr-create

**Comment by andrebriggs** [comment]
@bnookala If there is no code work then there is manual setup (which is fine). Do we have pipeline set up with the specific things we want already? I'm just trying to reduce the unknowns here to be confident about the estimates. Is there a 1 person Issue or a 2 person issue? Can we get a translation of number of days the "effort - M" means?

> Moreover, we can invoke PRs in a pipeline via the devops CLI: https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/pr?view=azure-cli-latest#ext-azure-devops-az-repos-pr-create

@bnookala Do we have code for that already in SPK?

**Comment by mtarng** [comment]
Closing, as this story now duplicates #647
