### ISSUE TITLE
Add support for backend state in HCL file generation for Terragrunt

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#695]
**As a:**
Developer

**I want:**
to be able to add a remote state backend block to the HCL file

**So that:**
Terragrunt can use remote backend terraform state files.

**Describe the solution you'd like:**
As part of the `terragrunt.hcl`, there should be an optional `remote/backend` block if there exists a `backend.tfvars` file in the terraform environment. The `spk infra command` will need to:
- [ ] Generate a backend block as part of the `terragrunt.hcl` if it exists.

**Describe alternatives you've considered:**

**Additional context:**
When a remote backend exists for a terraform environment, the `terragrunt.hcl` should look like the following:

```
remote_state {
    backend = "azurerm"
        config = {
            resource_group_name  = "${get_env("AZURE_BACKEND_RG_NAME", "")}"
            storage_account_name = "${get_env("AZURE_BACKEND_STORAGE_NAME", "")}"
            container_name       = "${get_env("AZURE_BACKEND_CONTAINER_NAME", "")}"
            access_key           = "${get_env("AZURE_BACKEND_ACCESS_KEY", "")}"
            key                  = "spk1.${path_relative_to_include()}/terraform.tfstate"
    }
}

inputs = {
    # BYO Resource Group
    resource_group_name      = "nr-spk-infra-tests-rg"
    agent_vm_count           = "3"
    dns_prefix               = "spk-dns-prefix"
    vnet_name                = "spk-vnet"
    service_principal_id     = "${get_env("AZURE_CLIENT_ID", "")}"
    service_principal_secret = "${get_env("AZURE_CLIENT_SECRET", "")}"
}
```

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@yradsmikham this is `effort - M`. What how many work days (~6 hour work days) would that be for you?

@yradsmikham Is the new functionality the addition of the **bolded**? 
<pre>
<b>
remote_state {
    backend = "azurerm"
        config = {
            resource_group_name  = "${get_env("AZURE_BACKEND_RG_NAME", "")}"
            storage_account_name = "${get_env("AZURE_BACKEND_STORAGE_NAME", "")}"
            container_name       = "${get_env("AZURE_BACKEND_CONTAINER_NAME", "")}"
            access_key           = "${get_env("AZURE_BACKEND_ACCESS_KEY", "")}"
            key                  = "spk1.${path_relative_to_include()}/terraform.tfstate"
    }
}</b>

Do there exist libraries to parse the HCL files?
inputs = {
    # BYO Resource Group
    resource_group_name      = "nr-spk-infra-tests-rg"
    agent_vm_count           = "3"
    dns_prefix               = "spk-dns-prefix"
    vnet_name                = "spk-vnet"
    service_principal_id     = "${get_env("AZURE_CLIENT_ID", "")}"
    service_principal_secret = "${get_env("AZURE_CLIENT_SECRET", "")}"
}</pre>

**Comment by yradsmikham** [comment]
@andrebriggs that's correct. The bolded is the addition made to the HCL file.

Currently, there is not an HCL parser library that I can find compatible with Typescript. So I've been handling the generation using regex.

I could see this being 2-3 days with unit tests included. This will involve parsing the `backend.tfvars`, storing it as an object, and manipulating the object to fit the format of an HCL file via regex.

**Comment by yradsmikham** [comment]
Pivoting away from Terragrunt. Closing issue.
