### ISSUE TITLE
[spk] Fix CORS issue from dashboard

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#699]
**Describe the bug:** When running the dashboard in dev mode and possibly production (when running without the docker build), the private pipelines and repository setup runs into a CORS error while accessing the ADO apis (since the access token header is present, which is not the case for public pipelines/repos)

**To Reproduce:**
Use a GitOps setup that's using Azure DevOps private repos and in a private project. 

**Expected behavior:**
Dashboard should work as expected. 

**Suggested solution:**
- [ ] Create a backend server that sits between the dashboard and the API calls. Dashboard should not be aware of what APIs are being called (whether github/ado etc). 
- [ ] Dashboard should make a call to for eg. /api/deployments?example=1 and get all the responses from the backend server. This will prevent the CORS error since a nodejs server will be making the http request. 
- [ ] The backend server should be running on its own port when launched via the docker image. Make sure docker image can open up two ports.

**Comment by andrebriggs** [comment]
@samiyaakhtar is this still valid? This task was created 3 days ago and was put in Sprint 5 todo https://github.com/microsoft/bedrock/issues/709

**Comment by samiyaakhtar** [comment]
@andrebriggs https://github.com/microsoft/bedrock/issues/709 is actually a different CORS documentation bug, this one is for the CORS error when hitting the ADO apis, and 709 is for the storage table. We only added 709 for this week because it was just a matter of documenting it correctly.

**Comment by andrebriggs** [comment]
@samiyaakhtar still an issue given the new prototype? Regardless can we link this to the epic for the frontend/backend?

**Comment by samiyaakhtar** [comment]
@andrebriggs I think we can close this as a duplicate and link it on the epic.

**Comment by samiyaakhtar** [comment]
Closing this as it's covered as part of https://github.com/microsoft/bedrock/issues/938
