### ISSUE TITLE
resource-group property is missing in spk-config.yaml

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#701]
**Describe the bug:**
`resource-group` is required by service introspection but it's not included in `spk-config.yaml`

**To Reproduce:**

**Expected behavior:**
Include `resource-group` in `spk-config.yaml`

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by samiyaakhtar** [comment]
What portion requires `resource-group`?
