### ISSUE TITLE
find best way to track K8s version in Azure

### ISSUE THREAD

**Issue by jmspring** [Microsoft/bedrock#71]

**Comment by dtzar** [comment]
Not an answer to this question, but I had to do this for another project just thought I'd post this here since it's relevant:
`az aks get-versions -l westus2 --query 'orchestrators[].orchestratorVersion | [-1]'`
gives the latest version number for the region.

**Comment by dtzar** [comment]
Best way to track this is using [this website](https://azure.microsoft.com/en-us/updates/?status=nowavailable&product=kubernetes-service) and the RSS feed on that page. 

@timfpark @jmspring was the goal behind this to once a release happens push the default bedrock version up?

I *think* we could remove the `kubernetes_version` field from the config block as the default option, but then it wouldn't allow people to specify a desired version without doing quite a bit of hacking.

**Comment by dtzar** [comment]
Closing this out per email thread
