### ISSUE TITLE
Build is failing intermittently due to automated test timeout error

### ISSUE THREAD

**Issue by sarath-p** [microsoft/bedrock#711]
**Describe the bug:**
Build is failing intermittently due to async call timeout. 

```
Summary of all failing tests
FAIL src/commands/deployment/dashboard.test.ts (30.597s)
  ● Validate dashboard container pull › Pull dashboard container if docker is installed

    : Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.Error:

      24 | 
      25 | describe("Validate dashboard container pull", () => {
    > 26 |   test("Pull dashboard container if docker is installed", async () => {
         |   ^
      27 |     try {
      28 |       const dashboardContainerId = await launchDashboard(2020);
      29 |       const dockerInstalled = await validatePrereqs(["docker"], false);

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/commands/deployment/dashboard.test.ts:26:3)
```

**To Reproduce:**

**Expected behavior:**
Build should not fail due to timeout errors.

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by samiyaakhtar** [comment]
Can you try increasing the timeout on your machine and test? It's not failing for me with this timeout, but maybe we can increase it more if that helps

**Comment by sarath-p** [comment]
Increasing timeout on my machine doesn't help since it is failing in build pipeline. The test needs to be specified with longer timeout value.

**Comment by samiyaakhtar** [comment]
@sarath-p Feel free to increase timeout in your PR if that helps fix the test

**Comment by sarath-p** [comment]
Already merged the PR so it will need to be fixed in a different PR.

**Comment by andrebriggs** [comment]
@samiyaakhtar @sarath-p how often is intermittent? Is this still going on?

**Comment by samiyaakhtar** [comment]
@andrebriggs I'm not seeing this happen at all, and it looks like it's fixed now. @sarath-p Can you confirm?

**Comment by sarath-p** [comment]
I just checked builds in azdo and I don't see it failing since Wednesday. It probably failed due to an issue in azdo that day.

**Comment by samiyaakhtar** [comment]
@andrebriggs @sarath-p I think we should close this as a non-issue for now?

**Comment by evanlouie** [comment]
closing; fixed by azdo
