### ISSUE TITLE
[spk] Show cluster sync in dashboard and cli

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#712]
**Describe the bug:**
When the flux sync tag is pushed to the manifest repo, the get table or the dashboard should show an indication as to which deployment is synced on the cluster.

**To Reproduce:**
Deploy a manifest repo to the cluster and see if the flux sync status shows up. 

**Expected behavior:**
Cluster sync icon should get updated on the dashboard.

**Additional Context:**
- [x] Make sure this cluster sync status is working for Azure DevOps repos
- [x] Make sure this cluster sync status is working for GitHub repos 
- [x] Utilize the necessary config in spk for users to enter their manifest repo and access token for spektate to pull the flux-sync tag

**Does this require updates to documentation?:** no

**Comment by andrebriggs** [comment]
@samiyaakhtar can we prioritize AzureDevOps repos and split GitHub out to another task? Also is this really a bug or just not implemented?

**Comment by samiyaakhtar** [comment]
@andrebriggs this is just a bug, it's implemented but needs some config params to make it work again, such as github manifest repo name (and possibly access token). I can split GitHub out to another task, if it turns out time consuming.

**Comment by andrebriggs** [comment]
@samiyaakhtar I guess the question is do we know the root cause of the bug If we know the root cause then all that is left is implementation (if we have fix). Do we know the root cause and have code fix in mind?

**Comment by samiyaakhtar** [comment]
@andrebriggs Yes I do, it's more a config plug in from spk into spektate dashboard and package that needs to be done. The work for it is already in place in the spektate package. The bug is mainly to connect the config pieces and test to make sure it works on all types of repos.

**Comment by andrebriggs** [comment]
@samiyaakhtar we have this estimated at size medium so 2 to 3 days. That sounds like implementation. I say we remove the bug label.

**Comment by samiyaakhtar** [comment]
@andrebriggs it was just a slight pessimistic estimate, happy to make it `effort - S` if that makes it easier to scope in
