### ISSUE TITLE
[SPK] Add command to output structured rings and services for repository

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#716]
**As a:**

Developer

**I want:**

A command that I can invoke on SPK that can output a structured list of services and rings.

**So that:**

I can take the output from this command, and consume it via an external tool, like Fabrikate. 

**Describe the solution you'd like:**

- [ ] `spk project dump` or some similar command to read the bedrock.yaml file in the root of the repository and output a structure (which can be dumped to a file later):

```
{
  services: [
    {
      name: "a", // corresponds to ./packages/a
      rings: ["qa", "prod"],
      helm: {
        chart: {
          repository: "some-helm-repo",
          chart: "zookeeper"
        }
      }
    },
    {
      name: "b", // corresponds to ./packages/b
      rings: ["qa", "prod"],
      helm: {
        chart: {
          git: "https://github.com/helm/charts.git",
          path: "incubator/zookeeper",
          sha: "4e61eb234b0ac38956efc1b52a0455a43dba026f"
        }
      }
    },
    {
      name: "c",  // corresponds to ./packages/c
      rings: ["qa", "prod"],
      helm: {
        chart: {
          git: "https://github.com/helm/charts.git",
          path: "incubator/zookeeper",
          branch: "master"
        }
      }
    }
  ];
}
```

Note: the above structure is _suggested_, not required. 

**Describe alternatives you've considered:**
 
None

**Additional context:**

This command is meant to be invoked in a pipeline appliance to reconcile new services. 
In a pipeline appliance, this command is to be invoked in an application repository, with the output being dumped to a file. This file can then be read via a shell script, wherein we can run `fab add` for every service and for every ring. 

**Does this require updates to documentation?:**

Yes

**Comment by mtarng** [comment]
This ticket may not be required if we're handling the logic via SPK.

@bnookala @evanlouie

**Comment by mtarng** [comment]
Going to go ahead and close this ticket as we will be using `spk` to call `fab`
