### ISSUE TITLE
Generate multi node spk template

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#721]
**As a:**
Developer

**I want:**
to generate Terraform files for a multi-cluster based on parent-leaf definitions

**So that:**
I can avoid the need to manually update individual cluster configurations when a shared variable has changed.

**Describe the solution you'd like:**
This is an extension to https://github.com/microsoft/bedrock/issues/749.

Upon generation, `spk infra generate` (e.g. `spk infra generate east`) should:
- [x] Parse `definition.json` from parent directory (current working directory)
- [x] Replicate a hierarchy similar to the target directory. For example:

```
discovery-service
    |- definition.json
    |- east
        |- definition.json
    |- central
        |- definition.json

discovery-service-generated
    |- east
        |- main.tf
        |- variables.tf
        |- spk.tfvars
    |- central
        |- main.tf
        |- variables.tf
        |- spk.tfvars
```
- [x] Iterate through definition.json files from parent and leaf directories
- [x] Write to spk.tfvars for cluster environment

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@yradsmikham @NathanielRose Is there an order dependency with #653 ? They are both marked as medium size. If there is which ones do you anticipate to complete first?

**Comment by yradsmikham** [comment]
@andrebriggs Yes, this is the second part of of the generation and comes after 653.

**Comment by andrebriggs** [comment]
@NathanielRose let's reword the description and title here to be what we called "iteration 2"

**Comment by NathanielRose** [comment]
@andrebriggs Just updated.

**Comment by andrebriggs** [comment]
> Create terraform.tfvars in the generated directory of the final leaf directory from the accumulated variables

@NathanielRose   `terraform.tfvars` or `spk.tfvars`?

**Comment by NathanielRose** [comment]
@andrebriggs Updated.

**Comment by andrebriggs** [comment]
@yradsmikham  @NathanielRose  In the future lets make sure that tasks are scoped and signed off. This task still has "not scoped" as a tag and it jumped into the sprint...The description hasn't been updated in the 10 days since it was labelled "not scoped".  Let's at least make sure the backlog owners remove the tag
![image](https://user-images.githubusercontent.com/3119513/68614858-a6d74800-0476-11ea-80b8-5291dd55e7bd.png)

**Comment by yradsmikham** [comment]
@andrebriggs the description of this issue is accurate, and there is a PR open.

**Comment by andrebriggs** [comment]
@yradsmikham As mentioned before this is useful when folks see the description before the task is started to make sure we are building the right thing. Since there is already a PR we will evaluate the PR but the team loses the chance to add feedback before the PR was created.
