### ISSUE TITLE
Clean up HCL generation in `spk infra scaffold`

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#722]
**As a:**
Developer  

**I want:**
remove HCL generation in `spk infra scaffold`

**So that:**
there aren't unused arguments or functionalities

**Describe the solution you'd like:**
- [x] remove `--hcl` argument

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@yradsmikham is this still valid? Why was it in Prioritized User Stories column?

**Comment by yradsmikham** [comment]
@andrebriggs Yes, this is till valid. Now that we are no longer going with Terragrunt, we should remove code from `spk infra scaffold` to remove any HCL generation. Probably the first thing to do regarding scaffold.

**Comment by NathanielRose** [comment]
Bug:
`spk infra scaffold` is leaving stale files in the spk directory for terragrunt files.
Will be fixed upon HCL generation removal.
