### ISSUE TITLE
[spk] Dashboard queries release API for multistage pipelines

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#723]
**Describe the bug:**
The `spk` dashboard doesn't populate the ACR to HLD column for deployments by multistage pipelines.

**Expected behavior:**
The column contains the information

**Does this require updates to documentation?:**
No

**Suggested implementation**
~~-  Add a config param to spk config, to indicate if the deployment is multistage~~
- [x] If the deployment is multistage, query the build api instead of the releases api (since there's no difference between builds and releases in multi-stage pipelines)

**Comment by edaena** [comment]
Working introspection with multistage deployment pipeline here: [edaena/spartan-app/blob/master/azure-pipelines.yml](https://github.com/edaena/spartan-app/blob/master/azure-pipelines.yml)

The investigation resulted in these new tasks:
[spk Dashboard doesn't populate ACR to HLD for multistage pipelines](https://github.com/microsoft/bedrock/issues/723)

[Spike - Environment specification in multistage pipeline ](https://github.com/microsoft/bedrock/issues/724)

[Multistage pipeline introspection documentation](https://github.com/microsoft/bedrock/issues/725)

**Comment by samiyaakhtar** [comment]
@edaena I don't think you intended to close this task?

**Comment by edaena** [comment]
First iteration of the api change: [microsoft/spektate/pull/47/files#diff-d542d0c936a0a77e7c7d7939c9001545R335-R336](https://github.com/microsoft/spektate/pull/47/files#diff-d542d0c936a0a77e7c7d7939c9001545R335-R336)
