### ISSUE TITLE
Provide support for passing backend remote state using `spk infra generate`

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#728]
**As a:**
Developer

**I want:**
`spk infra generate` to recursively apply remote state configurations for tfstate files from parent directory to sub-directories for terraform deployment

**So that:**
at the final sub-directory, it creates a generated directory and fills the backend tfvars using the backend state variables accumulated from parent and child levels.

**Describe the solution you'd like:**
Upon generation, `spk infra generate` should:

- [x] Check in (parent) current working directory and verifies if it contains a definition.json:
- [x] If so, check the definition for any specification of a backend state. Then, iterate through child directory and create a backend.tfvars file

**Acceptance Criteria:**

When a user runs `spk infra generate east` for example, this should read in the backend configuration in the `definition.json` of the (parent) current working directory, and then apply the backend configuration of the `definition.json` of the `east` cluster. It creates a `generated` directory, with a `backend.tfvars` with the accumulated variables.

**Does this require updates to documentation?:**
Yes.

**Comment by andrebriggs** [comment]
@yradsmikham what the situation with this?

**Comment by yradsmikham** [comment]
@andrebriggs, I plan on working on this later this week. I am re-write the description.

**Comment by andrebriggs** [comment]
@NathanielRose do you agree with the description? cc @yradsmikham

**Comment by NathanielRose** [comment]
@andrebriggs Yes I agree with the description, I was initially unsure whether or not this functionality was in the new Iteration II PR.

**Comment by yradsmikham** [comment]
@andrebriggs @NathanielRose 

If we are all in agreement here, I can start working on this issue at some point today or tomorrow. Thanks y'all! :)

**Comment by NathanielRose** [comment]
Hey, I would like to take this on, But I am realizing due to issues I may be experiencing with the new addition of `spk infra generate` that I mentioned in (https://github.com/CatalystCode/spk/pull/132), that this may be blocked. Since we have a day left, this may need to be pushed to another sprint. Thoughts?

**Comment by yradsmikham** [comment]
@NathanielRose, you're welcome to work on this! I also agree that this item could be pushed to the next sprint given the amount of the time left in our current sprint.
