### ISSUE TITLE
Refactor SPK Service Introspection Config

### ISSUE THREAD

**Issue by sarath-p** [microsoft/bedrock#732]
**As a:**

Developer/Operator

**I want:**

The following SPK Config variables to be refactored.

   - resource_group: Not in use and should be removed.
   - partition_key: The partition key can be internalized within spk/spektate since there will be only one - partition at any point of time in service intropsection based on the current implementation specified
   - table_name: Table name can be internalized without a configurable option since the table is used for service introspection data
   - The following variables can be moved to `azure_devops` section since they are used in service creation area as well. If they are also used in infra, moving to first level makes sense.
       - service_principal_id
       - service_principal_secret
       - subscription_id
       - tenant_id

**So that:**

Reduces number of configurable variables and provides clarity with service principal related variables. 

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by andrebriggs** [comment]
@sarath-p this looks okay but I would discuss with @samiyaakhtar about partition key and table name changes.

**Comment by samiyaakhtar** [comment]
@sarath-p @andrebriggs I think both partition_key and table_name should still be configurable in case they have multiple table storages within the same storage account, and in case they would like to store multiple projects with different partition keys in the same table. While testing, I've used both these scenarios, so removing the configurable option is taking flexibility away. Thoughts?

**Comment by samiyaakhtar** [comment]
@andrebriggs with the new upcoming changes to `spk init`, is this task still needed?

**Comment by andrebriggs** [comment]
Closing @samiyaakhtar
