### ISSUE TITLE
Improve notifications/messages in `deployment get` command

### ISSUE THREAD

**Issue by sarath-p** [microsoft/bedrock#733]
**As a:**

Operator

**I want:**

- [x] `deployment get` to show a message "No deployments found" when no deployments available to show instead of nothing.

- [x]  When introspection is not configured in spk config, the generic message "You need to run `spk init` to initialize." is shown which can be improved by including details like what section/variable is missing in the configuration and inform running the spk init again. Similar to Validate messages would be useful.
- [x] Hide the message `(node:11557) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**So that:**

Know exactly what configuration is missing in spk config file.

** Repro steps **

Run `spk deployment get` with following setup
- no table exist in the storage account
- table exist but empty

From both scenarios, `spk deployment get` shows the following message.

`(node:11557) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Describe the solution you'd like:**

**Acceptance Criteria:**

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by andrebriggs** [comment]
@sarath-p can you please size the task?

**Comment by samiyaakhtar** [comment]
There's already a `No deployments found for specified filters` message shown when no deployments are found.

**Comment by sarath-p** [comment]
From testing these both scenarios 1) no table exist 2) table exist but no data, `spk deployment get` shows the following message.

`(node:11557) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Comment by andrebriggs** [comment]
@sarath-p size estimate?

**Comment by samiyaakhtar** [comment]
@sarath-p That warning comes from a library that's being included by the azure library, which is why a lot of other spk commands are seeing it too

**Comment by andrebriggs** [comment]
@samiyaakhtar can we hide or wrap azure library messages such as 
> (node:11557) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

?

**Comment by samiyaakhtar** [comment]
This has been fixed with the new error codes that were added to all of spk. 

![Screen Shot 2020-04-08 at 3 50 56 PM](https://user-images.githubusercontent.com/1795990/78840879-cedcc000-79b0-11ea-8519-fa18480f6e99.png)
