### ISSUE TITLE
[spk] Introspection dashboard should support filtering

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#736]
**As a:** developer/manager/operator

**I want:** to filter columns such as services, branches, states, environments, author

**So that:** I can get the most relevant information from the dashboard in a short amount of time without having to look for it.

**Describe the solution you'd like:**
- [x] Implement a filter row before the table so the user can apply filters to the table

**Acceptance Criteria:**
User is able to apply filters to the dashboard

**Describe alternatives you've considered:**
User can use filters via the spk cli tool

**Additional context:**
Refer to the UI elements in [azure-devops-ui](https://azdevinternal.azureedge.net/components) library.

**Does this require updates to documentation?:** No

**Comment by andrebriggs** [comment]
@samiyaakhtar do you have a more specific approach in mind on how to apply the filters? Will it be front end filtering or backend? Any idea on the UI control? 

I'm trying to see if there is investigation and items that can be split up.

**Comment by samiyaakhtar** [comment]
@andrebriggs Yes, we plan to use this [filter UI](https://azdevinternal.azureedge.net/components/filter#basic-filter-bar) from azure-devops-ui library
