### ISSUE TITLE
[spk] Introspection npm package needs updated unit tests

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#738]
**As a:** developer/operator on spk

**I want:** to be confident that the code coming from the spektate npm package is well tested

**Describe the solution you'd like:**
- [ ] Move the old unit tests from `src/tests` folder up into the new package
- [ ] Improve unit testing for the libraries such as `Deployment.ts`, `AzureDevOpsPipeline.ts`, and all other files that compute logic in the spektate package.

**Acceptance Criteria:**
- Unit tests in the spektate repo

**Describe alternatives you've considered:**
There used to be unit tests until the CLI was moved over to spk, leaving the rest of code behind

**Does this require updates to documentation?:** No

**Comment by andrebriggs** [comment]
@samiyaakhtar ideally every pull request you make that is related to that area should just have a little goodness in it that works towards closing the testing gap. Creating a task strictly about testings is always difficult. Adding testing after the fact is really add to predict. I'm marking this as low priority and would prefer we incrementally do this when ever we make changes to the area

**Comment by samiyaakhtar** [comment]
@andrebriggs That's right, ideally I don't want to create a task around this. Created this because currently the testing framework is missing from the npm package and pipelines.
