### ISSUE TITLE
[spk] deployment table has holes when a deployment is started by manually committing into HLD

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#739]
**As a:** developer/operator/manager

**I want:** to view the deployment list for commits made into the source repo or HLD repo

**So that:** there are no holes in the table

**Describe the solution you'd like:**
Currently, there are a lot of holes in the table when a commit is made into the HLD manually, since there's no linking prior build and release. 
<img width="1258" alt="Screen Shot 2019-10-30 at 6 45 45 PM" src="https://user-images.githubusercontent.com/1795990/67911934-7ffb4680-fb45-11e9-8192-f6a5194844aa.png">

We may want to consider adding the start time to the table at the very least, and somehow indicating the fact that the missing fields are not an error in the tool. Perhaps we could mark it with `HLD commit` in the service column to indicate that the service name is not known. 

**Acceptance Criteria:**
Do some UX thinking around this area

**Does this require updates to documentation?:** No

**Comment by andrebriggs** [comment]
@gemorris Does this issue make sense to you? cc @samiyaakhtar
