### ISSUE TITLE
As a developer, I want to use `spk infra generate` with private remote directories

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#740]
**As a:**
Developer

**I want:**
`spk infra generate` to generate Terraform scripts for all the infrastructure for a specific deployment from a private source.

**So that:**
I can manage terraform templates in my private remote repo.

**Describe the solution you'd like:**
`spk infra scaffold` should take into account private repo credentials from a PAT provided through `spk.config`. `spk infra generate` should be able to use the provided information and fetch the latest version of a template with the provided PAT token.

**Acceptance Criteria:**
The CLI command should include the following functionality:
- [x] `spk infra scaffold` checks spk.config.yaml for the `access_token` of `azure_devops` and also check for a `infra_repository`
- [x] If the token is not provided assume a public repo
- [x] If `infra_repository` is not provided or an arg is passed as a `source` for `spk infra scaffold` override the `source` 

**Does this require updates to documentation?:**
Yes.

**Comment by andrebriggs** [comment]
@NathanielRose we might want to be more concrete about our approach. It sounds like you want the `scaffold` command to store the args that `generate` will use. Is that the only way to do it?

**Comment by NathanielRose** [comment]
Revised scope for Authentication @andrebriggs @yradsmikham @jmspring :

**Describe the solution you'd like:**
`spk infra scaffold` should take into account private repo credentials from a PAT provided through `spk.config`. `spk infra generate` should be able to use the provided information and fetch the latest version of a template with the provided PAT token.

**Acceptance Criteria:**
The CLI command should include the following functionality:
- [ ] `spk infra scaffold` checks spk.config.yaml for the `access_token` of `azure_devops` and also check for a `infra_repository`
- [ ] If the token is not provided assume a public repo
- [ ] If `infra_repository` is not provided or an arg is passed as a `source` for `spk infra scaffold` override the `source`
