### ISSUE TITLE
Refactor AzDo SDK client connection creation calls

### ISSUE THREAD

**Issue by sarath-p** [microsoft/bedrock#742]
**As a:**

Developer

**I want:**

To use single azdo connection object instead of opening multiple connections.

**So that:**

Entire `spk` code base will reuse existing azdo SDK client connection from a singleton object.

**Describe the solution you'd like:**

Refactor existing azdo client creation calls to use single method that will handle creating connection objects as necessary.

**Acceptance Criteria:**

- [ ] Delete azdoUtil.ts and the places its being used, this functionality already exists in azdoClient
- [ ]  Use azdoClient across commands. Eg. lib/pipeline.ts is creating a connection instead of leveraging azdoClient. Find and fix other places to use azdoClient. Check for usage of the azure-devops-node library

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by andrebriggs** [comment]
@sarath-p has this been done or still necessary?

**Comment by sarath-p** [comment]
@andrebriggs - It is still necessary to improve code reusability and consistency.

**Comment by andrebriggs** [comment]
@sarath-p if I'm understanding correct we have situations where we instantiate new AzDO API connections all in one command and you want to reuse the same connection? If so makes sense. I was a little confused when I read "singleton" since `spk` isn't a long running process

**Comment by sarath-p** [comment]
Yes, `singleton` within a command and also duplicate code that creates `Azdo` API connections. This issue  should aim to achieve both tasks.
