### ISSUE TITLE
Generate single node spk template

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#749]
**As a:**
Developer 

**I want:**
I want to be able to go through end-to-end to generate of an `spk infra generate`.

**So that:**
I can generate Terraform files for a cluster based on a local environment source template.

**Describe the solution you'd like:**

Upon generation, `spk infra generate` should:
- [x] Verify `definition.json` in the project folder
- [x] Verify the tag is reflective of the current local repo
- [x] Check the path to the environment template is valid
- [x] mkdir generated & copy files from an environment template
- [x]  Parse the `definition.json` file to retrieve the `inputs` and create a `spk.tfvar`

See https://github.com/microsoft/bedrock/issues/749#issuecomment-548992820 for more details 

**Acceptance Criteria:**
`spk infra generate` should be able to go end to end with implementation.

```
spk-template
    |- definition.json
spk-template-generated
```

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
After caling `spk infra generate` with args for the terraform repo and repo version we look at the `definition.json` file in the `spk-template-repo`
```
spk-template-repo
    |- definition.json
```
In the `definition.json` we find information about the version of the terraform repo and validate that local git repository. Next we created a `spk-template-repo-generated` directory that is a sibling to `spk-template-repo`
```
spk-template-repo
    |- definition.json
spk-template-repo-generated/
```
Next, we look copy over items from the terraform repo into the `spk-template-repo-generated` directory. 
Our code will generate the `spk.tfvars` file by evaluating what is inside `definition.json`
```
spk-template-repo
    |- definition.json
spk-template-repo-generated/
     |- main.tf
     |- variables.tf
     |- spk.tfvars (generated by SPK infra generate)
```

@NathanielRose correct?

**Comment by NathanielRose** [comment]
@andrebriggs Correct, Adding to issue as well.
