### ISSUE TITLE
`spk infra scaffold` support cloning/syncing functionalities

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#762]
**As a:**
Developer

**I want:**
`spk infra scaffold` to clone the source repository

**So that:**
it can source the appropriate Terraform templates.

**Describe the solution you'd like:**
`spk infra generate` already has a cloning method built out that can be re-used in `spk infra scaffold`.

**Acceptance Criteria:**
When running `spk infra generate`:
- [x] source repo should be cloned to `~/.spk/templates` directory
- [x] the appropriate version should be checked out
- [x] template should be copied from cloned repo

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@yradsmikham it looks like you're already working on this even though it's in the backlog. Did you consider other items on the current sprint?

**Comment by yradsmikham** [comment]
@andrebriggs, that's correct. I figured this one would be an easy addition. In fact, I should have another PR out for it by tomorrow. I have also started working on https://github.com/microsoft/bedrock/issues/721, which is in the backlog as well, but it's dependent on: https://github.com/CatalystCode/spk/pull/124. So once the PR merges, I'll continue working on #721.
