### ISSUE TITLE
`spk infra generate` support populating vars with .env vars or local environment variables in definition.json

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#778]
**As a:**
Developer

**I want:**
Use private secrets that are loaded into my scaffolded definition.json to generate the appropriate variable upon `spk infra generate`.

**So that:**
I don't have to check in my config secrets

**Describe the solution you'd like:**
Load `.env` variables into my JSON and have `spk infra generate` populate them.
```
{
  "name": "discovery-service",
  "source": "https://github.com/Microsoft/bedrock.git",
  "template": "cluster/environments/azure-single-keyvault",
  "version": "v0.12.0",
  "backend": {
    "storage_account_name": "${env:storage-account-name}",
    "access_key": "${env:storage-account-access-key}",
    "container_name": "${env:storage-account-container}",
    "key": "${process.cmd}-tfstate-key"
  },
}
```

**Acceptance Criteria:**

- [x] Use `.env` to load secret configs into generated spk.tfvar files

**Additional context:**
https://github.com/CatalystCode/spk/blob/master/src/config.ts#L41

**Does this require updates to documentation?:**
Yes

**Comment by yradsmikham** [comment]
I'm thinking we can also have it take it environment variables if the `.env` file is not valid or does not exist.
