### ISSUE TITLE
[spk] Introspection dashboard should show last refreshed time for better UX

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#780]
**As a:** developer/operator

**I want:** to know that the dashboard automatically refreshes

**So that:** I don't assume that it always needs a refresh

**Describe the solution you'd like:**
Right now, the dashboard does not indicate that it auto-refreshes, it would be nice to have a last refreshed time somewhere. 
- [ ] Add a last updated time on dashboard

**Acceptance Criteria:**
User is made aware about the time it was last refreshed

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:** No

**Comment by andrebriggs** [comment]
@samiyaakhtar what sprint was this a part of?

**Comment by samiyaakhtar** [comment]
@andrebriggs during the on-site I believe. Although it’s currently a temp solution, should we reopen for a long term solution after working with Glenwood?

**Comment by andrebriggs** [comment]
@samiyaakhtar we can create a new issue when the time comes. Thanks
