### ISSUE TITLE
Integration Testing for `spk infra scaffold`

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#785]
**As an:**
Operator

**I want:**
End-to-End testing that encapsulates `spk infra scaffold`

**So that:**
I can assure new features to infra that are out of scope for a unit test are thoroughly vetted before merged.
 
**Describe the solution you'd like:**

1. Download SPK
2. Write out simple TF Template locally
3. Push TF Template to repo in shared project (e.g. `~/.spk/templates`)
4. Execute `spk infra scaffold`
6. Verify creation of definition file(s).

**Acceptance Criteria:**
- [x] Add infra E2E integration test to AzDO pipeline
- [x] Test scaffold function based on simple Terraform template generated at runtime

**Does this require updates to documentation?:**
Yes (Integration Testing SPK doc)

**Comment by andrebriggs** [comment]
@NathanielRose @yradsmikham I would break this up into 2 separate issues. One for the simplest test of `scaffold` and then one for the simplest test of `generate`. 

Do you think both of those 2 separate tasks would be a medium size? IMHO I think not.

**Comment by yradsmikham** [comment]
@andrebriggs sounds good. I'll modify this issue, and have to capture integration testing for `spk infra scaffold`.

**Comment by andrebriggs** [comment]
@yradsmikham @NathanielRose I believe this task would need documentation updates [here](https://github.com/CatalystCode/spk/tree/master/tests#infrastructure-management)
