### ISSUE TITLE
Traefik2 Fabrikate Component

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#786]
**As a:** operator

**I want:** A Traefik2 fabrikate component to be created under
https://github.com/microsoft/fabrikate-definitions

**So that:** I can that I can have a readily available fabrikate component to
deploy traefik2 with and utilize the Traefik2 IngressRoutes outputted from SPK

**Describe the solution you'd like:**

- A minimal Traefik2 component added to the fabrikate definitions library that
  wraps the https://github.com/containous/traefik-helm-chart helm chart

**Acceptance Criteria:**

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:** Yes -- for the component
created in the fabrikate-definitions repo

**Comment by timfpark** [comment]
I wrote this on the plane on the way over - I will send a PR soon :)

**Comment by timfpark** [comment]
I wrote a Traefik _1_  component in https://github.com/microsoft/fabrikate-definitions/pull/34/files since 2 was not yet released to production per the chart.  Just FYI - let's call the traefik2 definition `traefik2` in the definitions repo because of this.

**Comment by andrebriggs** [comment]
@evanlouie @bnookala @mtarng How close are we to needing this?

**Comment by mtarng** [comment]
@andrebriggs I believe this is a isn't a high priority, as we can work around this by including traefik through a default component in the application monorepository, but ideally it would be easier just to point to a fabrikate definition. 

@evanlouie @bnookala thoughts?

**Comment by bnookala** [comment]
@andrebriggs ingress routes won't work traefik, meaning rings won't work - this is a necessary component (though we can possibly ignore it by deploying manifests statically). regardless the work necessary is really quite small.

**Comment by andrebriggs** [comment]
I'm thinking we should bring this into the next cycle. Any issues with that? @evanlouie @mtarng @bnookala

**Comment by evanlouie** [comment]
agreed. I'll look into next sprint
