### ISSUE TITLE
spk project create-variable-group attempts to create incorrect variable group

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#788]
**To Reproduce:**
Run 
`$ spk project create-variable-group fabrikam-vg -r andrebriggs -d https://dev.azure.com/abrig/spk/_git/fabrikam-hld -u $SP_APP_ID -p $SP_PASS -t $SP_TENANT --org-name $AZDO_ORG --project $AZDO_PROJECT --personal-access-token $ACCESS_TOKEN_SECRET `

Where the variable I want to create is **fabrikam-vg**

The result is 
<pre>
<b>info:    Creating Variable Group from group definition 'abrig'
info:    Creating Variable Group abrig</b>
info:    Attempting to create Variable Group in project 'spk'
(node:9009) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info:    Successfully connected to Azure DevOps Task API!
error:   Failed to create Variable Group abrig
<b>Error: Variable group 'abrig' already exists.
error:   Error occurred while creating variable group
error:   Variable group 'abrig' already exists.</b>
</pre>
**Expected behavior:**
Should create correct variable group

**Does this require updates to documentation?:**
No

**Comment by edaena** [comment]
@andrebriggs no repro in the latest master
Ran:
```
 spk project create-variable-group fabrikam-vg -r $ACR_NAME -d https://dev.azure.com/edaenasj/spk-test -u $SP_APP_ID -p $SP_PASS -t $SP_TENANT --org-name $AZDO_ORG --project $AZDO_PROJECT --personal-access-token $ACCESS_TOKEN_SECRET 
```
Result:
```
info:    Creating Variable Group from group definition 'fabrikam-vg'
info:    Creating Variable Group fabrikam-vg
info:    Attempting to create Variable Group in project 'spk-test'
(node:25407) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info:    Successfully connected to Azure DevOps Task API!
info:    Created Variable Group fabrikam-vg with id: 1
info:    Creating Resource definition for all pipelines to access Variable Group fabrikam-vg
info:    Authorized access Resource definition for all pipelines to access Variable Group fabrikam-vg authorized flag set to true
info:    Creating variable group fabrikam-vg
{
  "variables": {
    "ACR_NAME": {
      "value": "edaenaacr"
...
```

![bug-result](https://user-images.githubusercontent.com/1280985/69223249-def22100-0b2f-11ea-995b-918e9fe4c8fb.png)

**Comment by andrebriggs** [comment]
Closing based upon no repro cc  @edaena @sarath-p
