### ISSUE TITLE
spk doesn't emit non-zero exit code on error

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#789]
**Describe the bug:**

**To Reproduce:**
I run something that [causes a failure](https://github.com/microsoft/bedrock/issues/788):
`$ spk project create-variable-group fabrikam-vg -r andrebriggs -d https://dev.azure.com/abrig/spk/_git/fabrikam-hld -u $SP_APP_ID -p $SP_PASS -t $SP_TENANT --org-name $AZDO_ORG --project $AZDO_PROJECT --personal-access-token $ACCESS_TOKEN_SECRET`

<pre>
info:    Creating Variable Group from group definition 'abrig'
info:    Creating Variable Group abrig
info:    Attempting to create Variable Group in project 'spk'
(node:9130) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info:    Successfully connected to Azure DevOps Task API!
error:   Failed to create Variable Group abrig
<b> Error: Variable group 'abrig' already exists.
error:   Error occurred while creating variable group
error:   Variable group 'abrig' already exists.</b>
$ <b><i>status=$?
$ echo $status
0</i></b>
</pre>

**Expected behavior:**
I expect to see a non-zero exit code when calling $? in bash
> ($?) Expands to the exit status of the most recently executed foreground pipeline.

See more [here](https://www.gnu.org/software/bash/manual/bash.html#Special-Parameters)

Related to https://github.com/microsoft/bedrock/issues/759  --> If we returned easily parsable return information in JSON we could have another way to tell the success of a command. Not necessarily the solution but would help in figuring this out during automation.

**Comment by andrebriggs** [comment]
@dennisseah not sure if you refactoring helped this?

**Comment by dennisseah** [comment]
this is related to a bug from winston logger. https://github.com/winstonjs/winston/issues/228

**Comment by evanlouie** [comment]
status of this? @dennisseah did https://github.com/CatalystCode/spk/pull/214 close this?

**Comment by dennisseah** [comment]
We are unable to fix this because of a bug in winston logger. We have to leave this open until we have a reliable fix. Thanks
