### ISSUE TITLE
spk hld init should create a component.yaml

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#790]
**Describe the bug:**

If we have an empty HLD, the HLD to manifest pipeline will fail to run

**To Reproduce:**

`spk hld init`
`git push`
`spk hld install-manifest-pipeline`
`git commit --allow-empty`
`git push`

HLD to manifest pipeline will fail because hld init does not output a component.yaml

**Expected behavior:**

HLD to manifest pipeline should succeed

**Additional context:**

**Does this require updates to documentation?:**

**Comment by andrebriggs** [comment]
@bnookala is the recommendation that `spk hld init` just needs to add `component.yaml` file? cc @mtarng
