### ISSUE TITLE
CLI deployment filter by service doesn't show results for github repos

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#792]
**Describe the bug:**
`spk deployment get -s service-name` doesn't show results for github repos

**To Reproduce:**
`spk deployment get -s service-name` where service-name is the name of a service in a github repository.

**Expected behavior:**
It shows the correct search result in the table

Seen:
Empty results table

**Does this require updates to documentation?:**
No

**Comment by andrebriggs** [comment]
@edaena @samiya So this only affects GitHub repos? If so let's indicate that in the title

**Comment by samiyaakhtar** [comment]
Not able to reproduce for github configurations. Closing
