### ISSUE TITLE
spk hld install-manifest-pipeline logs errors when no spk config file exists

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#794]
**Describe the bug:**
I get an error message yet the method seems to succeed when there doesn't exist a local spk.config file

**To Reproduce:**

Run the following without calling `spk init` first:

`spk hld install-manifest-pipeline -o $AZDO_ORG -d $AZDO_PROJECT -p $ACCESS_TOKEN_SECRET -r $hld_dir -u https://$hld_repo_url -m https://$manifest_repo_url`

The result is:
<pre>
<b>Error: ENOENT: no such file or directory, stat '/home/vsts/.spk/config.yaml'
warn:    ENOENT: no such file or directory, stat '/home/vsts/.spk/config.yaml'</b>
(node:4695) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info:    Fetched DevOps Client
info:    pipelineDefinition: {"badgeEnabled":true,"triggers":[{"batchChanges":false,"branchFilters":["master"],"maxConcurrentBuildsPerBranch":1,"settingsSourceType":2,"triggerType":2}],"queue":{"name":"Hosted Ubuntu 1604","pool":{"id":224,"name":"Hosted Ubuntu 1604"}},"queueStatus":0,"name":"fabrikam-hld-to-fabrikam-manifests","type":2,"quality":1,"repository":{"defaultBranch":"master","id":"fabrikam-hld","name":"fabrikam-hld","type":"tfsgit","url":"https://dev.azure.com/abrig/spk/_git/fabrikam-hld"},"process":{"yamlFilename":"manifest-generation.yaml"},"variables":{"ACCESS_TOKEN_SECRET":{"allowOverride":true,"isSecret":true,"value":"***"},"REPO":{"allowOverride":true,"isSecret":false,"value":"https://dev.azure.com/abrig/spk/_git/fabrikam-manifests"}}}
info:    Creating pipeline for definition
info:    Created pipeline for fabrikam-hld-to-fabrikam-manifests
info:    Pipeline ID: 82
</pre>

**Expected behavior:**
Either I should not see an error log or I should get a friendly warning messaging telling me to call `spk init` if I really need to. It doesn't seem like I need to.

**Comment by andrebriggs** [comment]
Another case. When I call 

`spk project create-variable-group $vg_name -r $ACR_NAME -d $hld_repo_url -u $SP_APP_ID -p $SP_PASS -t $SP_TENANT --org-name $AZDO_ORG --project $AZDO_PROJECT --personal-access-token $ACCESS_TOKEN_SECRET `

and I remove my spk.config from `~/.spk/spk.config` I see the following errors and warnings even though the command succeeds:

<pre>
<b>error:   An error occurred while loading configuration
 Error: ENOENT: no such file or directory, stat '/Users/andrebriggs/.spk/config.yaml'
warn:    ENOENT: no such file or directory, stat '/Users/andrebriggs/.spk/config.yaml'</b>
info:    Creating Variable Group from group definition 'fabrikam-vg'
info:    Creating Variable Group fabrikam-vg
<b>error:   An error occurred while loading configuration
 Error: ENOENT: no such file or directory, stat '/Users/andrebriggs/.spk/config.yaml'
warn:    ENOENT: no such file or directory, stat '/Users/andrebriggs/.spk/config.yaml'</b>
info:    Attempting to create Variable Group in project 'spk'
error:   An error occurred while loading configuration
<b> Error: ENOENT: no such file or directory, stat '/Users/andrebriggs/.spk/config.yaml'
warn:    ENOENT: no such file or directory, stat '/Users/andrebriggs/.spk/config.yaml'</b>
(node:46021) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info:    Successfully connected to Azure DevOps Task API!
info:    Created Variable Group fabrikam-vg with id: 18
info:    Creating Resource definition for all pipelines to access Variable Group fabrikam-vg
<b>error:   An error occurred while loading configuration
 Error: ENOENT: no such file or directory, stat '/Users/andrebriggs/.spk/config.yaml'
warn:    ENOENT: no such file or directory, stat '/Users/andrebriggs/.spk/config.yaml'</b>
info:    Authorized access Resource definition for all pipelines to access Variable Group fabrikam-vg authorized flag set to true
info:    Creating variable group fabrikam-vg
{
  "variables": {
    "ACR_NAME": {
      "value": "andrebriggs"
    },
    "HLD_REPO": {
      "value": "dev.azure.com/abrig/spk/_git/fabrikam-hld"
    },
    "PAT": {
      "value": null,
      "isSecret": true
    },
    "SP_APP_ID": {
      "value": null,
      "isSecret": true
    },
    "SP_PASS": {
      "value": null,
      "isSecret": true
    },
    "SP_TENANT": {
      "value": null,
      "isSecret": true
    }
  },
  "id": 18,
  "type": "Vsts",
  "name": "fabrikam-vg",
  "description": "Created from spk CLI",
  "createdBy": {
    "displayName": null,
    "id": "2b289f68-3aec-410a-8404-b7eaf6c92137"
  },
  "createdOn": "2019-11-16T01:55:00.626Z",
  "modifiedBy": {
    "displayName": null,
    "id": "2b289f68-3aec-410a-8404-b7eaf6c92137"
  },
  "modifiedOn": "2019-11-16T01:55:00.626Z",
  "isShared": false,
  "variableGroupProjectReferences": [
    {
      "projectReference": {
        "id": "ca459769-cfe0-490c-a89e-1f1eb2eba550",
        "name": "spk"
      },
      "name": "fabrikam-vg",
      "description": "Created from spk CLI"
    }
  ]
}
info:    Successfully created a variable group in Azure DevOps project!
</pre>

**Comment by mtarng** [comment]
Hm, so I think this is because we are configuring all commands to attempt to load the `.spk/config.yaml` that is created from `spk init` everytime we run a command.
