### ISSUE TITLE
bedrock-end-to-end outdated instructions

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#797]
**Describe the bug:**
The following command options in [bedrock-end-to-end-dx](https://github.com/CatalystCode/bedrock-end-to-end-dx) no longer exist:
```
spk project init -m -d services
```

**To Reproduce:**

**Expected behavior:**

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:** Yes

**Comment by andrebriggs** [comment]
Closing since we have a new branch in Bedrock for documentation
