### ISSUE TITLE
Build test infrastructure

### ISSUE THREAD

**Issue by timfpark** [Microsoft/bedrock#8]
We should be able to validate that the project works end to end before and after each commit with a CI system.

Some ideas on how to test a Terraform deployment here:  https://devops.stackexchange.com/questions/863/how-to-test-a-terraform-configuration

**Comment by NathanielRose** [comment]
Investigate Terratest
- [ ] Init integration with Bedrock
- [ ] [Azure Helpers #89](https://github.com/gruntwork-io/terratest/issues/89)
- [ ] Templated infrastructure tests
- [ ] Documentation

**Comment by NathanielRose** [comment]
Confirmed Integration Test
[ ] AKS get credentials
[ ] Ensure Flux pods running (kubectl get po --namespace=flux, make sure pods running)
[ ] Log Analytics add on running

**Comment by andrebriggs** [comment]
@NathanielRose I could see some intersection. We want to make sure our code is tested before any merges to master. I'll schedule time to chat about this

**Comment by drmmarsunited** [comment]
@NathanielRose - way late to anything in this issue, but I noticed it was linking to a Terratest issue that I'd worked on.  Foundational authentication mechanisms for an Azure module were rolled in a little while ago via https://github.com/gruntwork-io/terratest/pull/333.

More helpers to come in the Azure module, but the groundwork is there moving forward.
