### ISSUE TITLE
kube_config_raw revealed in Build Logs

### ISSUE THREAD

**Issue by memonfaheem** [microsoft/bedrock#802]
**Describe the bug:**
Cluster credentials are printed out to the console in the build logs.

**To Reproduce:**
Run `terraform apply` and see the output logs.

**Expected behavior:**
Cluster credentials are saved to the output config without being displayed to the console.

**Screenshots:**
```
module.aks.null_resource.cluster_credentials[0]: Creating...
module.aks.null_resource.cluster_credentials[0]: Provisioning with 'local-exec'...
module.aks.null_resource.cluster_credentials[0] (local-exec): Executing: ["/bin/sh" "-c" "if [ ! -e ./output ]; then mkdir -p ./output; fi && echo \"apiVersion: v1\nclusters:\n- cluster:\n    certificate-authority-data: ...\n    server: https://....hcp.eastus.azmk8s.io:443\n  name: ... \ncontexts:\n- context:\n    cluster: A...\n    user: ...\n  name: ...\nkind: Config\npreferences: {}\nusers:\n- name: ...\n  user:\n    client-certificate-data: ...\n    client-key-data: ...\n    token: ...\n\" > ./output/kube_config"]
module.aks.null_resource.cluster_credentials[0]: Creation complete after 0s [id=6020571218102932175]
```

**Additional context:**

**Does this require updates to documentation?:**
I don't think it would be desired behavior. There should a big red warning in the code if it's the desired behavior.

**Comment by bnookala** [comment]
Thanks for the report, @Faheemitian we'll get this fixed asap.

**Comment by yradsmikham** [comment]
@jmspring @sarath-p Any ideas? Can we get your eyes on this?
