### ISSUE TITLE
SPK Introspection dashboard should show shimmer while deployments are loading

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#808]
**As a:** user

**I want:** to see a user friendly loading view on the deployments table

**So that:** I know that the table is loading 

**Describe the solution you'd like:**
<img width="530" alt="Screen Shot 2019-11-20 at 10 39 23 AM" src="https://user-images.githubusercontent.com/1795990/69227499-2dc8a680-0b82-11ea-8ea6-5de44d929911.png">

- [x] Use [shimmer](https://azdevinternal.azureedge.net/components/table#table-shimmer) to depict loading of the table

**Acceptance Criteria:**
User friendly loading table

**Describe alternatives you've considered:** 

**Additional context:**

**Does this require updates to documentation?:** No

**Comment by andrebriggs** [comment]
@samiyaakhtar do we have an estimate for this?

**Comment by samiyaakhtar** [comment]
@andrebriggs added estimate

**Comment by samiyaakhtar** [comment]
While working on getting this to work, I found that it's only possible to make an entire row a shimmer and not individual cells, so I would like to show this shimmer in author and PR cells since those need an extra API call to be fetched, but the entire row would have to be shimmered. So skipping this step for now. 
Reference: https://azdevinternal.azureedge.net/components/table#table-shimmer
