### ISSUE TITLE
Spike:  Investigate making PR to Flux to add Azure Devops key

### ISSUE THREAD

**Issue by timfpark** [Microsoft/bedrock#81]
Flux has Github and Gitlabs keys baked in by default.  Let's investigate if there is a PR we can make on Flux to add support for Azure Devops so that Azure Devops repos work by default without horsing around with ssh keys.

**Comment by andrebriggs** [comment]
Related to #65 cc @yradsmikham

**Comment by sarath-p** [comment]
weaveworks/flux#1728

**Comment by sarath-p** [comment]
[Flux 1.10.1 release](https://github.com/weaveworks/flux/releases/tag/1.10.1) supports Azure DevOps by default.
