### ISSUE TITLE
`spk infra scaffold` should generate `definition.yaml` that use and exclude default values if provided in .tf files

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#811]
**As a:**
A developer

**I want:**
`spk infra scaffold` to parse, **use**, and _exclude_ the variables with default values in the `definition.yaml` file, instead of inserting a dummy placeholder `<insert value>`.

**So that:**
`spk infra scaffold` can generate a more complete `definition.yaml`, if possible.

**Describe the solution you'd like:**
- [x] Parse and extract the default values of the `variables.tf`, if they exists.
- [x] Generate a `definition.yaml` that excludes variables that have default values. Variables without default values will appear in the `definition.yaml`.

**Acceptance Criteria:**
The `definition.yaml` should use default values. Variables with default values should not appear in the definition file. Variables that do not have default values in the Terraform template will have a placeholder of `<insert value>`.

**Does this require updates to documentation?:**
Yes

**Comment by yradsmikham** [comment]
Revisiting the code, I think this may already be implemented.

**Comment by andrebriggs** [comment]
> Revisiting the code, I think this may already be implemented.

@yradsmikham @NathanielRose what is the status?

**Comment by andrebriggs** [comment]
> > Revisiting the code, I think this may already be implemented.
> 
> @yradsmikham @NathanielRose what is the status?

@yradsmikham @NathanielRose

**Comment by yradsmikham** [comment]
@andrebriggs this is still an issue that needs to be done.
