### ISSUE TITLE
`spk infra` should be using YAML files as opposed to JSON files

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#812]
**As a:**
A developer

**I want:**
`spk infra scaffold` to generate definition in the form of a yaml file and have `spk infra generate` consume yaml files instead of json files.

**So that:**
there is consistency in using yaml files across Fabrikate and Bedrock.

**Describe the solution you'd like:**
- [x] `spk infra scaffold` should produce a `definition.yaml`
- [x] `spk infra generate` should consume `definition.yaml`

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@yradsmikham  @NathanielRose  This task was not scoped but a dependency was created. Moreover this feature was created outside of any planning process. We are now in a position where this task is blocking #778 

This is why we follow a process. I will move to this the prioritized backlog but please for the sake of the SPK team follow the process. There was no reason to do this at the time.

**Comment by yradsmikham** [comment]
@andrebriggs this task is not blocking #778. I could have done them separately, but if code has already been developed for something similar, it only makes sense to hit two birds with one stone.
