### ISSUE TITLE
[spk] Introspection tool should read multiple flux sync tags prefixed by `flux`

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#814]
**As a:** user

**I want:** to see the cluster sync status coming from multiple clusters 

**So that:** I know which deployment is running on all my clusters

**Describe the solution you'd like:**
Right now, the dashboard is only reading the tag `flux-sync` which is default from flux. 
- [ ] Add support to read any tag prefixed with `flux-`
- [ ] Think about how the dashboard should visualize multiple flux-sync tags from the manifest repository and display this information in a meaningful way

**Acceptance Criteria:**
Information about all clusters is available through the tool

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:** No

**Comment by andrebriggs** [comment]
@samiyaakhtar size ?
