### ISSUE TITLE
[SPK] spk hld init should also include traefik by default

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#826]
**As a:**
Developer / Ops person

**I want:**
A initial traefik component to be added to the HLD repository

**So that:**
Ingress Routes will work on the cluster.

**Describe the solution you'd like:**
`spk hld init` should add a default traefik component so that ring routing can be tested.
Eventually this could point to a fabrikate definition when one is created #786 

also add a flag for this option (on or off, which do we want by default?)

**Acceptance Criteria:**

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@mtarng can you add some more detail to this? Size? Why?

**Comment by mtarng** [comment]
Added details @andrebriggs Should I move this to "Ungroomed"?

**Comment by andrebriggs** [comment]
@bnookala @evanlouie @mtarng Is this done?

**Comment by mtarng** [comment]
Closed via https://github.com/CatalystCode/spk/pull/293 and https://github.com/microsoft/bedrock/issues/942
