### ISSUE TITLE
SPK Infra CI/CD needs a Generation Pipeline

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#827]
**As a:**
Operator

**I want:**
to use SPK inside an automated pipeline

**So that:**
I can automate the conversion of definition files to Terraform files

**Describe the solution you'd like:**
A CI/CD that resembles [this](https://github.com/CatalystCode/spk/blob/master/docs/images/spk-infra-cicd.png).

**Generation Pipeline**: A pipeline that will be triggered off of changes made to **Infra HLD Repo**. The pipeline should re-generate Terraform files based off of the changes made to `definition.yaml` files in the Infra HLD Repo, and commit the `generated` directory to **Infra Generated Repo**.

- [x] Create an simple azure-pipelines.yaml that orchestrates `spk infra generate` #871  
- [x] SPK Integration Testing covers infra generation pipeline #872 
~~Investigate File Encryption (e.g. Git Crypt) (_low pri_) #869~~
~~Investigate Keyvault (_low pri_) #868~~

Hierarchy of directories:
```
discovery-service
    |- definition.json
    |- east
```
**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@yradsmikham @NathanielRose  I think this should broken down into separate tasks. Creating a generation pipeline can we a one nugget of goodness. After that creating the deployment pipeline can be another. 

Please break this down with your sizing estimates

**Comment by yradsmikham** [comment]
@andrebriggs sounds good to me. Will break this one up! I'll leave this issue to be the Generation Pipeline. Thanks!

**Comment by andrebriggs** [comment]
@NathanielRose @yradsmikham have we explored [Cobalt](https://github.com/microsoft/cobalt/tree/master/devops/providers/azure-devops)'s terraform pipeline?

**Comment by yradsmikham** [comment]
@andrebriggs @NathanielRose no, I'm not too familiar with it. We can create a spike item for it.

**Comment by NathanielRose** [comment]
@andrebriggs We have updated this issue and modified it into an epic that captures our strategy for the generation pipeline, can you review?

**Comment by andrebriggs** [comment]
@NathanielRose since this is now an epic task this will not be on the sprint. Please link to the tasks in the description  that will fulfill: 
* An azure-pipelines.yaml
* Incorporate Generation Pipeline as part of spk Integration Testing

**Comment by andrebriggs** [comment]
@yradsmikham @NathanielRose I think this is basically done. Agree?

**Comment by yradsmikham** [comment]
@andrebriggs Yes, that is correct. The low-pri items, we can throw into the back burner for now.

Should we remove them from the epic?

**Comment by andrebriggs** [comment]
Closing
