### ISSUE TITLE
Cloning a new repo will not clone all repo branches/tags

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#829]
**Describe the bug:**
Cloning a new repo to `.spk/templates` will only clone the master branch, causing the ability to check out specific repo tags or branches to fail.

**To Reproduce:**

Run `spk infra scaffold` or `spk infra generate` against a new repo.

**Expected behavior:**
Cloning the repo should allow to toggle between branches and repo tags.

**Does this require updates to documentation?:**
No.

**Comment by NathanielRose** [comment]
Hi @yradsmikham, just some clarity on this. Is the ask here to allow specific branches upon cloning due to different releases being associated with respective branches?

**Comment by andrebriggs** [comment]
@yradsmikham do we know the root cause? If we know the root cause we should be able to estimate this

**Comment by yradsmikham** [comment]
@NathanielRose Users are not able to see git tags or branches after they clone.

@andrebriggs No, I am not aware of the root cause here, and am having issues reproducing it. Further investigation is required.

**Comment by andrebriggs** [comment]
What's the status of this? Is it being actively investigated? @yradsmikham @NathanielRose

**Comment by yradsmikham** [comment]
@andrebriggs I have started looking into this, but it has put off due to other tasks this sprint.

**Comment by yradsmikham** [comment]
*Update*: Unable to reproduce in Windows or in Mac OS. Will attempt to reach out to users who experienced this bug for clarification.

**Comment by yradsmikham** [comment]
Users are no longer experiencing this issue with the new spk version. 
Root cause: unknown.
