### ISSUE TITLE
[spk] Introspection dashboard header "Spektate" takes up a lot of real estate

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#834]
**As a:** user

**I want:** to maximize the screen space to view deployments and filters

**So that:** I can view more information on the screen in one go

**Describe the solution you'd like:**
Right now, the Spektate black bar on the top is taking a lot of space, especially on smaller devices. 

**Acceptance Criteria:**

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:** no

**Comment by edaena** [comment]
We can decrease the height of the top bar.

Before:
![spektate-before](https://user-images.githubusercontent.com/1280985/70280412-38cc2b00-176d-11ea-8dfa-885231ed69ca.png)

After:
![spektate-after](https://user-images.githubusercontent.com/1280985/70280423-3e297580-176d-11ea-952a-3483f83ea3a6.png)

**Comment by samiyaakhtar** [comment]
@edaena that may be a good solution for now. @gemorris thoughts?
