### ISSUE TITLE
Integration Testing for `spk infra generate`

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#841]
**As an:**
Operator

**I want:**
End-to-End testing that encapsulates `spk infra generate`

**So that:**
I can assure new features to infra that are out of scope for a unit test are thoroughly vetted before merged.
 
**Describe the solution you'd like:**

1. Download SPK
2. Write out simple definition.yaml file in a simple directory hierarchy
3. Execute `spk infra generate`
6. Verify creation generated Terraform files

**Acceptance Criteria:**
- [x] Add infra E2E integration test to AzDO pipeline
    - [x] Create a simple test repo for templates such as `azure-simple` or `azure-single-keyvault`
    - [x] Create another simple Infra HLD repo with basic definition files in a multi-cluster directory hierarchy
    - [x] Test generate function based on simple definition files to produce generated Terraform files

**Does this require updates to documentation?:**
Yes (Integration Testing SPK doc)

**Comment by andrebriggs** [comment]
@yradsmikham @NathanielRose  When I think about this you have to have an existing TF template repo that the " simple definition.yaml file" is based off of. So a real Git repo must exist. 

Will we be testing private source TF template repos?
Do you plan to start with a multi region/cluster TF  template repo to start with?

**Comment by yradsmikham** [comment]
@andrebriggs that's correct. We will most likely have a simple test repo (simpler than the Bedrock repo) to store templates. It could also be an Azure DevOps repo.

Yes, a multi-cluster template, but not necessarily Bedrock's version of "multi-cluster" template. Multi-cluster in the sense of using `azure-simple` or `azure single keyvault` templates but in the structure of multi-cluster by using a hierarchy of directories.

Private repos can be another iteration of this integration test, or at least until we resolve this [bug](https://github.com/microsoft/bedrock/issues/829).

**Comment by andrebriggs** [comment]
@yradsmikham @NathanielRose let's be specific about that in the description
