### ISSUE TITLE
[spk] Introspection CLI should have support for cluster sync statuses

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#844]
**As a:** user

**I want:** to query via spk cli the cluster sync status of my deployment

**So that:** I can verify that my service is running on the most recent manifest commit

**Describe the solution you'd like:**
Right now, there's support for cluster sync on the dashboard but not in the CLI. 
- [x] Add support for cluster sync feature by supporting it in the CLI just like it's supported in the dashboard.

**Acceptance Criteria:**
User can get cluster sync information without going to dashboard

**Describe alternatives you've considered:**
User would have to launch the dashboard to get this information.

**Additional context:**

**Does this require updates to documentation?:**

**Comment by andrebriggs** [comment]
From looking at the Spektate [code base](https://github.com/andrebriggs/spektate/tree/master/packages/spektate/src/repository), cluster sync objects are referred to as `ITag` objects. We are using a `IRepository` interface to with a `getManifestSyncState` method that is concretely implemented in GitHub and AzureDevOpsRepo descendants of `IRepository`.

Is the idea here to import the Spektate package into SPK and reuse the objects and implementation? 

cc @samiyaakhtar @sarath-p @edaena

**Comment by samiyaakhtar** [comment]
@andrebriggs yes, this should only require building a command and leveraging the existing logic in the package for getting the results

**Comment by andrebriggs** [comment]
@samiyaakhtar Is this something we can pull into the next 2 week sprint?

**Comment by samiyaakhtar** [comment]
@andrebriggs yes, we could, along with https://github.com/microsoft/bedrock/issues/840

**Comment by andrebriggs** [comment]
@samiyaakhtar do you still think this is a medium effort task?

**Comment by samiyaakhtar** [comment]
@andrebriggs updated it to small
