### ISSUE TITLE
Automate adding storage account CORS settings from `onboard` command

### ISSUE THREAD

**Issue by sarath-p** [microsoft/bedrock#855]
**As a:**

Operator

**I want:**

To set storage account CORS setting from `onboard` command

**So that:**

Eliminates manual steps as described here https://github.com/CatalystCode/spk/blob/master/docs/service-introspection-onboarding.md#3-storage-account-cors-settings

**Describe the solution you'd like:**

Automate the step in `onboard` command.

**Acceptance Criteria:**

Set CORS settings if needed either on new or existing storage account.

**Describe alternatives you've considered:**

Manual steps.

**Does this require updates to documentation?:**

Yes

**Comment by samiyaakhtar** [comment]
This should no longer be needed since we have a nodejs backend that makes requests to the storage table.
