### ISSUE TITLE
Bedrock pipeline for integration tests is no longer handling white-listed toggling

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#857]
**Describe the bug:**
In the CI/CD pipeline for Bedrock, the integration tests are no longer being toggled based on PR diff between Master and head node.

**To Reproduce:**
Push PR to a subdirectory that triggers a respective test. The integration test will not be toggled.

Its set when the git diff for the PR is captured. In this commit. All tests are to run and its logged - https://dev.azure.com/epicstuff/bedrock/_build/results?buildId=8570&view=logs&j=cc158a69-e415-5d02-d514-691e0cc44014&t=0ddbddfe-67b7-538d-5060-0315564e27d5&l=41

Yet in the later stage the conditional env var set to Null
```
Evaluating: and(succeeded(), or(eq(variables['AZ_SIMPLE_TEST'], 'true'), eq(variables['ALL_IT_TESTS'], 'true')))
```

**Does this require updates to documentation?:**
No

**Comment by NathanielRose** [comment]
@sarath-p @jmspring @andrebriggs @timfpark  - Multi Job output variables are not supported between stages (https://github.com/MicrosoftDocs/vsts-docs/issues/4466). As a workaround, we were writing pipeline [vars as a published artifact](https://github.com/microsoft/bedrock/blob/master/azure-pipelines.yml#L92-L100) which I believe has stopped working due to a recent update in the pipeline runtime.

One quick fix is to place our Integration Tests all in the 1st stage so our whitelisting vars are passed correctly. I proofed it out [here]( https://naros32.visualstudio.com/spk-testing/_build/results?buildId=82&view=results). The failed tests are due to a golang package issue that may have been created in the months where the integrations tests were not running.

**Comment by andrebriggs** [comment]
@NathanielRose let's create an issue to publish test results for Bedrock integration tests. The reason for this is to highlight when tests are not working earlier. I noticed we have no easy metrics around the history of integration tests
