### ISSUE TITLE
[SPK] Extend service smoke test to test a single application repository

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#859]
**As a:**
Developer
**I want:**
SPK automated tests to test the single application repository use case.
**So that:**
I can be confident that behavior changes will be tested
**Describe the solution you'd like:**
Add a single application repository test to the smoke tests. It should:
- [x] Be a single application repository
- [x] Create a helm chart within the repo and config `bedrock.yaml` with it
- [ ] Deploy variable groups as needed
- [x] deploy the lifecycle and build pipelines for this service, pointing to the same HLD and ACR as the current tests.
- [ ] Validate code changes and builds for this service.

**Acceptance Criteria:**
The tests run and validate changes.

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@mtarng I increased the time estimate
