### ISSUE TITLE
[spk] deployment get command is broken for github repos

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#873]
**Describe the bug:**
`spk deployment get` command is suddenly broken for github repo configurations. 

**To Reproduce:**
system: MacOS
Use a configuration that uses GitHub repositories and run the init command. 
It doesn't repro in ubuntu

**Expected behavior:**
After init, running get command should return some results. 

**Screenshots:**
![Screen Shot 2020-01-09 at 2 36 20 PM](https://user-images.githubusercontent.com/1795990/72110575-687ecd80-32ed-11ea-98e2-cc249fdde0bc.png)

**Additional context:**
Seems to work well for ADO repositories. 

Furthermore, look into why the keyvault is failing on launching the dashboard for certain configurations. 

![Screen Shot 2020-01-09 at 2 37 29 PM](https://user-images.githubusercontent.com/1795990/72110646-919f5e00-32ed-11ea-9110-01e7edb239fe.png)

**Does this require updates to documentation?:**

**Comment by andrebriggs** [comment]
@samiyaakhtar do we know how to fix to justify this as a small effort?

**Comment by samiyaakhtar** [comment]
@andrebriggs this may be `S - M` effort depending on the debugging results to see what is triggering this bug
