### ISSUE TITLE
spk infra scaffold fails to validate remote git sources

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#880]
**Describe the bug:**
Recent changes made to `validateRemoteSource` now takes in a configuration parameter that is not specified in `spk infra scaffold`.

The error:
```
fatal: 'template' does not appear to be a git repository
fatal: Could not read from remote repository.
```

**To Reproduce:**
Execute `spk infra scaffold --name <name of project> --source <git url source> --version <template version> --template <path to template>`

**Expected behavior:**
`spk infra scaffold` should be able to validate the git sources.

**Does this require updates to documentation?:**
No

**Comment by edaena** [comment]
Could this have been detected by some sort of unit test related to the validateRemoteSource workflow?

**Comment by yradsmikham** [comment]
> Could this have been detected by some sort of unit test related to the validateRemoteSource workflow?

It was detected by the spk integration tests :)
