### ISSUE TITLE
[spk] Service pipelines should only use project Variable group

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#887]
**As a:** SPK user and developer

**I want:** service pipelines to only utilize variable groups for variables
instead of those baked into the yaml

**So that:** the utilization of variable groups across lifecycle and service
pipelines is standardized across the project

**Describe the solution you'd like:**

- [x] Refactor `spk service create` to output azure-piplines.yaml that consume
      the variable groups created in `spk project cvg`
- [x] Refactor `spk service create` to remove the `--variable-group-name <variable-group-name` flag, as spk should only use variable groups defined under the project's `bedrock.yaml
- [x] Check if user executed `spk project init` and `spk project cvg` commands before `spk service create` command for dependencies

**Acceptance Criteria:**

refer to task list above

**Describe alternatives you've considered:**

**Additional context:**

[Project commands are now expected to run in order](https://github.com/microsoft/bedrock/issues/886)

**Does this require updates to documentation?:** yes

**Comment by andrebriggs** [comment]
Marking as on hold on until VG issues are fixed

**Comment by andrebriggs** [comment]
@sarath-p @evanlouie @mtarng @bnookala  If working this feature is going to interfere with potential bug fixes then we need to prioritize the bug fixes and put this on hold. Let's discuss on Monday
