### ISSUE TITLE
Smoke tests pipelines only use variable groups

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#888]
**As a:** SPK developer

**I want:** the pipelines created/used in the integration/smoke tests to only
use variable groups instead of passing them in directly via flags.

**So that:** the realignment to only using variable groups is reflected in the
smoke tests and that any usage of flag based variable passing does not break the
tests when the removal of said flags occurs.

**Describe the solution you'd like:**

Look through the smoke tests usage of `spk project install-lifecycle-pipleline`
and `spk service install-build-pipeline` and ensure their is no flag usage for
variable setting in the created pipelines. Instead they should use the values
contained in the variable group from `spk project cvg`

**Acceptance Criteria:**

No flags are used to pass values to any created azure-pipelines.yaml files when
the variable group created via `project cvg` could be used instead.

**Describe alternatives you've considered:**

**Additional context:**

- https://github.com/microsoft/bedrock/issues/839
- https://github.com/microsoft/bedrock/issues/886
- https://github.com/microsoft/bedrock/issues/887

**Does this require updates to documentation?:** No

**Comment by evanlouie** [comment]
@andrebriggs as this place `on-hold` last week; are we still okay to pick this up?

**Comment by andrebriggs** [comment]
@evanlouie please add a size to it

**Comment by sarath-p** [comment]
Reviewed [validations.sh](https://github.com/CatalystCode/spk/blob/master/tests/validations.sh) and found no arguments to be removed since all of them are required to install pipelines. 
cc: @andrebriggs, @mtarng
