### ISSUE TITLE
spk deployment create and get integration test

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#891]
**As a:**
Developer

**I want:**
To validate `spk deployment create` and `spk deployment get` in the integration tests

**So that:**
I am confident about the functionality

**Describe the solution you'd like:**
Add the integration tests [here](https://github.com/CatalystCode/spk/tree/master/tests).
- [x] Update the tasks in the pipelines to include the step that runs `spk deployment create`
- [x] test the data retrieved from `spk deployment get` to make sure data was inserted and retrieved

**Acceptance Criteria:**
The test run successfully in the existing test pipeline.

**Does this require updates to documentation?:**
Yes

**Comment by samiyaakhtar** [comment]
@edaena @andrebriggs 
While working on integration testing the create command, it's essential for the `create` command to exist within the pipelines that are generated in the integration test. In order for this integration test to be implemented, we first need to prioritize https://github.com/microsoft/bedrock/issues/621 such that the scripts are present in the pipelines that are generated in the test. 

Can we prioritize 621 for this week's sprint?

**Comment by andrebriggs** [comment]
Done @samiyaakhtar are you saying you are blocked on this task. If so I can mark it as so
