### ISSUE TITLE
Generation fails to inherit leaf definitions when there is only 1 variable in the parent and leaf definition.yaml files

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#902]
**Describe the bug:**
When there is only 1 variable in the parent and leaf definition.yaml files, spk infra generation will produce a `spk.tfvars` with parent variables to take precedence.

**To Reproduce:**
Have a parent definition.yaml with one variable, and a leaf definition.yaml with one variable. Execute `spk infra generate -p <region>` and create a generated directory. The parent variable will take precedence in the `spk.tfvars` file.

**Expected behavior:**
Leaf definitions should always take precedence.

**Does this require updates to documentation?:**
No

**Comment by andrebriggs** [comment]
@dennisseah This might be good to look at cc @yradsmikham @NathanielRose
