### ISSUE TITLE
spk onboard smoke test fails on storage account name

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#903]
**Describe the bug:**
The spk onboard test sometimes fails if there storage account name exists in azure (under a different resource group of a different user).

**To Reproduce:**

**Expected behavior:**
No storage account name errors when running the spk onboard test.

- [x] fix storage account name bug

- ~~enable the integration test in the integration test pipeline~~

- [x] use an existing storage account

- [x] test the onboard table workflow only

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@edaena if we know the root cause let's describe a proposed fix. We should have an estimate

**Comment by edaena** [comment]
Given that we need:
-a unique storage account name
-to be able to map a storage account name to a test run
-delete the storage account after the test runs

We could have a case where the test fails and we have stale storage accounts on azure. Given this, the test will assume a given storage account exists and it will only exercise the onboard table scenario, where it will create the table required for introspection.
