### ISSUE TITLE
spk service create should ask for display name when path is "."

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#904]
**As a:**

SPK user

**I want:**

My tool to ask me for a display name if I provide the path as simply just "."

**So that:**

My HLD reconcile pipeline can create service components in my HLD using the display name

**Describe the solution you'd like:**

`spk service create .` (without the -n for display name)

Should trigger an error, asking that the user provide a display name via the `-n` parameter.

**Acceptance Criteria:**

- [x] `spk service create .` (without -n) triggers an error and exits
- [x] `spk service create . -n myServiceName` does not trigger an error.

**Describe alternatives you've considered:**

none

**Additional context:**

To prevent issues further downstream, we are adding this safe guard

See: https://github.com/microsoft/bedrock/issues/898 for how the reconcile pipeline handles the lack of a displayName config parameter

**Does this require updates to documentation?:**

yes

**Comment by jmspring** [comment]
@andrebriggs @jred55 This is a critical need, the UI/UX on this and overall opaqueness of the docs (from the cli) on how this impacts *where* the pipeline expects the yaml file to be is not clear.

**Comment by mtarng** [comment]
Can you expand on that @jmspring ? What is the critical need from this ticket, this work has already been released.  

If you're referring to the confusion between service name and directory, then I agree. That's this ticket here: https://github.com/microsoft/bedrock/issues/943
