### ISSUE TITLE
SPK failure in create-variable-group.test.ts

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#905]
**Describe the bug:**
The a unit test failed in the [SPK build](https://dev.azure.com/epicstuff/bedrock/_build/results?buildId=10109&view=logs&j=f164dbd1-368a-58ba-3795-906e0bb83435)

The SPK build also did not immediately fail, instead it hanged after the message `This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.` was displayed. I manually cancelled the build.
 
```
Summary of all failing tests
FAIL src/commands/project/create-variable-group.test.ts (7.383s)
  ● create › Should pass with empty variable group arguments

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      208 |   });
      209 | 
    > 210 |   test("Should pass with empty variable group arguments", async () => {
          |   ^
      211 |     const accessOpts: IAzureDevOpsOpts = {
      212 |       orgName,
      213 |       personalAccessToken,

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/commands/project/create-variable-group.test.ts:210:3)


Test Suites: 1 failed, 35 passed, 36 total
Tests:       1 failed, 311 passed, 312 total
Snapshots:   0 total
Time:        54.169s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
**To Reproduce:**
I assume this must be an intermittent bug.

**Expected behavior:**
There test should pass and if possible made to be less complicated if it requires async behavior that can cause the test runner to hang.

**Screenshots:**
Screenshot below shows a 7+ minute build due to hanging:
![image](https://user-images.githubusercontent.com/3119513/73126815-f43e5e00-3f6b-11ea-81e3-031e54956085.png)

**Comment by dennisseah** [comment]
Note: this failure is sporadic.

@sarath-p , can you shed some lights on this test, https://github.com/CatalystCode/spk/blob/master/src/commands/project/create-variable-group.test.ts#L210, is this test supposes to pass or throw exception? Currently it is throwing exception at 
```
const taskClient: ITaskAgentApi = await TaskApi(opts);
```
https://github.com/CatalystCode/spk/blob/master/src/lib/pipelines/variableGroup.ts#L177
and the exception message is "TypeError: Cannot read property 'value' of null"
thanks

**Comment by andrebriggs** [comment]
In the resolution of this bug we should put a timeout on the `YARN TEST` stage of the pipeline.

**Comment by sarath-p** [comment]
@dennisseah - the below test is passing correct arguments to the method, but it will get an exception in unit testing since it is not connecting to `Azdo` project. I think we should remove `empty` in the test title to remove the confusion. 
Thanks!
