### ISSUE TITLE
SPK install-build-pipeline issue around location of azure-pipelines.yaml file

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#906]
**Describe the bug:**

This [line](https://github.com/CatalystCode/spk/blob/93ddacdc77aa9513ff49e89f92d1ef00280050b0/src/commands/service/pipeline.ts#L213) seem to assume that in a non-mono repo we would still have a `services` directory instead of just having `azure-pipeline.yaml` exist at the top level of the repository.

**To Reproduce:**

When you have a single application repository (not a mono-repo)

`spk service install-build-pipeline -o abrig -u https://dev.azure.com/abrig/spk/_git/fabrikam-frontend -d spk -p REDACTED -n fabrikam.frontend.pipeline fabrikam-frontend`

```bash
warn:    Error loading SPK configuration file; run `spk init` to initialize your global configuration or ensure you have passed all required parameters to the called function.
(node:4624) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info:    Fetched DevOps Client
info:    Creating pipeline for definition
info:    Created pipeline for fabrikam.frontend.pipeline
info:    Pipeline ID: 416
error:   Could not queue the build because there were validation errors or warnings.
error:   Error occurred when queueing build for fabrikam.frontend.pipeline
error:   Error queueing build
```

**This happens with the latest master build of SPK**

The build cannot be queued because AzDO cannot find the `azure-pipeline.yaml` file. The `azure-pipeline.yaml` file exists at the top level of the repo, **not** under the directory `fabrikam-frontend`. The image below shows the issue:

![image](https://user-images.githubusercontent.com/3119513/73129044-91f75480-3f8f-11ea-8e8a-1de718cd13f9.png)

**Expected behavior:**
SPK allow build pipelines to be created with a `azure-pipeline.yaml` file living at the top level of a single application repository

**Comment by mtarng** [comment]
spk command should be:`spk service install-build-pipeline -o abrig -u https://dev.azure.com/abrig/spk/_git/fabrikam-frontend -d spk -p REDACTED -n fabrikam.frontend.pipeline .`

**Comment by andrebriggs** [comment]
> spk command should be:`spk service install-build-pipeline -o abrig -u https://dev.azure.com/abrig/spk/_git/fabrikam-frontend -d spk -p REDACTED -n fabrikam.frontend.pipeline .`

@mtarng This corrected the issue

What are you thoughts on having to specify the dot? Can we default to dot if nothing is provided?

**Comment by mtarng** [comment]
i don't believe so. The way `commander works` is it requires a "service name" which is actually the directory.

`spk service create` results in
`error: missing required argument 'service-name'`

We're indexing services based on directory path. If this is the root repository path, then the service will be index and named `.`, unless a display name is also given.
