### ISSUE TITLE
Silent error related to Fabrikate in update_image_tag stage of SPK install-build-pipeline 

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#908]
**Describe the bug:**
Related to #906 #907 #900

The `spk install-build-pipeline` produced `azure-pipelines.yaml` file has an error related to `fab set` and it doesn't fail the build. Screenshot below of "passing" build:

![image](https://user-images.githubusercontent.com/3119513/73129378-10a3c000-3f97-11ea-8568-d9f5dc6a779a.png)

A closer look at the build log snippet that contains the failure:
```
GIT PULL ORIGIN MASTER
From https://dev.azure.com/abrig/spk/_git/fabrikam-hld
 * branch            master     -> FETCH_HEAD
Already up to date.
Switched to a new branch 'DEPLOY/fabrikam-frontend-master-20200126.1'
Error: 'set' takes one or more key=value arguments and/or a --file
Usage:
  fab set <config> [--subcomponent subcomponent] [--file <my-yaml-file.yaml>] <path1>=<value1> <path2>=<value2> ... [flags]

Flags:
      --environment string    Environment this configuration should apply to (default "common")
  -f, --file string           Path to a single YAML file which can be read in and the values of which will be set; note '.' can not occur in keys and list values are not supported.
  -h, --help                  help for set
      --no-new-config-keys    'Prevent creation of new config keys and only allow updating existing config values.
      --subcomponent string   Subcomponent this configuration should apply to

```

The outcome is that the resulting PR doesn't have the expected commits. The commits should be an update of the Docker image tag number on the HLD. With out the HLD repo doesn't have the correct version of applications.

**To Reproduce:**
See #906 #907

**Expected behavior:**
We should be making correct commits on the HLD repo that represent updated Docker image tags

**Comment by bnookala** [comment]
a correct invocation of the `fab set` step is likely similar to this:

```fab set --subcomponent "$REPOSITORY.$SERVICE_NAME.$RING.$CHART_NAME image.tag=$(Build.SourceBranchName)-$(Build.BuildNumber)```

**Comment by mtarng** [comment]
Should be coupled with #945.

This ticket's AC should be that pipelines fail when there are errors running the bash scripts. Add `set -e` for all pipelines.

#945 's work is aligned with making sure hld reconcile correctly sets the image.tag for the right component via fabrikate.
