### ISSUE TITLE
Manifest generation pipeline should support optional variable group

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#912]
**As a:** developer

**I want:** to create the hld pipeline with a variable group

**So that:** the hld -> manifest pipeline can use my optional variable group to perform custom tasks, such as introspection storage update

**Describe the solution you'd like:**
Right now, the generated pipeline yamls for src -> acr -> hld support taking in a variable group. There's currently no support for manifest generation to have a variable group since multiple services will be using it, need some thinking around this. 
- [x] Perhaps allow an optional flag in `spk hld init` to pass in a variable group name. 
- [x] Update the integration tests

**Acceptance Criteria:**
Manifest generation pipeline allows specifying a variable group 

**Describe alternatives you've considered:**
Considered the option of manually doing this as part of integration tests. 

**Additional context:**
append-variable-group

**Does this require updates to documentation?:** No

**Comment by samiyaakhtar** [comment]
@andrebriggs @mtarng 
Just creating this issue as it came around while working on https://github.com/microsoft/bedrock/issues/621 and integration testing. Feel free to add your thoughts

**Comment by mtarng** [comment]
Could also have tasks:
- [ ] Add an optional flag in `spk hld init` to pass in a variable group name that will be added to the hld's `manifest-generation.yaml`.
- [ ] Add a new command to add the variable group after initialization. `spk hld add-variable-group <my-new-vg>`.

We do have some similar logic that exists for the second task where we run `spk project init` then `spk project create-variable-group` and add the new variable group referenced in `bedrock.yaml` to the project's `hld-lifecycle.yaml`.

@evanlouie @bnookala @sarath-p

**Comment by sarath-p** [comment]
@mtarng - i think we can use a higher level `spk variable-group` command instead of additional commands under each resource. `spk variable-group` command also replaces `spk project cvg`. As part of this refactoring, we can make `spk variable-group` more generic to take `n` number of key/value` pairs for variables in the group.

> * [ ]  Add a new command to add the variable group after initialization. `spk hld add-variable-group <my-new-vg>`.

**Comment by andrebriggs** [comment]
I like @sarath-p's idea to use the existing spk variable-group. @sarath-p do we have a task for cleaning up `spk variable-group` and `spk project cvg`

cc @mtarng @samiyaakhtar

**Comment by sarath-p** [comment]
@andrebriggs - we could use #796 which will need to be updated with desired outcome. 

Related to #796,and #678

**Comment by samiyaakhtar** [comment]
@sarath-p @andrebriggs using the existing spk variable group command is a good idea, although does it support (or plan to) an open ended list of key value pairs to be added to the VG?

**Comment by andrebriggs** [comment]
Let's implement `spk hld add-variable-group <my-new-vg>`cc @mtarng @edaena @samiyaakhtar

**Comment by mtarng** [comment]
https://github.com/CatalystCode/spk/blob/master/tests/validations.sh#L156 should be updated once this is in. Use the new `spk hld add-variable-group` command instead.
