### ISSUE TITLE
SPK should support private helm chart repos at service creation

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#914]
**As a:**
Developer

**I want:**
SPK to automatically create a `access.yaml` file when  defining a helm chart repository in the `spk service create` command

**So that:**
I will not have to manually see my HLD to Manifest pipeline fail when I reference a private helm chart repository. 

**Describe the solution you'd like:**
Ideally I wouldn't want to have to look into the Fabrikate tool repository to [discover](https://github.com/microsoft/fabrikate/blob/master/docs/auth.md#authentication--personal-access-tokens--accessyaml) that I need to do an additional step.

**Acceptance Criteria:**
I can specify a secure ENV VAR that is linked to a variable group and have the HLD to Manifest pipeline inject this ENV VAR when calling `fab install` and `fab generate` commands. `spk` should scaffold an `access.yaml` file that has a mapping of helm chart URLs to ENV VARs that represent an git repository access token 

Ideally I can specify this at the time of `spk service create` 

**Describe alternatives you've considered:**
Manually updating the HLD and manually testing.

**Does this require updates to documentation?:**
Yes

related to #805

**Comment by andrebriggs** [comment]
@bnookala My suggestion in the description is one way to do it. Did you have any way you were thinking?

**Comment by mtarng** [comment]
- Add a --access-token-variable option that is an environment variable for `spk service create` that gets tracked in bedrock.yaml
- If its not present, log a warning during service create time
- If its not present, default to ACCESS_TOKEN_SECRET and still scaffold an entry in access.yaml during reconcile time in the lifecycle pipeline.
- To check: currently the hld to manifest generation pipeline does not have a variable group. Do we create one with another `spk hld add-variable-group` or `spk hld create-variable-group`?
