### ISSUE TITLE
SPK service create should validate helm chart repo is valid URL format 

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#915]
**Describe the bug:**
If the helm chart repo doesn't have `http://` or `https://` Fabrikate will not recognize it. This could be a Fabrikate issue instead. Depends where it should be fixed.

## No `http://` or `https://`
```
INFO[27-01-2020 18:59:07] 🚁  Component 'chart' requesting helm chart in path 'dev.azure.com/abrig/spk/_git/helm-charts' from git repository 'master' 
INFO[27-01-2020 18:59:07] 🚁  Component requested latest commit: fast cloning at --depth 1 
INFO[27-01-2020 18:59:07] 🚁  Component requested branch 'master'       
INFO[27-01-2020 18:59:07] 🚁  Cloning dev.azure.com/abrig/spk/_git/helm-charts@master:head => /var/folders/lj/9dqdzw193jg2jhjp9x19fyb00000gn/T/b985f7d6-2cb1-4f33-a80f-42cc5e02483f 
ERRO[27-01-2020 18:59:07] 🚫  Error occurred while cloning: 'dev.azure.com/abrig/spk/_git/helm-charts@master:head'
exit status 128: fatal: repository 'dev.azure.com/abrig/spk/_git/helm-charts' does not exist 
Error: exit status 128
Usage:
  fab install [flags]

Flags:
  -h, --help   help for install

Global Flags:
  -v, --verbose   Use verbose output logs

ERRO[27-01-2020 18:59:07] exit status 128  
```

## With `http://` or `https://`
```
INFO[27-01-2020 19:00:14] 🚁  Component 'chart' requesting helm chart in path 'http://dev.azure.com/abrig/spk/_git/helm-charts' from git repository 'master' 
INFO[27-01-2020 19:00:14] 🚁  Component requested latest commit: fast cloning at --depth 1 
INFO[27-01-2020 19:00:14] 🚁  Component requested branch 'master'       
INFO[27-01-2020 19:00:14] 🚁  Cloning http://dev.azure.com/abrig/spk/_git/helm-charts@master:head => /var/folders/lj/9dqdzw193jg2jhjp9x19fyb00000gn/T/fd753910-6f47-4f69-a9ac-ce517e2c2fbb 
INFO[27-01-2020 19:00:14] 🚚  Copying /var/folders/lj/9dqdzw193jg2jhjp9x19fyb00000gn/T/fd753910-6f47-4f69-a9ac-ce517e2c2fbb => /Users/andrebriggs/Code/spk-ab/tests/spk-env/fabrikam-hld/fabrikam-frontend/fabrikam-frontend-service/master/helm_repos/chart 
INFO[27-01-2020 19:00:14] 🚁  Updating helm chart's dependencies for chart in '/Users/andrebriggs/Code/spk-ab/tests/spk-env/fabrikam-hld/fabrikam-frontend/fabrikam-frontend-service/master/helm_repos/chart/fabrikam-frontend/chart' 
INFO[27-01-2020 19:00:14] 👈  Finished install for component: chart     
INFO[27-01-2020 19:00:14] ✅  Installed successfully: fabrikam-frontend-service 
INFO[27-01-2020 19:00:14] ✅  Installed successfully: master            
INFO[27-01-2020 19:00:14] ✅  Installed successfully: static            
INFO[27-01-2020 19:00:14] ✅  Installed successfully: chart             
INFO[27-01-2020 19:00:14] 🙌  Finished install       
```
**To Reproduce:**
Run `spk service create . -n "$repo_dir_name-service" -p "$repo_dir_name/chart" -g $helm_repo_url -b master` where `$helm_repo_url` does not have `http://` or `https://`

Git push changes. let build pipelines run and approve PR. Look at HLD to Manifest repo

**Expected behavior:**
Either validation should have in `spk service create` or we open a bug in Fabrikate.

**Does this require updates to documentation?:**
YES

**Comment by bnookala** [comment]
hmmm - yeah this could probably be captured in `spk service create`

**Comment by andrebriggs** [comment]
@bnookala  In addition to an initial validation on `spk service create` every time we decide to read from `bedrock.yaml` we should be doing a validation since the file can be manually edited.

**Comment by evanlouie** [comment]
What kind of validations were we thinking? Git URLs very widely depending on provider and specifying  any sort of validations could be troublesome.

In the example given by @andrebriggs, that is not a valid git URL (ie, you can't do `git clone dev.azure.com/abrig/spk/_git/helm-charts`, that will error out with `fatal: repository 'dev.azure.com/abrig/spk/_git/helm-charts' does not exist`)

**Comment by andrebriggs** [comment]
@evanlouie let's match what git expects and change if needed. 

@bnookala I see you removed yourself from this. Is this still in progress?
