### ISSUE TITLE
Remove DeprecationWarnings from SPK output

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#924]
is it possible to supress (or even better fix) these warnings:
```bash

(node:1579) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

It would be good for us to look into this 

cc @evanlouie @dennisseah

**Comment by evanlouie** [comment]
In order to suppress this warning, add the following to the top of `src/index.ts`

```ts
// Hide deprecation warnings
(process as any).noDeprecation = true;
```
ref: https://nodejs.org/api/process.html#process_process_nodeprecation
