### ISSUE TITLE
Clone a Javascript Object

### ISSUE THREAD

**Issue by dennisseah** [microsoft/bedrock#933]
**As a:**
Developer

**I want:**
Clone a Javascript object like a commonly used function in `lodash`, 'cloneDeep`

**So that:**
this simplify code and make code more readable.

**Describe the solution you'd like:**
I will like to use third parties library, `lodash` which is the most commonly used library by nodeJs 
developers. Otherwise we would have to write a common helper function.

**Acceptance Criteria:**
Implement the helper function and with adequate tests

**Does this require updates to documentation?:**
No

**Comment by bnookala** [comment]
@dennisseah I'm fine with taking on lodash as a dependency @evanlouie thoughts?
