### ISSUE TITLE
Need better error messages for install-lifecycle-pipeline

### ISSUE THREAD

**Issue by timfpark** [microsoft/bedrock#934]
I attempted to create an install-lifecycle-pipeline with spk and was greeted with an error message that doesn't give me a lot to go on in terms of how to fix it:

$ spk project install-lifecycle-pipeline --org-name tpark --devops-project spktest --repo-url https://github.com/timfpark/testService --repo-name "test-service-repo" --pipeline-name test-service-lifecycle-pipeline --personal-access-token mh3jiepsfgfq7deadbeefuo57itpeupwxw7cegucrlrrj7xsba
(node:29134) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info:    Fetched DevOps Client
info:    Creating pipeline for definition
error:   Error creating BuildDefinition; buildApi.createDefinition() returned an invalid value of null
error:   Error occurred during pipeline creation for test-service-lifecycle-pipeline
error:   Error creating definition

Can we add parameter validation and/or better troubleshooting metadata to improve on this?

**Comment by evanlouie** [comment]
The error gets thrown here: https://github.com/CatalystCode/spk/blob/master/src/lib/pipelines/pipelines.ts#L220

Sadly I can't really think of a good way to add more information surrounding the error. No messaging is returned from azdo regarding why the pipeline failed to create; when it fails the `createDefinition` function in `azure-devops-node-api` itself does not throw any errors and only returns a `null` value.

**Comment by andrebriggs** [comment]
@yradsmikham in progress?

**Comment by yradsmikham** [comment]
@andrebriggs yes.

**Comment by sarath-p** [comment]
Related to https://github.com/microsoft/bedrock/issues/951

**Comment by andrebriggs** [comment]
> Related to #951

@sarath-p should @yradsmikham @edaena be communicating around this?

**Comment by yradsmikham** [comment]
The error seen above happens when there is a mismatch in `--repo-name` and `--repo-url`. I think it would help to remove the `--repo-name` argument, so that we can eliminate the possibility of running into this issue. We should be able to extract the `repo-name` from the `repo-url` anyways.

Plus, it's one less argument to worry about.
