### ISSUE TITLE
SPK Infra validate unit test takes 8 seconds to run

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#937]
**Describe the bug:**

![image](https://user-images.githubusercontent.com/3119513/73584610-55739f00-444e-11ea-9ea4-7bf02881fa85.png)

Not sure if we are using the `spk infra validate` command at all. It is not exercised in the [integration tests](https://github.com/CatalystCode/spk/blob/master/tests/infra-validations.sh).

If not let's remove the test that accounts for 22% of the SPK unit test stage

**Comment by yradsmikham** [comment]
The `spk infra validate` may (or may not) be deprecated. The idea for the command was for it to check that users have all the prerequisites installed before executing other `spk infra` commands, such as having az cli, or terraform installed, and also checking for SP env variables.

We should deprecate this functionality, and have it be removed from the tests.

**Comment by andrebriggs** [comment]
Thanks @yradsmikham. Mind removing it?
