### ISSUE TITLE
Bedrock tests need to remove .terraform and related artifacts upon cloning environment

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#941]
**Describe the bug:**  If one is using the current clone of Bedrock for both test and deployment, if there is a lingering .terraform directory or terraform.tfstate file in the environment being cloned, it can cause issues with the test running.  The tests assume a clean slate.

**Comment by andrebriggs** [comment]
@NathanielRose can you confirm?

**Comment by NathanielRose** [comment]
@jmspring can you share the error you received from the test when the environment is not new?

**Comment by jmspring** [comment]
The error received is that resources are not found because it is looking for the existing state.

When you run the bedrock tests locally, they are cloning things from environment/* and if you have existing artifacts in there from a terraform init/terraform apply, the test (when run locally) will fail.
