### ISSUE TITLE
HLD update build step does not update the correct image tag

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#945]
**Describe the bug:**

Committing a change to my application repository does _not_ update the proper component configuration in the HLD generated by reconcile

**To Reproduce:**

1. Set up any buildable application via spk, and create a HLD + HLD lifecycle pipeline
2. Commit to application repository on any ring branch
3. Observe that HLD update step does _not_ update HLD to reflect the container image built at the ring level in the HLD.

**Expected behavior:**
 
My HLD to have a Pull Request against it containing an image tag update against the proper subcomponent

**Additional context:**

https://github.com/CatalystCode/spk/blob/master/src/lib/fileutils.ts#L240 invokes `fab set` on $PROJECT_NAME_LOWER, which does not work as $PROJECT_NAME_LOWER does _not_ reflect the proper path of the chart within an HLD.

A correct invocation of `fab set` would be to update the helm component at the leaf node of the HLD ie:

`fab set --subcomponent "$REPOSITORY.$SERVICE_NAME.$RING.$CHART_NAME  image.tag=$(Build.SourceBranchName)-$(Build.BuildNumber)`

**Does this require updates to documentation?:**

Yes

**Comment by bnookala** [comment]
this _might_ be the same as #908 - @andrebriggs

**Comment by andrebriggs** [comment]
@bnookala yes I think this is the same

**Comment by bnookala** [comment]
Closing as a duplicate - context transferred to #908
