### ISSUE TITLE
Add unit test for spk variable group create command

### ISSUE THREAD

**Issue by dennisseah** [microsoft/bedrock#946]
**As a:**
Developer

**I want:**
Has code tested

**So that:**
quality of the tool is good

**Describe the solution you'd like:**
Add unit test for spk variable group create command

**Acceptance Criteria:**
unit and integration tests passed

**Does this require updates to documentation?:**
No

**Comment by sarath-p** [comment]
Related to #912, #796, and #678

**Comment by andrebriggs** [comment]
@sarath-p why is this on hold?

**Comment by sarath-p** [comment]
> Related to #912, #796, and #678

@andrebriggs - it would be good to do this as part of https://github.com/microsoft/bedrock/issues/796 or after it is completed.

**Comment by andrebriggs** [comment]
This issue is in the critical path for https://github.com/microsoft/bedrock/issues/1006

**Comment by evanlouie** [comment]
Closing: method has been removed
