### ISSUE TITLE
Bedrock OpenHack - Investigation, first draft

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#949]
**As a:**
Developer

**I want:**
A series of OpenHack challenges

**So that:**
I can understand and ramp-up on Bedrock concepts.

**Describe the solution you'd like:**
Deploy the Azure Voting App using a bedrock workflow via `spk`. Setup the cluster using `spk`. Get deployment insights with introspection in `spk`.

**Acceptance Criteria:**

- [x] Setup the Azure voting app with spk

- [x] Cluster setup with spk

- [x] Infra setup scripts

**Describe alternatives you've considered:**

**Additional context:**
Repository: [edaena/ohbedrock](https://github.com/edaena/ohbedrock)

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@edaena is there a sizing for this task?

**Comment by edaena** [comment]
Triaged the remainder of this task.

**Comment by edaena** [comment]
@andrebriggs  closing this initial piece and working on populating the overall work in this Epic and have it ready by tomorrow before planning: https://github.com/microsoft/bedrock/issues/1018
