### ISSUE TITLE
Check whether `azure-pipeline.yaml` file exist in the repo or not before creating the build definition 

### ISSUE THREAD

**Issue by sarath-p** [microsoft/bedrock#951]
**As a:**

Operator/Developer

**I want:**
Inform the user with an actionable message when `pipeline.yaml` file is missing in the repo instead of showing the `Azdo` API error message. 

**So that:**

User can run commands that creates `pipeline.yaml` and push it to the repo.

**Describe the solution you'd like:**
Add a step in `checkDepencies` method to call repo API for file existence in below commands:

- `spk service install-build-pipeline`
- `spk project install-lifecycle-pipeline`
- `spk hld install-manifest-pipeline`

**Acceptance Criteria:**

Implement checks in above commands. 

**Does this require updates to documentation?:**
No

**Comment by andrebriggs** [comment]
Looks good cc @dennisseah
