### ISSUE TITLE
SPK Infra Integration Test Private secrets in Variable group

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#965]
**As a:**
Developer
**I want:**
Improved reliable integration testing for SPK Infra Generation Pipeline
**So that:**
I can ensure that my Generation pipeline will run smoothly in production.
**Describe the solution you'd like:**
- [x] Creation of variable group with private values for sensitive tokens to use in generation pipeline

**Acceptance Criteria:**
Updated  `infra-validations.sh` 

**Additional context:**
Continuation of #872 & #919 

**Does this require updates to documentation?:**
No

**Comment by andrebriggs** [comment]
@NathanielRose please size this

**Comment by NathanielRose** [comment]
> @NathanielRose please size this
> 
> Also feel free to create additional issues from the epic

Just created a the tickets for epic #919
