### ISSUE TITLE
Create helm chart for spektate dashboard

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#967]
**As a:** developer

**I want:** to use a helm chart for the dashboard

**So that:** I can run it in my cluster with ease

**Describe the solution you'd like:**
- [x] Provide a helm chart for dashboard
~~- Embed this in the default hld template so someone who uses spk hld to setup their repositories can have this be included in their manifest~~

**Acceptance Criteria:**
Dashboard can be deployed on Kubernetes easily

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:** Yes

**Comment by andrebriggs** [comment]
@samiyaakhtar I created https://github.com/microsoft/bedrock/issues/1156
