### ISSUE TITLE
Add a ring in SPK

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#969]
**As a:**
spk user
**I want:**
to be able to add a ring
**So that:**
i can have rings
**Describe the solution you'd like:**
a new `spk ring create <ring-name>` command to create a ring in a spk managed project.

**Acceptance Criteria:**
- [x] Create a new command `spk ring create <ring-name>`
- [x] Command adds the ring to the `bedrock.yaml`
- [x] For all services linked in `bedrock.yaml`, add the new ring to the trigger branches in the service's build pipeline

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
Same comment
>@mtarng thanks for creating this. Would love to see this in a user guide as mentioned in #955 before implementing.

**Comment by andrebriggs** [comment]
@mtarng is the sizing correct for this task?
