### ISSUE TITLE
Delete a ring in SPK

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#971]
**As a:**
spk user
**I want:**
to be able to delete a ring
**So that:**
i can have remove a ring i no longer need
**Describe the solution you'd like:**
a new `spk ring delete <ring-name>` command to delete a ring from a spk managed project.

**Acceptance Criteria:**
- [ ] Create a new command `spk ring delete <ring-name>`
- [ ] Command removes the ring from the `bedrock.yaml`
- [ ] For all services linked in `bedrock.yaml`, remove the new ring from the trigger branches in the service's build pipeline
- [ ] This command will not allow the deletion of the default ring. Users must first change the default ring before deleting the current default ring. Setting default ring is captured here: https://github.com/microsoft/bedrock/issues/972

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
Same comment 
>@mtarng thanks for creating this. Would love to see this in a user guide as mentioned in #955 before implementing.

**Comment by andrebriggs** [comment]
@mtarng sam e question here about sizing? Can others take this on?
