### ISSUE TITLE
Improved validation of Generated repo to account for `spk.tfvars` file content

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#973]
**As a:**
Developer
**I want:**
Improved reliable integration testing for SPK Infra Generation Pipeline
**So that:**
I can assure the my generated repo contains the correct spk.tfvr files in the submitted pull request

**Describe the solution you'd like:**
Currently, in our integration test, we simply check for the existence of a PR and the correct files in the Generated repo. We want improved coverage for validating this test by checking the contents of the `spk.tfvars` file
- [x] Improved validation of Generated repo to account for `spk.tfvars` file content

**Acceptance Criteria:**
Updated  `infra-validations.sh` 

**Additional context:**
Continuation of #872 & #919 

**Does this require updates to documentation?:**
No

**Comment by NathanielRose** [comment]
@andrebriggs & @yradsmikham , any thoughts or preference on expectations of validating the Generated Deployment Repo. Initially, I was thinking to simply have a static tf string to inspect the `spk.tfvars` file from the PR that is verified in our `infra-validations.sh`. Would this be adequate?

**Comment by yradsmikham** [comment]
@NathanielRose yeah, that might be the quick and easy way of doing a validation for the `spk.tfvars`.
