### ISSUE TITLE
Build Failed in the "Transform fabrikate definitions and publish to YAML manifests to repo" 

### ISSUE THREAD

**Issue by prakash1097** [microsoft/bedrock#977]
We referred the link, https://github.com/microsoft/bedrock/blob/master/gitops/azure-devops/ManifestGeneration.md
And tried deployment of Bedrock Manifest Generation Pipeline. But the build failed in "Transform Fabrikate definitions and publish Yaml manifests to repo"
![image](https://user-images.githubusercontent.com/48716940/74127439-aaf33d00-4c00-11ea-8c0e-87eeef8bb64b.png)

**Comment by timfpark** [comment]
Could you include details of the error message for your failure?
