### ISSUE TITLE
Introspection backend prototype

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#980]
**As a:** developer

**I want:** the dashboard to make a call to a back end server

**So that:** the dashboard is not storing secrets on the front end

**Describe the solution you'd like:**
- [x] As discussed in https://github.com/microsoft/bedrock/issues/966, move the back end calls from the spektate package to its own node.js (perhaps express) server
- [x] Make this backend code an independent yarn project that can run on a port specified in env vars
- [x] Make the dashboard take in an env var for the backend endpoint and consume the data

Follow up tasks to be created: Create dockerfile for the backend

**Acceptance Criteria:**
The secrets are not stored in front end

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**

**Comment by samiyaakhtar** [comment]
Added a few mini tasks under this task itself, after which we can call the prototype complete.

**Comment by andrebriggs** [comment]
@samiyaakhtar is there a related PR? Can we check this off in #938?
