### ISSUE TITLE
Update Bedrock integration tests to be scheduled weekly when idle

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#984]
**As a:** Operator

**I want:** Weekly scheduled builds for the Bedrock Repo

**So that:** I can assure current state of bedrock is stable with updates to the Azure Terraform Provider

**Acceptance Criteria:**
- [x] Create a scheduled build for the bedrock Master branch to assure integration tests are live
**Describe alternatives you've considered:**

**Additional context:**
Task of https://github.com/microsoft/bedrock/issues/964

**Does this require updates to documentation?:**
No

**Comment by NathanielRose** [comment]
@andrebriggs - Looks like a scheduled trigger overrides the Yaml trigger which means PRs will no longer trigger the build for Bedrock. I can make the triggers Identical to Spk or create a separate pipeline for scheduled builds.

```
Scheduled triggers defined using the pipeline settings UI take precedence over YAML scheduled triggers.

If your YAML pipeline has both YAML scheduled triggers and UI defined scheduled triggers, only the UI defined scheduled triggers are run. To run the YAML defined scheduled triggers in your YAML pipeline, you must remove the scheduled triggers defined in the pipeline setting UI. Once all UI scheduled triggers are removed, a push must be made in order for the YAML scheduled triggers to start running.
```

**Comment by andrebriggs** [comment]
@NathanielRose The trigger from SPK integration tests is in separate pipeline. That might be the best approach if it does override regular build triggers. It is surprising to me that PR triggers and scheduled triggers are mutually exclusive in AzDO yaml. Is that what you found from documentation?
