### ISSUE TITLE
Bedrock env deployment fails with 'ERROR: failed to helm template'

### ISSUE THREAD

**Issue by gagansalaria** [microsoft/bedrock#998]
We re facing an issue while trying to deploy a new bedrock env using below documentation.

https://github.com/microsoft/bedrock/blob/master/docs/azure-simple/README.md

![image](https://user-images.githubusercontent.com/23356081/74586059-ac11d900-5009-11ea-92df-7db7d03a93e9.png)

It appears that --name flag being used in below file is not supported by helm in the latest 3.0 Version.

https://github.com/microsoft/bedrock/blob/master/cluster/common/flux/deploy_flux.sh

echo "generating flux manifests with helm template"
if ! helm template . --name "$RELEASE_NAME"

**Comment by andrebriggs** [comment]
Hi @gagansalaria, at this time we [do not support](https://github.com/microsoft/bedrock/tree/master/cluster#required-tools) Helm 3 but are looking into across Bedrock and Fabrikate.

In Helm 3 the release name is positional arg as opposed to a flag in Helm 2 

Helm3
`helm template [RELEASE_NAME] [CHART] [flags]`

Helm2
`helm template . --name "$RELEASE_NAME"`

To unblock yourself for the moment I would try adjusting your fork of `deploy_flux.sh`. Support for Helm 3 is on our backlog. Pull requests are welcome

**Comment by jred55** [comment]
Created the issue https://github.com/microsoft/bedrock/issues/1102 in the backlog

**Comment by jred55** [comment]
@gagansalaria, pls let us know if you continue to see issues with Helm version. This has been fixed

**Comment by jmspring** [comment]
The issue has been fixed in master
